<!DOCTYPE html>
<html lang="nl">
@php
  $logoPad = public_path('assets/img/iuasr-logo.png');
  $logo = is_file($logoPad) ? 'data:image/png;base64,'.base64_encode(file_get_contents($logoPad)) : null;
@endphp
<head>
  <meta charset="utf-8">
  <style>
    @page { margin: 42px 46px 64px 46px; }
    body { font-family: "DejaVu Sans", sans-serif; color: #1E1446; font-size: 10.5pt; line-height: 1.5; }
    #footer { position: fixed; bottom: -44px; left: 0; right: 0; height: 30px; border-top: 1px solid #ddd; padding-top: 6px; font-size: 8pt; color: #666; }
    #footer .r { text-align: right; }
    #footer .num:after { content: counter(page); }
    .cover { border-bottom: 3px solid #1E1446; padding-bottom: 14px; margin-bottom: 20px; }
    .cover img { height: 96px; }
    .cover h1 { font-size: 23pt; font-weight: bold; margin: 14px 0 2px; }
    .cover .sub { font-size: 11pt; color: #666; margin: 0; }
    h2 { font-size: 14pt; color: #C8102E; margin: 20px 0 6px; border-bottom: 1px solid #eee; padding-bottom: 3px; page-break-after: avoid; }
    h3 { font-size: 11.5pt; margin: 14px 0 4px; page-break-after: avoid; }
    p { margin: 0 0 9px; }
    ul, ol { margin: 0 0 10px; padding-left: 20px; }
    li { margin: 0 0 5px; }
    code, .cmd { font-family: "DejaVu Sans Mono", monospace; font-size: 9pt; }
    .cmd { display: block; background: #1E1446; color: #EDEBF5; padding: 8px 12px; border-radius: 5px; margin: 6px 0 12px; white-space: pre-wrap; word-break: break-all; }
    .kv { width: 100%; border-collapse: collapse; font-size: 9.5pt; margin: 6px 0 12px; }
    .kv td { border-bottom: 1px solid #eee; padding: 5px 8px; }
    .kv td.k { color: #666; width: 190px; }
    .let { background: #FBEFEF; border-left: 3px solid #C8102E; padding: 8px 12px; margin: 10px 0; font-size: 10pt; }
    .tip { background: #F0F5F3; border-left: 3px solid #285C4D; padding: 8px 12px; margin: 10px 0; font-size: 10pt; }
    b { color: #1E1446; }
    ol.stap > li { margin-bottom: 9px; }
  </style>
</head>
<body>
  <div id="footer">
    <table style="width:100%;"><tr>
      <td>IUASR Management Systeem — Technische handleiding &amp; herstel · VERTROUWELIJK · {{ now()->format('d-m-Y') }}</td>
      <td class="r">Pagina <span class="num"></span></td>
    </tr></table>
  </div>

  <div class="cover">
    @if ($logo)<img src="{{ $logo }}" alt="IUASR">@endif
    <h1>Technische handleiding &amp; data-recovery</h1>
    <p class="sub">Voor technisch beheer · Intern managementsysteem · IUASR</p>
  </div>

  <div class="let">Dit document is bestemd voor <b>technisch personeel/beheerders</b>. Het beschrijft de architectuur, het maken van back-ups en de <b>herstelprocedure</b>. Bewaar het vertrouwelijk.</div>

  <h2>0. Platform: modules</h2>
  <p>Het systeem is een multi-module platform. Na de login (route <code>modules.kiezen</code>, <code>/modules</code>) kiest de gebruiker een module. Tabel <code>modules</code> (<code>sleutel</code>, <code>naam</code>, <code>actief</code>, <code>volgorde</code>) is de registry; de vijf modules worden in de create-migratie ingevoegd. Nieuwe module toevoegen = één rij plus haar schermen, geen ingreep in de kern.</p>
  <p>Moduletoegang volgt uit de rol: <code>Rol::moduleSleutels()</code> geeft de toegestane modulesleutels (<code>['*']</code> voor Beheerder). <code>Module::toegankelijkVoor()</code> toetst toegang, <code>bruikbaarVoor()</code> = toegankelijk én <code>actief</code>. Een module opent op <code>Module::startRoute()</code> (nu alleen Studentenzaken → <code>dashboard</code>). Nog niet gebouwde modules staan op <code>actief=false</code> en worden als 'Binnenkort' getoond. De rollen blijven de bestaande enum <code>App\Enums\Rol</code>; de cursus-specifieke rollen komen bij de Cursussen-module.</p>

  <h2>0b. Module Cursussen Administratie</h2>
  <p>Aparte administratie, lichter regime (geen BSN/DUO). Tabellen: <code>cursussen</code> (code, naam, cursusgeld, start/eind, directeur_id, actief; drie cursussen in de create-migratie), <code>cursisten</code> (aangepaste, lichtere kopie van <code>studenten</code>; <code>cursistnummer</code> = C + jaar + volgnr via <code>CursistnummerGenerator</code>), <code>cursusinschrijvingen</code> (cursist × cursus, <code>totaalbedrag</code> als momentopname van het cursusgeld). Controllers onder <code>App\Http\Controllers\Cursus\*</code>, routes onder prefix <code>cursussen</code>. Rol <code>Cursusadministratie</code> toegevoegd aan de enum (enum-kolom via ALTER). Bulk-import leest .xlsx én .csv via <code>App\Support\Tabellezer</code> (PhpSpreadsheet), kolomherkenning op naam. Cursusdirecteuren met toegangsbeperking volgen in een latere fase.</p>
  <p><b>Cursus kopiëren (Beheerder).</b> <code>CursusController@kopieForm</code> op route <code>cursussen.kopieren</code> (<code>/cursussen/beheer/{bron}/kopieren</code>, <code>rol:beheerder</code>) rendert het bestaande <code>cursussen.form</code> vooraf ingevuld met een niet-persisted <code>new Cursus()</code> op basis van de bron (cursusgeld, omschrijving, looptijd, directeur; code leeg). Opslaan verloopt via de reguliere <code>store</code> — er is dus geen aparte kopie-actie; de nieuwe cursus ontstaat uit de ingevulde velden. Inschrijvingen/cursisten worden NIET meegekopieerd. Let op de route-model-binding: de parameter heet bewust <code>{bron}</code> zodat hij bindt op <code>kopieForm(Cursus $bron)</code> (naam moet overeenkomen, anders krijgt de methode een leeg model).</p>
  <p><b>Directe cursusknoppen op het welkomstscherm.</b> <code>ModuleController@index</code> geeft de voor de gebruiker zichtbare, actieve cursussen mee (<code>Cursus::query()->zichtbaarVoor()</code>); <code>modules/index.blade.php</code> rendert ze als aparte tegels onder "Cursussen". Elke tegel linkt naar de cursus-startpagina <code>cursussen.cursus</code> (<code>/cursussen/cursus/{cursus}</code>, <code>CursusDashboardController@cursus</code>, view <code>cursussen.cursus</code>) in de dashboardgroep <code>rol:cursusadministratie,financien,beheerder,bestuur</code> met <code>abort_unless($cursus->zichtbaarVoor())</code>. De pagina toont per cursus de statusverdeling, financiële kerncijfers (<code>Cursusrapport::financieelTotaal</code>) en de cursisten, met snelkoppelingen naar cursusgelden (<code>?cursus=</code>) en rapportage. De naam-tegel toont bewust géén cursusgeld.</p>
  <p><b>Cursusrapportage &amp; dashboards (Fase E).</b> Aggregatieklasse <code>App\Support\Cursusrapport</code>: per cursus de inschrijvingen (uitgesplitst per <code>CursusinschrijvingStatus</code>) en de cursusgelden (verschuldigd/betaald/openstaand + betaalgraad, via <code>Cursusgeldstatus</code>), plus totalen en een verdeling naar betaalmethode. Financiële cijfers tellen alleen niet-geannuleerde inschrijvingen; alleen betalingen met status <code>Betaald</code> gelden als voldaan. <code>Cursus\CursusrapportController</code> (<code>index</code> = view <code>cursussen.rapport</code>, <code>export</code> = CSV op cursistniveau, gelogd als <code>INZAGE</code> veld <code>cursusrapport_export</code>). Routes <code>cursussen.rapport</code> + <code>cursussen.rapport.export</code> in de dashboardgroep <code>rol:cursusadministratie,financien,beheerder,bestuur</code>, dezelfde <code>Cursus::query()->zichtbaarVoor()</code>-scoping als het dashboard (directeur = eigen cursus[sen]). Het cursusdashboard toont via <code>Cursusrapport::financieelTotaal()</code> de betaalgraad en het openstaande bedrag; de Bestuurspagina linkt door naar het rapport. Rendering met de bestaande chart-partials. 8 tests (<code>CursusrapportTest</code>); 327 groen.</p>
  <p><b>Cursusdirecteuren — toegang per cursus (Fase D).</b> De rol <code>Cursusadministratie</code> is voortaan <b>cursusgebonden</b> (need-to-know), analoog aan de opleidinggebonden Directie. Sleutel is de bestaande FK <code>cursussen.directeur_id</code> (geen pivot nodig): een directeur dirigeert de cursussen waarvan hij <code>directeur_id</code> is (<code>User::gedirigeerdeCursussen()</code>, <code>User::cursusIds()</code>, <code>User::isCursusBeperkt()</code> → alleen Cursusadministratie). Scopes <code>Cursus::scopeZichtbaarVoor()</code> / <code>Cursist::scopeZichtbaarVoor()</code> (aanroepen via <code>::query()->zichtbaarVoor()</code> om botsing met de gelijknamige instance-guard te vermijden) + instance-guards <code>Cursus::zichtbaarVoor()/beheerbaarVoor()</code> en <code>Cursist::zichtbaarVoor()</code>. Toegepast in alle vier de admin-controllers: dashboard (drie tellingen gescoped), cursusbeheerlijst, cursistenlijst + withCount, cursus-dropdowns, en per-record guards op edit/update/show/inschrijven. <b>Rolverdeling in de routes:</b> cursus aanmaken/verwijderen én directeur toewijzen is <code>rol:beheerder</code> (server-side; in <code>CursusController::update</code> wordt <code>directeur_id</code> alleen toegepast als de gebruiker Beheerder is → geen rechtenescalatie). Cursusbeheer-details en cursisten/inschrijvingen muteren: <code>rol:cursusadministratie,beheerder</code> (gescoped). Boekhouding (betalingen): <code>rol:financien,beheerder</code>, ongescoped (alle cursussen). Dashboard en cursisteninzage ook voor het <b>Schoolbestuur</b> (<code>Rol::moduleSleutels()</code> voor Bestuur = <code>['studentenzaken','cursussen']</code>; <code>Rol::magCursusInzien()</code> = Cursusadministratie/Beheerder/Bestuur), alleen-lezen — de mutatieknoppen hangen in de views aan <code>magCursusBeheer()</code>. Seed (definitief, opdrachtgever): Arabische Taal → Hafsa; Hifz + Ijaaza → Omar (twee directeuren — Arabisch apart, Hifz en Ijaaza samen). Guarded datamigraties (<code>wijs_cursusdirecteuren_toe</code>, <code>herverdeel_cursusdirecteuren_een_per_cursus</code>) vullen/herverdelen een bestaande database (draaien op een verse migratie vóór de seeders en doen dan niets). 15 tests (<code>CursusdirecteurTest</code> + tegentest); 312 groen.</p>
  <p><b>Cursusgelden &amp; boekhouding (Fase C).</b> Tabel <code>cursusbetalingen</code> (<code>cursusinschrijving_id</code> FK cascade, <code>betaalmethode</code>, <code>bedrag</code> decimal(10,2), <code>betaaldatum</code>, <code>betalingsstatus</code>, <code>referentienummer</code>, <code>opmerking</code>, <code>geregistreerd_door_id</code> FK users nullOnDelete). Enums <code>App\Enums\Betaalmethode</code> (ideal/overboeking/contant) en <code>App\Enums\Cursusbetaalstatus</code> (in_afwachting/betaald/mislukt/terugbetaald; alleen <code>Betaald</code> telt als voldaan). De financiële status per inschrijving is <b>afgeleid, niet opgeslagen</b>: <code>App\Support\Cursusgeldstatus::voor()</code> zet <code>totaalbedrag</code> af tegen de som van de betalingen met status <code>Betaald</code> → <code>{totaal, betaald, openstaand, status}</code> (voldaan/deels/open). Controller <code>Cursus\CursusbetalingController</code> (overzicht/registreer/bijwerken/verwijderen); routes onder prefix <code>cursussen</code> met middleware <code>rol:financien,beheerder</code>. Het cursusdashboard staat op <code>rol:cursusadministratie,financien,beheerder</code> (de modulekiezer stuurt Financiën naar <code>cursussen.dashboard</code>); cursus-/cursistbeheer blijft <code>rol:cursusadministratie,beheerder</code>. Rolregels: <code>Rol::magCursusBeheer()</code> en <code>Rol::magCursusFinancien()</code> (met <code>User</code>-delegates) sturen de rolbewuste sidebar en dashboardknoppen. Wijzigen/verwijderen van betalingen wordt via <code>AuditLogger</code> gelogd (veld <code>cursusbetaling</code>).</p>

  <h2>0b2. Module Relatiebeheer &amp; Stagebeheer (Fase A)</h2>
  <p><b>Opzet.</b> Opleidingoverstijgende module (PABO, Bachelor Islamitische Theologie, Master IGV) voor externe relaties. De placeholder-module <code>stage</code> is via de datamigratie <code>stage_module_naar_relatiebeheer</code> hernoemd naar sleutel <code>relatiebeheer</code> (naam "Relatiebeheer &amp; Stage") en met <code>activeer_relatiebeheer_module</code> op <code>actief=true</code> gezet; <code>Module::START_ROUTES['relatiebeheer'] = 'relaties'</code>. Twee nieuwe rollen <code>Relatiebeheerder</code> en <code>Stagecoordinator</code> in <code>App\Enums\Rol</code> (enum-kolom via ALTER-migratie <code>add_relatiebeheer_rollen</code>, die <code>Rol::waarden()</code> leest — enum-case dus vóór de migratie). Ontwerp: <code>docs/MODULE-RELATIEBEHEER.md</code>.</p>
  <p><b>Datamodel.</b> <code>organisatie_types</code> (opzoektabel; <code>code</code> uniek, <code>naam</code>, <code>opleiding_id</code> nullable = per opleiding instelbaar of null=alle, <code>actief</code>), <code>organisaties</code> (<code>relatienummer</code> uniek/leesbaar via <code>App\Support\RelatienummerGenerator</code> = <code>R</code> + jaar + volgnr, <code>organisatie_type_id</code> nullOnDelete, adres/contactvelden, <code>actief</code>, <code>opmerkingen</code>) en de pivot <code>organisatie_opleidingen</code> (echte FK's, cascade, unique). Modellen <code>App\Models\Organisatie</code> en <code>OrganisatieType</code>.</p>
  <p><b>Scoping &amp; rollen.</b> Opleidinggebonden (need-to-know), analoog aan de Directie: de koppeling loopt via dezelfde <code>User::opleidingen()</code>-relatie (<code>directie_opleidingen</code>). <code>Rol::isRelatieBeperkt()</code> = Relatiebeheerder/Stagecoordinator/Directie; <code>Organisatie::scopeZichtbaarVoor()</code> filtert op <code>whereHas('opleidingen', ... whereIn opleidingIds)</code>, plus instance-guards <code>zichtbaarVoor()</code>/<code>beheerbaarVoor()</code>. Rolregels: <code>Rol::magRelatiebeheer()</code> (Relatiebeheerder/Stagecoordinator/Beheerder = aanmaken/wijzigen), <code>magStagebeheer()</code> (Stagecoordinator/Beheerder — stageplaatsen, latere fase), <code>magRelatieInzien()</code> (+ Directie, Bestuur). <code>moduleSleutels()</code>: de twee nieuwe rollen → <code>['relatiebeheer']</code>, Directie → <code>['studentenzaken','relatiebeheer']</code>, Bestuur → <code>['studentenzaken','cursussen','relatiebeheer']</code>. <b>Let op:</b> bij een nieuwe rol alle exhaustive <code>match</code>-methodes zonder <code>default</code> in <code>Rol</code> aanvullen (label, magCijfersInzien, magInschrijvingBeheren, magPresentieInzien, magAanwezigheidsregelingZien, moduleSleutels).</p>
  <p><b>Controller/routes/views.</b> <code>App\Http\Controllers\Relatie\OrganisatieController</code> (index met filters q/type/opleiding/status, create/store/show/edit/update/status-toggle). Routes onder prefix <code>relatiebeheer</code>: beheergroep <code>rol:relatiebeheerder,stagecoordinator,beheerder</code> (bewust vóór de inzagegroep zodat <code>/organisaties/nieuw</code> niet als id bindt), inzagegroep <code>rol:relatiebeheerder,stagecoordinator,directie,bestuur,beheerder</code> (<code>relaties</code>, <code>relaties.show</code>). Views <code>resources/views/relaties/{index,form,show}</code>; sidebar-tak <code>$inRelatiemodule = routeIs('relaties*')</code>. Aanmaken/wijzigen gelogd via <code>AuditLogger</code> (veld <code>organisatie</code>/<code>organisatie_status</code>). Server-side afgedwongen dat een opleidinggebonden gebruiker alleen de <b>eigen</b> opleiding(en) kan koppelen (<code>Rule::in($toegestaan)</code> op <code>opleidingen.*</code>). <b>AVG-grens:</b> uitsluitend organisatie- en contactgegevens, nooit leerling-/cliëntgegevens. Landing-redirect (<code>DashboardController</code>) stuurt module-only rollen naar <code>relaties</code>. Startdata op de draaiende DB via guarded <code>seed_relatiebeheer_startdata</code> (no-op op verse test-DB). 10 tests (<code>RelatiebeheerModuleTest</code>); 361 groen.</p>

  <p><b>Contactpersonen &amp; relatiekaart (Fase B).</b> Tabel <code>contactpersonen</code> (<code>organisatie_id</code> FK cascade, voornaam/achternaam, functie, email, mobiel, telefoon, afdeling, <code>voorkeur_communicatie</code> [e-mail/telefoon/teams], linkedin, <code>actief</code>). Model <code>App\Models\Contactpersoon</code> (<code>belongsTo</code> organisatie, <code>volledigeNaam()</code>, scope <code>actief</code>); <code>Organisatie::contactpersonen()</code> <code>HasMany</code>. <code>Relatie\ContactpersoonController</code> (create/store genest onder <code>{organisatie}</code>, edit/update/status op <code>{contactpersoon}</code>) in de beheergroep <code>rol:relatiebeheerder,stagecoordinator,beheerder</code>; autorisatie volgt de organisatie (<code>abort_unless($cp->organisatie->beheerbaarVoor())</code>). De relatiekaart (<code>relaties.show</code>) laadt de contactpersonen (eager, actief eerst) en toont ze in een paneel met toevoegen/bewerken/inactiveren; view <code>relaties/contactpersoon-form</code>. Sidebar-tak <code>$inRelatiemodule</code> matcht ook <code>contactpersonen*</code>. Mutaties gelogd (<code>veld: contactpersoon</code>/<code>contactpersoon_status</code>); inactiveren i.p.v. verwijderen (historie/AVG). Synthetische seed in <code>OrganisatieSeeder</code> + guarded datamigratie <code>seed_contactpersonen_startdata</code>. 5 tests (<code>ContactpersoonTest</code>); 366 groen.</p>

  <p><b>Contactmomenten, notities &amp; tijdlijn (Fase C).</b> Tabellen <code>contactmoment_types</code> (opzoektabel, in <code>ReferentieController</code> als <code>contactmomenttypes</code>), <code>contactmomenten</code> (FK organisatie cascade; contactpersoon/type/medewerker nullOnDelete; datum, tijd, onderwerp, samenvatting, <code>vervolgdatum</code>) en <code>relatie_notities</code> (organisatie cascade, auteur nullOnDelete, categorie, tags, tekst). Modellen <code>Contactmoment</code>, <code>ContactmomentType</code>, <code>RelatieNotitie</code>; <code>Organisatie::contactmomenten()/notities()</code>. Controllers <code>Relatie\ContactmomentController</code> (create/store/edit/update — geen delete, historie) en <code>Relatie\RelatieNotitieController</code> (store/destroy), beide in de beheergroep <code>rol:relatiebeheerder,stagecoordinator,beheerder</code>, autorisatie via <code>organisatie->beheerbaarVoor()</code>. Bij store wordt de <code>contactpersoon_id</code> gevalideerd met <code>Rule::in</code> op de contactpersonen van díe organisatie (geen kruiskoppeling). Contactmomenten worden gelogd (<code>veld: contactmoment</code>); notities niet (werkinformatie). De <b>tijdlijn</b> is afgeleid via <code>App\Support\Relatietijdlijn::voor()</code> — merge van contactmomenten + notities + audit-logregels (<code>onderwerp_type</code> Organisatie/Contactpersoon), gesorteerd op moment; geen aparte historietabel. De relatiekaart (<code>relaties.show</code>) toont de panelen Contactmomenten, Notities (inline formulier) en Historie/tijdlijn. Views <code>relaties/contactmoment-form</code>. Sidebar-tak matcht ook <code>contactmomenten*</code>. Synthetische seed in <code>OrganisatieSeeder</code> + guarded datamigratie <code>seed_relatie_fase_c_startdata</code>. 6 tests (<code>ContactmomentTest</code>); 372 groen.</p>

  <p><b>Stagebeheer — stageplaatsen &amp; stages (Fase D).</b> Enum <code>App\Enums\Stagestatus</code> (aangevraagd/lopend/afgerond/afgebroken; <code>teltVoorBezetting()</code>, <code>badge()</code>). Tabellen <code>stageplaatsen</code> (organisatie/opleiding/periode FK; leerjaar, aantal_plaatsen, max_studenten, eisen/specialisaties/werkdagen, actief) en <code>stages</code> (leesbaar <code>stagenummer</code> via <code>StagenummerGenerator</code>; student/organisatie/stageplaats/opleiding FK; <code>stagebegeleider_id</code> → users [rol Docent], <code>werkplekbegeleider_id</code> → contactpersonen; start/eind, <code>status</code>, <code>beoordeling</code> voldoende/onvoldoende, toelichting). Modellen <code>Stage</code> (scopeZichtbaarVoor op <code>opleiding_id</code>, beheerbaarVoor = <code>magStagebeheer</code> + zichtbaar) en <code>Stageplaats</code> (<code>bezetting()</code>/<code>vrijePlaatsen()</code> afgeleid uit de stages met status aangevraagd/lopend); <code>Organisatie::stageplaatsen()/stages()</code> + <code>stagesBeheerbaarVoor()</code>. Controllers <code>Relatie\StageplaatsController</code> en <code>Relatie\StageController</code>; muteren in de groep <code>rol:stagecoordinator,beheerder</code>, het Stages-overzicht (<code>stages</code>) in de bredere inzagegroep. <b>Server-side afgedwongen:</b> de opleiding moet een van de organisatie zijn (en binnen de scope van de gebruiker); de student moet een actieve inschrijving in die opleiding hebben; stageplaats en werkplekbegeleider moeten bij dezelfde organisatie horen (alles via <code>Rule::in</code>). De stagebegeleider moet rol Docent hebben. De <b>beoordeling</b> is gevoelig: een wijziging wordt gelogd met veld <code>stage_beoordeling</code> (anders <code>stage</code>). Views <code>relaties/stage-form</code>, <code>relaties/stageplaats-form</code>, <code>relaties/stages-index</code>; panelen Stageplaatsen &amp; Stages op de relatiekaart. Sidebar-item <b>Stages</b>; <code>$inRelatiemodule</code> matcht ook <code>stages*</code>/<code>stageplaatsen*</code>. Synthetische seed (3 stageplaatsen + 1 demo-stage) + guarded datamigratie <code>seed_relatie_fase_d_startdata</code>. 7 tests (<code>StageTest</code>); 379 groen.</p>

  <p><b>Taken &amp; agenda (Fase E).</b> Tabellen <code>relatie_taken</code> (eigen tabel, gemodelleerd naar Graph <code>todoTask</code>; organisatie cascade, stage nullOnDelete, titel/omschrijving, toegewezen/aangemaakt/afgerond-door FK users, start/vervaldatum, prioriteit, status, afgerond_op) en <code>agenda_afspraken</code> (organisatie cascade, stage/medewerker nullOnDelete, type, datum, tijd_van/tot, locatie, status, omschrijving). Enum-hergebruik <code>TaakStatus</code>/<code>TaakPrioriteit</code>; nieuw <code>App\Enums\AfspraakType</code> (schoolbezoek/stagebezoek/evaluatie/overleg/open_dag). Modellen <code>Relatietaak</code> (<code>isTeLaat()</code> afgeleid uit vervaldatum+status, <code>scopeZichtbaarVoor</code> via de organisatie-opleidingen) en <code>Afspraak</code>; <code>Organisatie::relatietaken()/afspraken()</code>. Controllers <code>Relatie\RelatietaakController</code> (store/edit/update/afronden/destroy; <code>afronden</code> togglet status en zet/wist <code>afgerond_op</code>+<code>afgerond_door_id</code>) en <code>Relatie\AfspraakController</code> (create/store/edit/update/destroy + <code>index</code> = module-brede planning: aankomende afspraken + open taken, gescoped). Muteren in de groep <code>rol:relatiebeheerder,stagecoordinator,beheerder</code> met <code>organisatie->beheerbaarVoor()</code>; de planning (<code>agenda</code>) in de inzagegroep (Directie/Bestuur lezen mee). <b>Geen audit-logging</b> (werkverdeling). Server-side: toegewezene ∈ module-rollen, stage/afspraak-koppeling ∈ dezelfde organisatie (<code>Rule::in</code>). Views <code>relaties/relatietaak-form</code>, <code>relaties/afspraak-form</code>, <code>relaties/agenda-index</code>; panelen Taken (inline quick-add) &amp; Agenda op de relatiekaart. Sidebar-item <b>Agenda &amp; taken</b>; <code>$inRelatiemodule</code> matcht ook <code>agenda*</code>/<code>afspraken*</code>/<code>relatietaken*</code>. Synthetische seed + guarded datamigratie. 7 tests (<code>TakenAgendaTest</code>); 386 groen. (<code>phpunit.xml</code> kreeg <code>memory_limit=1024M</code> zodat de volledige suite via <code>artisan test</code> draait.)</p>

  <p><b>Documenten &amp; overeenkomsten (Fase F).</b> Tabellen <code>relatie_documenten</code> (organisatie cascade, stage nullOnDelete, categorie [<code>RelatieDocument::CATEGORIEEN</code>], bestandsnaam/pad/mime/grootte, <code>versie</code> + <code>vorige_versie_id</code> zelf-FK voor versiebeheer, geupload_door) en <code>overeenkomsten</code> (type/status als enums <code>OvereenkomstType</code>/<code>OvereenkomstStatus</code>, start/verloopdatum, <code>ondertekend_document_id</code> → <code>ondertekende_documenten</code>). Modellen <code>RelatieDocument</code> (<code>isHuidigeVersie()</code> = geen nieuwer document verwijst hiernaar) en <code>Overeenkomst</code> (<code>isVerlopen()</code>/<code>dagenTotVerloop()</code>, <code>scopeZichtbaarVoor</code>); <code>Organisatie::documenten()/overeenkomsten()</code>. Controllers <code>Relatie\RelatieDocumentController</code> (store/versie/download/destroy — private schijf <code>local</code>, upload/inzage/verwijdering gelogd; <code>versie</code> maakt een nieuw record met <code>versie+1</code> + <code>vorige_versie_id</code>) en <code>Relatie\OvereenkomstController</code> (create/store/edit/update/download/destroy). <b>Ondertekening hergebruikt de bestaande module:</b> een meegestuurde PDF gaat door <code>App\Support\Documentondertekening::ondertekenUpload()</code> (SHA-256 + verificatiecode + waarmerk-certificaat), de resulterende <code>OndertekendDocument</code> wordt gekoppeld en de status wordt <code>Getekend</code>; download serveert de gewaarmerkte bytes met een eigen route (zodat de module-rollen niet afhankelijk zijn van de rolgroep van het ondertekenarchief). Muteren in de beheergroep <code>rol:relatiebeheerder,stagecoordinator,beheerder</code> (<code>organisatie->beheerbaarVoor()</code>); downloads in de inzagegroep (Directie/Bestuur mogen inzien, gelogd). De signalering <b>‘contracten die verlopen’</b> (verloopdatum ≤ 60 dagen of verstreken, niet opgezegd) staat op de planning (<code>agenda</code>) en als badge op de relatiekaart. Views <code>relaties/overeenkomst-form</code>; panelen Overeenkomsten &amp; Documenten (met inline upload/nieuwe-versie) op de relatiekaart. Synthetische seed (1 overeenkomst) + guarded datamigratie. 6 tests (<code>DocumentOvereenkomstTest</code>, incl. echte waarmerking met <code>Storage::fake</code>); 392 groen.</p>

  <p><b>Dashboard &amp; rapportage (Fase G).</b> Aggregatieklasse <code>App\Support\Relatierapport</code> — alle methodes nemen een optionele <code>?array $oplIds</code> (null = geen beperking) zodat de opleidinggebonden scoping consistent is: <code>kerncijfers()</code> (organisaties, contactpersonen, stageplaatsen, lopende/te-beoordelen stages, open taken, aankomende bezoeken, aflopende contracten, nieuwe documenten, bezettingsgraad), <code>bezettingsgraad()</code> (bezet ÷ som max_studenten), <code>teBeoordelen()</code> (beoordeling null én afgerond of einddatum verstreken), <code>evaluatie()</code> (% voldoende), <code>stagesPerStatus()</code>/<code>organisatiesPerType()</code> (chart-data) en <code>rijen()</code> (per organisatie, met <code>withCount</code>). Controller <code>Relatie\RelatieDashboardController</code> (<code>index</code> = view <code>relaties.dashboard</code>, <code>rapport</code> = <code>relaties.rapport</code>, <code>export</code> = CSV met BOM, gelogd als INZAGE veld <code>relatierapport_export</code>). De scope komt uit <code>isRelatieBeperkt() ? opleidingIds() : null</code>. Routes <code>relatiebeheer.dashboard</code>/<code>.rapport</code>/<code>.rapport.export</code> in de inzagegroep; de <b>modulestartroute is nu het dashboard</b> (<code>Module::START_ROUTES['relatiebeheer'] = 'relatiebeheer.dashboard'</code>, de landing-redirect en de organisatielijst verhuisd naar <code>/organisaties</code> met behoud van de routenaam <code>relaties</code>). Rendering met de bestaande chart-partials (donut/bar) en <code>iuasr-dash-stat</code>-tegels. Sidebar kreeg <b>Overzicht</b> en <b>Rapportage</b>; <code>$inRelatiemodule</code> matcht ook <code>relatiebeheer.*</code>. 5 tests (<code>RelatieDashboardTest</code>) + <code>DashboardStatistiekTest</code> bijgewerkt; 397 groen.</p>

  <p><b>Slimme functies (Fase H).</b> Intranet-veilig — geen externe koppelingen. (1) <b>Globaal zoeken</b>: <code>Relatie\ZoekController</code> (<code>relatiebeheer.zoeken</code>) doorzoekt organisaties, contactpersonen en stages tegelijk, opleidinggebonden gescoped (<code>zichtbaarVoor</code> / <code>whereHas('organisatie', …zichtbaarVoor)</code>), min. 2 tekens. (2) <b>iCal-export</b>: <code>AfspraakController@ical</code> (<code>relatiebeheer.agenda.ics</code>) bouwt een <code>text/calendar</code>-bestand (VCALENDAR/VEVENT met DTSTART/DTEND of all-day, geëscapete velden) van de aankomende gescopede afspraken — te importeren in Outlook/Google/Apple; een download, geen live sync. (3) <b>Actiepunt → taak</b>: <code>ContactmomentController@maakTaak</code> (<code>contactmomenten.taak</code>, beheergroep) maakt van een contactmoment met vervolgdatum een <code>Relatietaak</code> (titel “Opvolging: …”, vervaldatum = vervolgdatum), 422 zonder vervolgdatum. Sidebar kreeg <b>Zoeken</b>; iCal-knop op de planning; “→ Taak”-knop op het contactmomenten-paneel. <b>Bewust buiten scope</b> (en zo genoteerd): tweewegs Outlook/Graph-synchronisatie en het koppelen van e-mail aan een relatie — die vergen een externe provider en passen niet in het intranet-only regime. 5 tests (<code>RelatieSlimmeFunctiesTest</code>); 402 groen. <b>Hiermee is de module Relatiebeheer &amp; Stage (Fasen A–H) afgerond.</b></p>

  <h2>0b3. Module HR / Personeelszaken (Fase A)</h2>
  <p><b>Opzet.</b> Nieuwe module (placeholder <code>hr</code> geactiveerd) voor personeelsadministratie. Twee rollen <code>Hrmedewerker</code> + <code>Manager</code> in <code>App\Enums\Rol</code> (enum-kolom via ALTER-migratie <code>add_hr_rollen</code>). <code>Rol::magHrBeheer()</code> (HR/Beheer), <code>magHrInzien()</code> (+ Manager, Bestuur), <code>isHrTeamBeperkt()</code> (Manager), <code>magVerlofBeoordelen()</code>. <code>moduleSleutels</code>: HR-rollen → <code>['hr']</code>, Bestuur krijgt <code>'hr'</code> erbij. Startroute <code>hr.dashboard</code>. Ontwerp: <code>docs/MODULE-HR-PERSONEELSZAKEN.md</code>. Stack bewust Laravel/MySQL (niet de generieke React/Node-suggestie uit de prompt); NL (EN-i18n later). Beslissingen (opdrachtgever): voltijdsnorm <b>40 uur</b> (config <code>sis.hr.voltijd_uren</code>), BSN <b>veld klaar, standaard uit</b> (<code>sis.hr.bsn_ingeschakeld</code>), verlof door <b>manager, HR als terugval</b>.</p>
  <p><b>Datamodel.</b> <code>functies</code> (opzoektabel: docent/staf/management), <code>afdelingen</code> (self-ref <code>bovenliggende_afdeling_id</code> voor teams; <code>manager_id</code> → medewerkers, FK apart toegevoegd wegens circulaire afhankelijkheid), <code>medewerkers</code> (personeelsmaster; leesbaar <code>personeelsnummer</code> via <code>PersoneelsnummerGenerator</code>; <code>user_id</code> uniek/nullable voor self-service; <code>docent_id</code>, <code>manager_id</code> self-ref, <code>afdeling_id</code>, <code>functie_id</code>; BSN versleuteld via <code>VersleuteldGevoeligVeld</code>, <code>$hidden</code>; <code>status</code> enum <code>MedewerkerStatus</code>), <code>dienstverbanden</code> (contracthistorie; <code>contracttype</code> enum, uren/week; <b>FTE afgeleid</b> = uren ÷ voltijd) en <code>hr_documenten</code> (private schijf, gelogd). Modellen <code>Medewerker</code> (<code>huidigDienstverband()</code>, <code>fte()</code>, <code>scopeZichtbaarVoor</code> = Manager ziet eigen team via <code>manager_id</code> + zichzelf), <code>Dienstverband</code> (<code>fte()</code>/<code>isLopend()</code>), <code>Afdeling</code>, <code>Functie</code>, <code>HrDocument</code>; <code>User::medewerker()</code> + HR-delegates. Functies/afdelingen beheerbaar via Opzoektabellen.</p>
  <p><b>Controllers/routes/views.</b> <code>Hr\HrDashboardController</code> (kerncijfers gescoped), <code>Hr\MedewerkerController</code> (index met filters, create/store/show/edit/update; personeelsnummer met retry; BSN alleen als ingeschakeld), <code>Hr\DienstverbandController</code> en <code>Hr\HrDocumentController</code>. Routes onder prefix <code>hr</code>: beheergroep <code>rol:hrmedewerker,beheerder</code> (bewust vóór de inzagegroep i.v.m. <code>medewerkers/nieuw</code>), inzagegroep <code>rol:hrmedewerker,manager,beheerder,bestuur</code>. Mutaties gelogd (<code>medewerker</code>/<code>dienstverband</code>/<code>hr_document</code>). Eigen sidebar-tak (<code>$inHrmodule</code>) en <code>$hrMenu</code>; landing-redirect voor HR-rollen naar <code>hr.dashboard</code>. Views <code>hr/{dashboard,medewerkers-index,medewerker-form,medewerker-show,dienstverband-form}</code>. Synthetische <code>HrSeeder</code> (3 afdelingen, 4 functies, 6 medewerkers, HR-accounts Nadia Aslan/Ruben Smit) + guarded datamigratie <code>seed_hr_startdata</code>. 8 tests (<code>HrModuleTest</code>); 410 groen.</p>

  <p><b>Verlof &amp; verzuim (HR Fase B).</b> Enums <code>Verloftype</code> (vakantie/bijzonder/ouderschap/studie) en <code>Verlofstatus</code> (aangevraagd/goedgekeurd/afgewezen/ingetrokken). Tabellen <code>verlofsaldi</code> (recht per medewerker/jaar/type, unique), <code>verlofaanvragen</code> (van/tot/uren/status/reden, aangevraagd-/beoordelaar-door FK) en <code>ziekmeldingen</code> (ziek_van/hersteld_op/percentage). <code>Verlofoverzicht::voor()</code> leidt per type het recht, het <b>opgenomen</b> (som goedgekeurde aanvragen in het jaar) en het saldo af. Modellen <code>Verlofaanvraag</code> (<code>beoordeelbaarVoor()</code> — HR/Beheer altijd; Manager alleen eigen team, dus nooit de eigen aanvraag → HR is terugval; alleen bij status aangevraagd), <code>Ziekmelding</code> (<code>isOpen()</code>/<code>dagen()</code>), <code>Verlofsaldo</code>; relaties op <code>Medewerker</code>. Controllers <code>Hr\VerlofController</code> (index/mijn/create/store/intrekken/beoordelen), <code>Hr\ZiekmeldingController</code> (index/store/herstel — zet medewerkerstatus op ziek/actief) en <code>Hr\VerlofsaldoController</code> (recht bijwerken). <b>Self-service</b> (<code>verlof.mijn/create/store/intrekken</code>) staat in de auth-groep <b>zonder</b> rolbeperking; de controller vereist een gekoppeld <code>medewerker</code>-record (<code>eigenMedewerker()</code> → 403). Overzicht/beoordelen/verzuim in <code>rol:hrmedewerker,manager,beheerder</code> (team gescoped via <code>whereHas('medewerker', zichtbaarVoor)</code>). Beoordelen/ziekmelding gelogd. Views <code>hr/{verlof-index,verlof-mijn,verlof-form,verzuim-index}</code> + panelen Verlof/Verzuim op de medewerkerkaart; dashboard toont openstaande aanvragen. Sidebar: Verlof/Verzuim + zelfservice ‘Mijn verlof’. Synthetische seed + guarded datamigratie. 8 tests (<code>HrVerlofTest</code>); 418 groen.</p>

  <p><b>Gesprekken &amp; performance (HR Fase C).</b> Enums <code>Gesprekstype</code> (beoordeling/functionering/exit) en <code>Gespreksstatus</code> (gepland/gehouden/afgerond). Tabellen <code>gesprekken</code> (medewerker/type/datum/gespreksvoerder/status/samenvatting/feedback), <code>gespreksdoelen</code> (KPI's; status open/behaald/niet_behaald) en <code>competentiescores</code> (competentie + score onvoldoende..uitstekend + toelichting). Modellen <code>Gesprek</code> (<code>beheerbaarVoor()</code> = <code>magHrInzien</code> + <code>medewerker->zichtbaarVoor</code>, dus Manager = eigen team), <code>Gespreksdoel</code>, <code>Competentiescore</code>; relatie op <code>Medewerker</code>. <code>Hr\GesprekController</code>: index (gescoped), create/store (genest onder medewerker), show (detail + inline bewerken), update, destroy, en de detail-endpoints doelStore/doelDestroy/competentieStore/competentieDestroy. Routes in <code>rol:hrmedewerker,manager,beheerder</code>. Mutaties gelogd (<code>veld: gesprek</code>). Views <code>hr/{gesprek-form,gesprek-show,gesprekken-index}</code> + gesprekspaneel op de medewerkerkaart; het dashboard toont de aankomende geplande gesprekken. Sidebar-item Gesprekken. Synthetische seed (functioneringsgesprek gepland + afgerond beoordelingsgesprek met doel/competentie) + guarded datamigratie. 6 tests (<code>HrGesprekTest</code>); 424 groen.</p>

  <p><b>Organisatiestructuur &amp; rapportages (HR Fase D).</b> Geen nieuwe tabellen — de afdelingsboom (<code>afdelingen.bovenliggende_afdeling_id</code> + <code>manager_id</code>) en functies bestonden al (Fase A). Aggregatieklasse <code>App\Support\HrRapport</code> — alle methodes nemen een optionele <code>?array $ids</code> (null = geen beperking): <code>kerncijfers()</code> (medewerkers, actief, FTE-totaal en -gemiddeld, ziek, <b>actueel verzuimpercentage</b> = aandeel met open ziekmelding, ziektedagen dit jaar), <code>perAfdeling()</code> (aantal/FTE/ziek/verzuim% per afdeling) en <code>rijen()</code> (per medewerker, voor CSV). Controller <code>Hr\HrRapportController</code>: <code>rapport</code> (view <code>hr.rapport</code>, tegels + chart-partials + per-afdeling-tabel), <code>export</code> (CSV met BOM, gelogd als INZAGE veld <code>hr_rapport_export</code>) en <code>organisatie</code> (view <code>hr.organisatie</code> — afdelingenboom recursief via partial <code>hr.partials.afdelingrij</code>, met <code>withCount</code> op de actieve medewerkers). Scope uit <code>isHrTeamBeperkt() ? zichtbaarVoor()->pluck('id') : null</code>. Routes <code>hr.rapport</code>/<code>.rapport.export</code>/<code>hr.organisatie</code> in de inzagegroep <code>rol:hrmedewerker,manager,beheerder,bestuur</code>. Sidebar: Organisatie + Rapportage. Seed uitgebreid met een sub-afdeling <b>PABO-team</b> onder Onderwijs (teamleden verplaatst) + guarded datamigratie. 6 tests (<code>HrRapportTest</code>); 430 groen.</p>

  <p><b>Onboarding/offboarding (HR Fase E).</b> Enum <code>ChecklistSoort</code> (onboarding/offboarding) met een <code>sjabloon()</code> (standaard taaklijst per soort). Tabel <code>hr_checklisttaken</code> (medewerker, soort, titel, verantwoordelijke, volgorde, gereed + gereed_op/gereed_door). Model <code>HrChecklisttaak</code>; relatie <code>Medewerker::checklisttaken()</code>. Controller <code>Hr\ChecklistController</code>: <code>start</code> (maakt de sjabloontaken aan, idempotent — niet als de checklist al bestaat), <code>store</code> (losse taak), <code>toggle</code> (afvinken/heropenen, zet gereed_op/gereed_door), <code>destroy</code>. Autorisatie via <code>guard()</code> = <code>magHrInzien</code> + <code>medewerker->zichtbaarVoor</code> (Manager = eigen team). Routes in <code>rol:hrmedewerker,manager,beheerder</code>. Twee checklistpanelen (onboarding/offboarding) met voortgang op de medewerkerkaart; starten gelogd (<code>veld: checklist</code>). Synthetische seed (demo-onboarding voor Johan Bakker) + guarded datamigratie. 5 tests (<code>HrChecklistTest</code>); 435 groen.</p>
  <p><b>Self-service "Mijn HR" &amp; iCal-agenda (HR Fase F).</b> Geen nieuwe tabellen. Nieuwe pagina <code>hr.mijn</code> (<code>Hr\MijnHrController@index</code>, view <code>hr.mijn</code>): het eigen 360°-dossier voor elke gekoppelde medewerker (gegevens/dienstverband, verlofsaldo via <code>Verlofoverzicht</code>, verlofaanvragen, gesprekken, documenten, checklists) — alleen-lezen. <b>Autorisatie</b> = koppeling <code>medewerkers.user_id</code> (geen aparte rol); <code>eigenMedewerker()</code> → 403 zonder dossier. <b>iCal-export</b> <code>hr.mijn.agenda</code> (<code>.ics</code>): <code>App\Support\Icsagenda::voor()</code> bouwt een VCALENDAR met de geplande gesprekken en het goedgekeurde verlof als all-day VEVENT's (DTEND exclusief; RFC 5545-escaping) — bewust een <b>zelfstandig bestand</b> (geen live Outlook/Teams-koppeling; intranet-only). <b>Eigen documentdownload</b> <code>hr.mijn.document</code> met eigendomscheck (<code>document->medewerker_id === eigen id</code>, anders 403) + INZAGE-log. Routes in de bestaande self-service-groep (auth, geen rolbeperking). Sidebar: Zelfservice-groep <b>Mijn HR</b> + <b>Mijn verlof</b>, toegevoegd aan elk menu wanneer de gebruiker een medewerkerrecord heeft (ook buiten de HR-module). HR-dashboard uitgebreid met een paneel <b>actuele ziekmeldingen</b> en een Mijn HR-snelkoppeling. 5 tests (<code>HrMijnTest</code>).</p>
  <p><b>Organisatiestructuur-beheer door HR (opdrachtgever).</b> De HR-referentiedata (afdelingen/teams en functies) is voorheen alleen door de Beheerder via Opzoektabellen te muteren; nu beheert de HR-medewerker (<code>magHrBeheer</code>) deze variabelen rechtstreeks op de pagina <code>hr.organisatie</code>. Nieuwe controller <code>Hr\OrganisatiebeheerController</code> met <code>afdelingStore/Update/Destroy</code> en <code>functieStore/Update/Destroy</code>; validatie spiegelt <code>ReferentieController</code> (code uniek per tabel via <code>Rule::unique()->ignore()</code>, functie-categorie ∈ <code>Functie::CATEGORIEEN</code>). <b>Vergrendeling bij verwijderen:</b> een afdeling met medewerkers of onderliggende teams en een functie met medewerkers geven 422; een afdeling kan niet haar eigen bovenliggende zijn. Alle mutaties gelogd (<code>AANMAAK/WIJZIGING/VERWIJDERING</code>, veld <code>afdeling</code>/<code>functie</code>). Routes in de HR-beheergroep <code>rol:hrmedewerker,beheerder</code>. De view toont onder de afdelingenboom twee beheerblokken met een toevoegformulier en <b>inline-bewerkbare rijen</b> (HTML5 <code>form</code>-attribuut, zodat de rij-formulieren geldig binnen de tabel blijven); alleen zichtbaar bij <code>magHrBeheer</code> — het Schoolbestuur ziet de pagina alleen-lezen. 8 tests (<code>HrOrganisatiebeheerTest</code>).</p>
  <p><b>Slimme functies (HR Fase G).</b> Geen nieuwe tabellen. (1) <b>Globaal zoeken</b> <code>hr.zoeken</code> (<code>Hr\ZoekController</code>, view <code>hr.zoeken</code>): zoekt bij ≥ 2 tekens over medewerkers (<code>Medewerker::zichtbaarVoor</code>, op voornaam/achternaam/personeelsnummer/e-mail) en — voor niet team-beperkte gebruikers — afdelingen (naam/code, met <code>withCount</code> actieve medewerkers). (2) <b>Signaleringen</b> <code>hr.signaleringen</code> (<code>Hr\SignaleringController</code>, view <code>hr.signaleringen</code>): bundelt de aflopende contracten (<code>dienstverbanden.einddatum</code> ≤ <code>sis.hr.contract_signaal_dagen</code>) en de verzuimsignalering. (3) <b>Verzuimsignalering</b> <code>App\Support\Verzuimsignalering</code>: <code>langdurig()</code> leidt per open ziekmelding de <b>Wet Verbetering Poortwachter</b>-mijlpalen af uit <code>ziek_van</code> (config <code>sis.hr.poortwachter.mijlpalen</code>: probleemanalyse wk 6, plan van aanpak wk 8, UWV-ziekmelding wk 42, eerstejaarsevaluatie wk 52, WIA-aanvraag wk 93), met per mijlpaal status <code>verstreken</code>/<code>binnenkort</code> (binnen <code>venster_dagen</code>, default 14)/<code>gepland</code>; <code>frequent()</code> signaleert medewerkers met ≥ <code>drempel</code> (default 3) losse ziekmeldingen binnen <code>maanden</code> (default 12). Het systeem houdt <b>geen</b> afgehandelde status per mijlpaal bij (informatief; formele re-integratie via bedrijfsarts). Routes in de inzagegroep <code>rol:hrmedewerker,beheerder,bestuur</code>; scope <code>isHrTeamBeperkt() ? …pluck('id') : null</code>. Sidebar: menu-items Zoeken + Signaleringen (nieuwe icoonsleutels <code>search</code>/<code>alert</code>); HR-dashboard kreeg een knop naar Signaleringen. Synthetische seed: Mehmet (P260004) drie herstelde ziekmeldingen (frequent verzuim); geen migratie nodig. 8 tests (<code>HrSlimmeFunctiesTest</code>). <b>Bewust buiten scope:</b> live Teams/Outlook-integratie, e-mail (externe provider; intranet-only) en NL/EN-i18n. <b>Module HR / Personeelszaken afgerond.</b></p>
  <p><b>Interne notities per medewerker (contactmomenten).</b> Hetzelfde patroon als de student-notities. Tabel <code>medewerker_notities</code> (<code>medewerker_id</code> cascade, <code>gebruiker_id</code> nullOnDelete, <code>tekst</code>, timestamps, index <code>[medewerker_id, created_at]</code>) + model <code>MedewerkerNotitie</code>; relatie <code>Medewerker::notities()</code> (<code>latest()</code>). <code>Hr\MedewerkerController::notitieStore/notitieDestroy</code> (autorisatie via <code>medewerker->beheerbaarVoor()</code> = <code>magHrBeheer</code>; destroy checkt eigenaarschap → 404); <code>show()</code> eager-loadt <code>notities.gebruiker</code>. Routes <code>medewerkers.notities.store/destroy</code> in de HR-beheergroep <code>rol:hrmedewerker,beheerder</code>. Notitieblok onderaan <code>hr/medewerker-show</code> (hergebruik van de <code>iuasr-dash-note*</code>-klassen): toevoegformulier met datumkop + lijst met datum/tijd + auteur + verwijderknop, alleen bij <code>magHrBeheer</code> — Bestuur leest mee. <b>Werkinformatie, niet audit-gelogd</b> (net als de student- en relatie-notities); geen BSN. Synthetische seed (twee notities bij Sophie Willemsen). 5 tests (<code>HrNotitieTest</code>).</p>
  <p><b>Rapportage "Verzuim &amp; verlof per medewerker".</b> Uitbreiding van de HR-rapportage (opdrachtgever: per medewerker alle verzuim en verlof kunnen volgen). Nieuwe aggregatie <code>HrRapport::perMedewerker(?array $ids, ?int $jaar)</code>: per medewerker het aantal ziekmeldingen, de ziektedagen (som <code>Ziekmelding::dagen()</code> over meldingen met <code>whereYear('ziek_van')</code>), het <b>verzuimpercentage</b> (ziektedagen ÷ <code>verstrekenDagenInJaar()</code>, kalenderdag-gebaseerd) en het verlof — recht (som <code>verlofsaldi</code>), opgenomen (som goedgekeurde <code>verlofaanvragen</code> in het jaar), saldo en het aantal openstaande aanvragen. Alle grootheden in <b>geaggregeerde group-by-queries</b> (geen N+1); status als enum. Controller <code>Hr\HrRapportController::verzuimVerlof</code> (view <code>hr.verzuimverlof</code>) + <code>verzuimVerlofExport</code> (CSV met BOM, gelogd als INZAGE veld <code>hr_verzuim_verlof_export</code>); helper <code>verzuimScope()</code> combineert de team-scope met een optioneel <code>afdeling</code>-filter, plus een <code>jaar</code>-keuze (huidig jaar t/m 3 terug). View: KPI-tegels + tabel met gegroepeerde kolomkoppen (Verzuim | Verlof), rij-link naar de medewerkerkaart (<code>#verzuim</code>), negatief saldo rood. Routes <code>hr.verzuimverlof</code>(<code>.export</code>) in de inzagegroep <code>rol:hrmedewerker,beheerder,bestuur</code>; sidebar-item <b>Verzuim &amp; verlof</b> + knop op de rapportagepagina. Geen nieuwe tabellen. 7 tests (<code>HrVerzuimVerlofRapportTest</code>).</p>

  <h2>0c. Bestuurspagina &amp; systeembeheer-snelkoppelingen</h2>
  <p><b>Globale bestuurspagina.</b> Route <code>/bestuur</code> (<code>bestuur</code>, middleware <code>rol:bestuur,beheerder</code>), <code>BestuurController@index</code> → view <code>bestuur.index</code> (in de app-shell). Instellingsbreed, alleen-lezen; hergebruikt de bestaande <code>App\Support\Statistiek</code>-aggregaties (kern, perOpleiding, statusVerdeling, instroom, slaagpercentage, presentie(+Verdeling/PerOpleiding), financieel) plus cursuscijfers (<code>Cursus</code>/<code>Cursist</code>/<code>Cursusinschrijving</code>). Rendering met de chart-partials <code>partials.charts.bar|spark|donut</code> en de dashboardkaarten (<code>sis-chartgrid</code>/<code>sis-chart-card</code>, <code>iuasr-dash-stat</code>). Bereikbaar via een tegel op de modulekiezer en een menu-item in de sidebar (Bestuur + Beheerder).</p>
  <p><b>Herontwerp — één samengevoegd overzicht met alle modules (opdrachtgever).</b> Het Schoolbestuur had in de sidebar twee Overzicht-links (<code>bestuur</code> + <code>dashboard</code>); die zijn samengevoegd tot <b>één</b> pagina (<code>bestuur</code>). De sidebar-tak <code>Rol::Bestuur</code> heeft nog één link (<b>Bestuursoverzicht</b>); <code>DashboardController@index</code> redirect het Bestuur na login naar <code>route('bestuur')</code> (de <code>match($rol)</code>-arm voor Bestuur is daarmee dode code maar blijft staan). <code>BestuurController</code> verzamelt nu de statistieken van <b>alle</b> modules via hun eigen aggregatieklassen: Studentenzaken (<code>Statistiek</code>), Cursussen (<code>Cursus</code> + <code>Cursusrapport::financieelTotaal</code>), Relatiebeheer &amp; Stage (<code>Relatierapport::kerncijfers/stagesPerStatus/organisatiesPerType/evaluatie</code>, scope null = instellingsbreed) en HR (<code>HrRapport::kerncijfers/perAfdeling</code>, scope null). De view is geordend in vijf <b>rubrieken met hoofdlijnen</b> (A Studenten &amp; onderwijs, B Financiën, C Cursussen, D Relatiebeheer &amp; stage, E HR / Personeelszaken) — volledige scheidingslijn (<code>border-top</code>) + titel + toelichting per rubriek. <b>Financiën is expliciet tweeledig:</b> collegegeld (opleidingen, <code>Statistiek::financieel</code>) én cursusgelden (cursussen, <code>Cursusrapport::financieelTotaal</code>) apart, plus een gecombineerd totaal (verschuldigd/betaald/openstaand/betaalgraad in de controller opgeteld). 10 tests (<code>BestuurPaginaTest</code>).</p>
  <p><b>Bestuur houdt altijd het eigen menu (opdrachtgever).</b> Probleem: opende het Bestuur een modulerapport (bv. <code>hr.rapport</code>), dan schakelde de sidebar via <code>$inHrmodule</code> naar het HR-module-menu, dat beheerlinks bevat (<code>verlof</code>/<code>verzuim</code>/<code>gesprekken</code> in <code>rol:hrmedewerker,beheerder</code>) — klikken daarop gaf een 403. Oplossing in <code>partials/sidebar</code>: voor <code>$rol === Rol::Bestuur->value</code> wordt <b>altijd</b> het Bestuur-menu (<code>$standaardMenu</code>) gekozen, ongeacht <code>$inCursusmodule</code>/<code>$inRelatiemodule</code>/<code>$inHrmodule</code>. Het Bestuur-menu kreeg een groep <b>Rapportages</b> met directe links naar de (alleen-lezen) rapporten die het Bestuur mag zien: Alumni (<code>rapporten.alumni</code>), Aanwezigheid (<code>presentieoverzicht</code>), Cursusrapportage (<code>cursussen.rapport</code>), Relatiebeheer (<code>relatiebeheer.dashboard</code>), HR-rapportage (<code>hr.rapport</code>) en HR verzuim &amp; verlof (<code>hr.verzuimverlof</code>) — alle routegroepen bevatten <code>bestuur</code>. Zo verschijnt er nooit een module-menu met verboden links en blijft het Bestuur in de eigen context; geen route-/rechtenwijziging nodig (alle routes blijven bereikbaar, alleen de sidebar verandert). Voor de HR-medewerker/Beheerder blijft het module-menu ongewijzigd. 3 tests toegevoegd aan <code>BestuurPaginaTest</code> (menu bevat rapportagelinks; Bestuur houdt eigen menu op <code>hr.rapport</code>; HR-medewerker ziet wél het module-menu).</p>
  <p><b>Rolsamenvoeging HR-medewerker + Manager (opdrachtgever).</b> Bij IUASR zijn de HR-medewerker en de leidinggevende (Manager) dezelfde persoon; de twee rollen zijn samengevoegd tot <b>één</b> rol <code>Rol::Hrmedewerker</code>. De enum-case <code>Manager</code> is verwijderd, alle exhaustive <code>match</code>-armen zonder <code>default</code> zijn bijgewerkt (label, magCijfersInzien, magInschrijvingBeheren, magPresentieInzien, magAanwezigheidsregelingZien, moduleSleutels), evenals <code>magHrInzien</code> (nu Hrmedewerker/Beheerder/Bestuur), <code>isHrTeamBeperkt()</code> (nu altijd <code>false</code> — geen team-scoping meer; het mechanisme <code>Medewerker::scopeZichtbaarVoor</code> blijft aanwezig voor eventuele herintroductie) en <code>magVerlofBeoordelen()</code> (Hrmedewerker/Beheerder). <code>Verlofaanvraag::beoordeelbaarVoor()</code> vereenvoudigd tot <code>status===Aangevraagd &amp;&amp; magVerlofBeoordelen()</code>; <code>GesprekController::gespreksvoerders()</code> zonder Manager; alle HR-routemiddleware van <code>rol:hrmedewerker,manager,…</code> naar <code>rol:hrmedewerker,…</code>; sidebar-fallback zonder Manager. Datamigratie <code>merge_manager_in_hrmedewerker</code>: <code>UPDATE users SET rol='hrmedewerker' WHERE rol='manager'</code> gevolgd door <code>ALTER … MODIFY rol ENUM(Rol::waarden())</code> (zonder 'manager'); op een verse test-DB een no-op. In de <code>HrSeeder</code> is Ruben Smit nu <code>Hrmedewerker</code> (blijft leidinggevende in de organisatiestructuur). De HR-tests die team-scoping toetsten zijn omgezet naar "de gecombineerde rol ziet iedereen".</p>
  <p><b>Systeembeheer op de modulekiezer.</b> <code>resources/views/modules/index.blade.php</code> toont voor <code>rol=beheerder</code> een blok met directe links naar <code>gebruikers</code>, <code>opzoektabellen</code>, <code>audit-log</code>, <code>backup</code> en <code>handleiding.technisch</code> (voorheen alleen via de Studentenzaken-sidebar). De routes zelf blijven in de <code>rol:beheerder</code>-groep; dit zijn uitsluitend snelkoppelingen op de hoofdpagina.</p>

  <h2>1. Architectuur &amp; stack</h2>
  <ul>
    <li><b>Applicatie:</b> PHP + Laravel (server-gerenderd; geen kale PHP/WordPress).</li>
    <li><b>Database:</b> MySQL/MariaDB (InnoDB, echte foreign keys, surrogaatsleutels).</li>
    <li><b>Authenticatie:</b> Microsoft Entra ID (SSO/OIDC) — nooit een eigen login bouwen. In de ontwikkelomgeving een tijdelijke dev-login.</li>
    <li><b>Netwerk:</b> draait intern (intranet), IP-beperkt, gescheiden van het publieke aanmeldportaal.</li>
    <li><b>Gevoelige data:</b> BSN en rekeningnummer versleuteld (Laravel-encryptie met <b>APP_KEY</b>); inzage/mutatie gelogd (audit-log).</li>
  </ul>

  <h2>2. Omgeving (referentie)</h2>
  <table class="kv">
    <tr><td class="k">PHP</td><td><code>~/php/8.3/php.exe</code></td></tr>
    <tr><td class="k">Composer</td><td><code>~/bin/composer.phar</code></td></tr>
    <tr><td class="k">Database-server</td><td>MariaDB (portable) — <code>~/mariadb/mariadb-11.4.9-winx64/bin/</code></td></tr>
    <tr><td class="k">DB-host / poort</td><td><code>127.0.0.1</code> : <code>3307</code></td></tr>
    <tr><td class="k">Database / gebruiker</td><td><code>iuasr_sis</code> / <code>iuasr_sis</code></td></tr>
    <tr><td class="k">Configuratie</td><td><code>.env</code> (in de projectmap) — bevat DB-gegevens en <b>APP_KEY</b></td></tr>
  </table>
  <div class="let"><b>APP_KEY is kritiek.</b> Zonder de originele APP_KEY zijn de versleutelde velden (BSN, rekeningnummer) onherstelbaar. De sleutel zit in <code>.env</code> en wordt meegenomen in de back-up.</div>

  <h3>E-mail (resultaten mailen)</h3>
  <p>De examencommissie kan definitieve resultaten per e-mail naar studenten sturen. In <b>ontwikkeling</b> staat <code>MAIL_MAILER=log</code>: e-mails worden naar <code>storage/logs/laravel.log</code> geschreven, er gaan GEEN echte e-mails uit (AVG, synthetische data). In <b>productie</b> configureert u de IUASR-mailserver in <code>.env</code>:</p>
  <span class="cmd">MAIL_MAILER=smtp
MAIL_HOST=&lt;smtp.iuasr.nl&gt;
MAIL_PORT=587
MAIL_USERNAME=&lt;gebruiker&gt;
MAIL_PASSWORD=&lt;wachtwoord&gt;
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=noreply@iuasr.nl
MAIL_FROM_NAME="IUASR Studentenzaken"</span>
  <p>Elke student ontvangt individueel de eigen (ondertekende) cijferlijst als bijlage; verzending wordt gelogd. Overweeg voor grote aantallen een queue (<code>QUEUE_CONNECTION</code> + worker).</p>

  <h2>3. Back-up maken</h2>
  <p>Een volledige back-up wordt gemaakt via de webapplicatie:</p>
  <ol>
    <li>Log in als <b>Beheerder</b>.</li>
    <li>Ga naar <b>Beheer → Back-up &amp; herstel</b>.</li>
    <li>Geef een sterk <b>wachtwoord</b> op (minimaal 8 tekens) en bevestig.</li>
    <li>Klik op <b>Back-up genereren &amp; downloaden</b>. U ontvangt een met AES-256 versleutelde ZIP.</li>
  </ol>
  <p>De ZIP bevat: <code>database.sql</code> (volledige dump), de applicatiebroncode en webpagina's, <code>.env</code> (incl. APP_KEY) en de geüploade bestanden (<code>storage/app</code>). Niet inbegrepen: <code>vendor/</code>, <code>.git/</code> en de referentiemap <code>IUASR/</code>. Het wachtwoord wordt <b>nergens opgeslagen</b>; downloaden wordt ge-audit-logd.</p>
  <div class="tip">Advies: bewaar back-ups versleuteld op een beveiligde, interne locatie en hanteer een bewaarschema (bijv. wekelijks + vóór elke update). Overweeg een periodieke, geautomatiseerde back-up naar een netwerkschijf.</div>

  <h2>4. Herstelprocedure (recovery)</h2>
  <p>Terugzetten is een bewuste beheerhandeling en gebeurt <b>niet</b> vanuit de draaiende applicatie (die kan zichzelf niet veilig overschrijven en een database-restore wist bestaande data). Voer de stappen uit op de server.</p>

  <h3>Stap 1 — Archief uitpakken</h3>
  <p>De Windows Verkenner kan een AES-versleutelde ZIP <b>niet</b> openen. Gebruik het meegeleverde commando (of 7-Zip/WinRAR):</p>
  <span class="cmd">~/php/8.3/php.exe artisan backup:uitpakken "pad/naar/iuasr-sis-backup-JJJJMMDD-UUMM.zip" --doel="pad/naar/hersteld"</span>
  <p>U wordt om het wachtwoord gevraagd (of geef <code>--wachtwoord=...</code>). Het commando verifieert het wachtwoord en pakt uit naar de doelmap.</p>

  <h3>Stap 2 — Bestanden plaatsen</h3>
  <p>Plaats de uitgepakte bestanden in de webroot/projectmap van de (interne) server. Zet ook <code>storage/app</code> (geüploade documenten) terug.</p>

  <h3>Stap 3 — Afhankelijkheden herstellen</h3>
  <span class="cmd">~/bin/composer.phar install --no-dev --optimize-autoloader</span>

  <h3>Stap 4 — Database terugzetten</h3>
  <p>Maak (indien nodig) een lege database en importeer de dump. De dump bevat zowel het schema als de data (DROP/CREATE/INSERT):</p>
  <span class="cmd">~/mariadb/mariadb-11.4.9-winx64/bin/mariadb.exe -h 127.0.0.1 -P 3307 -u iuasr_sis -p iuasr_sis &lt; database.sql</span>
  <div class="let">Let op: dit <b>overschrijft</b> de bestaande gegevens in de database <code>iuasr_sis</code>. Maak eerst een verse back-up van de huidige stand als die nog waarde heeft.</div>

  <h3>Stap 5 — Configuratie controleren</h3>
  <ul>
    <li>Controleer <code>.env</code>: <code>DB_*</code>-gegevens en <code>APP_URL</code>.</li>
    <li><b>Laat <code>APP_KEY</code> ongewijzigd</b> (gelijk aan de back-up), anders zijn BSN/rekeningnummer niet te ontsleutelen.</li>
  </ul>

  <h3>Stap 6 — Cache legen &amp; controleren</h3>
  <span class="cmd">~/php/8.3/php.exe artisan optimize:clear</span>
  <p>Een <code>php artisan migrate</code> is <b>niet</b> nodig: de dump bevat het volledige schema. Controleer tot slot of de applicatie start en of inloggen werkt.</p>

  <h2>5. Losse database-restore (zonder volledige recovery)</h2>
  <p>Alleen de gegevens terugzetten (code ongewijzigd)? Pak het archief uit (stap 1) en voer alleen stap 4 uit met <code>database.sql</code>.</p>

  <h2>6. AVG &amp; beveiliging</h2>
  <ul>
    <li>Back-ups bevatten alle persoonsgegevens én de encryptiesleutel — uitsluitend versleuteld en intern bewaren; niet e-mailen of naar buiten brengen.</li>
    <li>Echte productiedata alleen in de laatste fase, onder toezicht van de Functionaris Gegevensbescherming.</li>
    <li>Inzage/mutatie van cijfers en BSN wordt gelogd (audit-log, alleen-lezen voor Beheer).</li>
    <li>Rolscheiding wordt server-side afgedwongen; wijzig dit niet zonder reden.</li>
    <li><b>Multi-rol (unie).</b> Een gebruiker heeft één <b>primaire</b> rol (<code>users.rol</code>) plus optioneel <b>extra</b> rollen (tabel <code>roltoewijzingen</code>, één regel per extra rol, uniek op <code>(user_id, rol)</code>). De rechten zijn de <b>unie</b> over alle rollen: <code>User::alleRollen()</code> levert de rolset, <code>User::magVolgensRol()</code> is waar zodra één rol de regel toestaat. De <code>Rol</code>-enum blijft de bron van waarheid per rol; álle <code>mag…()</code>-methoden op <code>User</code>, de <code>rol:</code>-middleware (<code>User::rolSleutels()</code>) en de Gates in <code>AutorisatieServiceProvider</code> gaan via die unie. De <b>scoping</b> volgt de ruimste rol: <code>isOpleidingBeperkt()</code>/<code>isCursusBeperkt()</code>/<code>isRelatieBeperkt()</code> geven alleen <code>true</code> als géén andere rol brede inzage geeft (bijv. <code>Rol::zietAlleOpleidingen()</code>). Het <b>startdashboard</b> en de sidebar-thuisbasis volgen de primaire rol; de sidebar voegt de menu's van álle rollen samen. Beheer beheert de rolset via <b>Gebruikers &amp; rollen</b> (primaire rol + aanvinkbare extra rollen); wijzigingen worden gelogd, en een <b>risicocombinatie</b> (Studentenzaken + een cijferrol) geeft een waarschuwing.</li>
    <li><b>Gebruiker aanmaken.</b> <code>GebruikerController::store</code> (route <code>POST /gebruikers</code>, <code>rol:beheerder</code>) maakt een account met naam, e-mail, primaire rol, extra rollen en <code>actief</code>. Er wordt <b>geen wachtwoord</b> gezet: authenticatie loopt via Entra ID (of de dev-login in ontwikkeling); het account kan inloggen zodra het e-mailadres in Entra bestaat. Aanmaak wordt gelogd (<code>actie=aanmaak</code>, <code>veld=gebruiker</code>).</li>
    <li><b>Directie is opleidinggebonden.</b> De koppeltabel <code>directie_opleidingen</code> (user &harr; opleiding) bepaalt welke studenten, cijfers en rapporten een directielid ziet. Beheer wijst dit toe via <b>Gebruikers &amp; rollen &rarr; Directie — opleidingtoewijzing</b>. Zonder toewijzing ziet een directielid <b>niets</b> (need-to-know). Een dubbel ingeschreven student is zichtbaar voor de directie van elke opleiding waarin hij/zij actief is. De filtering loopt via <code>User::opleidingIds()</code>, <code>Student::scopeZichtbaarVoor()</code> en per-opleiding gefilterde statistieken.</li>
    <li><b>Onderwijsnieuws (bestuursdashboard).</b> Nieuws wordt op een <b>schema</b> opgehaald en lokaal opgeslagen; het dashboard leest alleen uit de tabellen <code>nieuwsbronnen</code>/<code>nieuwsberichten</code> (nooit live het internet op). Commando <code>nieuws:ophalen</code>, gepland op <b>dagelijks 23:00</b> (<code>routes/console.php</code>) — vereist dat er een <b>cron</b> draait die elke minuut <code>php artisan schedule:run</code> aanroept (of <code>php artisan schedule:work</code>). Uitgaand verkeer is beperkt tot de <b>whitelist</b> <code>config sis.nieuws.toegestane_hosts</code> (env <code>SIS_NIEUWS_HOSTS</code>); een bron met een host buiten de lijst wordt geweigerd. SSL-verificatie staat altijd aan; heeft de server geen CA-bundel in php.ini, zet dan <code>SIS_NIEUWS_CACERT</code> naar een <code>cacert.pem</code>. Bronnen zonder feed (bv. de Onderwijsinspectie, een JavaScript-app) staan op type <b>handmatig</b>: Beheer voegt items toe via <b>Beheer &rarr; Nieuwsbronnen</b> (daar ook 'Nu ophalen'). Ophalen vereist uitgaand internet — een bewuste, tot de whitelist beperkte, uitzondering op het intranet-only regime.</li>
    <li><b>Presentiegegevens zijn onderwijsinhoudelijk.</b> Studentenzaken, Financiële Administratie en Beheer hebben géén toegang tot presentielijsten of aanwezigheidspercentages (Gate <code>presentie-inzien</code>). Registreren mag alleen de docent van het eigen vak (Gate <code>presentie-registreren</code>). Inzage en mutatie worden gelogd.</li>
  </ul>

  <h2>7. Presentie (aanwezigheidsregistratie)</h2>
  <p>De docent registreert per college de aanwezigheid; dit is verplicht. Het model is bewust <b>genormaliseerd</b>: één regel per student &times; vak &times; onderwijsweek — nooit vaste weekkolommen op de inschrijving.</p>
  <table class="kv">
    <tr><td class="k">Tabel</td><td><code>presenties</code> (<code>inschrijving_id</code>, <code>vak_id</code>, <code>week</code>, <code>aanwezig</code>, <code>geregistreerd_door_id</code>) met unieke sleutel op (<code>inschrijving_id</code>, <code>vak_id</code>, <code>week</code>).</td></tr>
    <tr><td class="k">Regeling</td><td>Kolom <code>inschrijvingen.aanwezigheidsregeling_50</code> (boolean). Bewust op de <b>inschrijving</b>, niet op de student: zij geldt per opleiding en per studiejaar en moet bij herinschrijving opnieuw worden toegekend.</td></tr>
    <tr><td class="k">Normen</td><td><code>config/sis.php</code> &rarr; <code>presentie.weken_per_blok</code> (8), <code>presentie.norm</code> (<b>0.75</b> — studiegids §2.3.3; eerder 0.80) en <code>presentie.norm_regeling</code> (0.50). Alle drie env-overschrijfbaar (<code>SIS_PRESENTIE_NORM</code> e.a.). LET OP: sommige modules eisen "100% aanwezigheid, max 25% afwezig" (= ook 75%); een per-vak-norm is nog niet gemodelleerd.</td></tr>
    <tr><td class="k">Logica</td><td><code>App\Support\Presentiebewaking</code> — percentage, norm per student, volledigheid per week. <code>App\Support\Statistiek</code> levert de dashboard-aggregaties.</td></tr>
    <tr><td class="k">Signaal bij cijfers</td><td>De studiegids (§2.3.3) verbiedt deelname aan de toets onder de norm. De cijferinvoer (<code>CijferController::invoer</code>) toont per student een <b>Aanwezigheid</b>-kolom en een waarschuwing bij wie onder de norm zit — <b>niet blokkerend</b> (docent/examencommissie wegen het mee). Een harde blokkade/uitzonderingsregeling is een OER-keuze.</td></tr>
  </table>
  <div class="let"><b>Ontbrekende registratie is geen afwezigheid.</b> Het percentage wordt berekend over de <b>geregistreerde</b> weken. Een week zonder regel telt niet mee — anders zou nalatigheid van de docent op de student worden afgewenteld. Een week geldt pas als “geregistreerd” wanneer álle presentieplichtige deelnemers een waarde hebben.</div>
  <p>Vrijgestelde studenten (<code>vaktoewijzingen.vrijgesteld</code>) volgen het vak niet en worden bij het opslaan overgeslagen, óók als het formulier voor hen een waarde meestuurt. Wijzigt u <code>weken_per_blok</code>, dan blijven bestaande registraties met een hoger weeknummer in de database staan maar verdwijnen zij uit het scherm; ruim ze in dat geval expliciet op.</p>

  <div class="let"><b>EC-model (instelbaar per opleiding — TE BEVESTIGEN per OER).</b> Hoe leidt een voldoende tot de vak-EC? <code>opleidingen.ec_model</code> (nullable) met terugval op <code>config('sis.cijfers.ec_model')</code> (default <code>knockout</code>): <b>knockout</b> = élk meetellend toetsonderdeel moet ≥ cesuur zijn; <b>compensatorisch</b> = het <b>gewogen eindcijfer</b> over de meetellende onderdelen moet ≥ cesuur zijn (een onvoldoende onderdeel mag gecompenseerd worden). Logica in <code>App\Support\EcBerekening::bepaalEc(...,$model)</code>; het model komt uit <code>Cijferberekening::ecModel($vak)</code>. Beheer stelt het per opleiding in via <b>Opzoektabellen &rarr; Opleidingen &rarr; EC-model</b>. Achtergrond: de studiegids beschrijft per module een gewogen toetsformule (wijst op compensatie), maar de bindende regel staat in het OER; daarom data-gedreven en niet hardcoded. Cesuur idem: <code>opleidingen.voldoende_grens</code> met terugval 5,5. De <b>cijferschaal</b> is 1–10 (<code>SIS_CIJFER_MIN/MAX</code>); sommige studiegids-modules hanteren een 0–100-schaal met bonuspunten — dat wordt intern (nog) niet ondersteund en vergt een aparte OER-/ontwerpbeslissing.</div>

  <h2>8. Collegegeld: termijnen</h2>
  <p>Er is bewust <b>geen facturentabel</b>. Het termijnschema wordt volledig afgeleid uit het jaartarief, de betaalregeling en de inschrijvingsduur, zodat het nooit kan verouderen ten opzichte van de inschrijving (bijvoorbeeld na een gewijzigde uitschrijfdatum).</p>
  <table class="kv">
    <tr><td class="k">Schema</td><td><code>App\Support\Collegegeldtermijnen</code> — vervalmaanden 9, 11, 1, 3, 5; bedrag = jaarbedrag ÷ n, restje op de laatste termijn.</td></tr>
    <tr><td class="k">Vervaldatum</td><td>Factuurdag + betaaltermijn = de <b>24e</b> van de vervalmaand (factuur op de 14e, 10 dagen betaaltermijn). Instelbaar via <code>config/sis.php</code> (<code>sis.collegegeld.factuurdag</code> / <code>betaaltermijn_dagen</code>; env <code>SIS_COLLEGEGELD_FACTUURDAG</code> / <code>SIS_COLLEGEGELD_BETAALTERMIJN_DAGEN</code>).</td></tr>
    <tr><td class="k">Regeling</td><td><code>inschrijvingen.betaalregeling</code>: <code>termijnen</code> (5 facturen) of <code>volledig</code> (1 factuur, vervalt de 24e van september).</td></tr>
    <tr><td class="k">Betaling &rarr; termijn</td><td><code>betalingen.termijn</code> (1..5, nullable). Leeg = automatisch toerekenen aan de oudste openstaande termijn (FIFO).</td></tr>
    <tr><td class="k">Achterstand</td><td>Som van het openstaande deel van de termijnen waarvan de <b>vervaldatum verstreken</b> is. Dit stuurt de blokkades op herinschrijven en verklaringen.</td></tr>
  </table>
  <div class="let"><b>Per opleiding (beleid 2026-07-10).</b> Collegegeld hangt aan de INSCHRIJVING, niet aan het studiejaar. Elke inschrijving heeft een eigen termijnschema en eigen betalingen; <code>Collegegeldstatus::voor()</code> telt alle inschrijvingen op. Korting staat op <code>inschrijvingen.korting_percentage</code> (+ verplichte <code>korting_reden</code>); <code>Collegegeldstatus::jaarbedrag()</code> geeft het tarief ná korting en is de basis voor het schema. Bij 100% korting levert <code>Collegegeldtermijnen::voor()</code> een lege collectie. Betalingen worden nooit tussen opleidingen verrekend. Een achterstand bij één inschrijving zet <code>achterstand</code> op true en blokkeert herinschrijven en verklaringen.</div>
  <div class="let"><b>Schuld en blokkade zijn twee dingen.</b> <code>Collegegeldstatus::voor()</code> geeft <code>achterstand</code> (er is een onbetaalde vervallen termijn) én <code>geblokkeerd</code> (<code>achterstand</code> zonder lopende betalingsafspraak). Blokkeer altijd op <code>geblokkeerd</code> / <code>isGeblokkeerd()</code>, nooit op <code>achterstand</code> — dat laatste beschrijft alleen de schuld en blijft true tijdens een afspraak. Tabel <code>betalingsafspraken</code> (<code>geldig_tot</code>, <code>reden</code>, <code>vastgelegd_door_id</code>, <code>ingetrokken_op</code>). 'Lopend' is afgeleid (<code>Betalingsafspraak::isLopend()</code>), nooit een opgeslagen status: een verlopen of ingetrokken afspraak kan zo niet blijven doorwerken. Vastleggen/intrekken alleen door rollen <code>financien</code> en <code>beheerder</code>; beide gelogd (<code>veld: betalingsafspraak</code>).</div>
  <div class="let"><b>Betalingen zijn muteerbaar.</b> <code>BetalingController::bijwerken()</code> en <code>::verwijderen()</code> (rollen financien + beheerder) schrijven de oude en nieuwe waarden naar de audit-log (<code>veld: betaling</code>). Verwijder deze logging niet: zij is het enige bewijsspoor van mutaties op geldbedragen.</div>
  <div class="let"><b>Synthetische studenten opschonen.</b> Artisan-commando <code>php artisan sis:studenten-verwijderen {nummers*} {--force}</code> verwijdert studenten op studentnummer (los of als reeks, bijv. <code>261015-261026</code>). Zonder <code>--force</code> toont het alleen een voorbeeld (dry-run); met <code>--force</code> verwijdert het definitief, in een transactie en per student gelogd (<code>AuditLogger::VERWIJDERING</code>, veld <code>student</code>). Alle gekoppelde gegevens verdwijnen via de database-constraints: inschrijvingen, betalingen, resultaten, presenties, vaktoewijzingen, notities, documenten, vrijstellingsbesluiten, betalingsafspraken en kennistoetsresultaten staan op <code>ON DELETE CASCADE</code>; <b>taken</b> en <b>ondertekende documenten</b> op <code>SET NULL</code> (die blijven bestaan, alleen de koppeling vervalt). NB: de studententabel heet <code>studenten</code> (niet <code>students</code>). Uitsluitend bedoeld voor het opschonen van synthetische testdata.</div>
  <div class="let"><b>Jaarovergang (actief studiejaar).</b> Het systeem is periode-geparametriseerd: precies één <code>perioden</code>-rij heeft <code>actief = true</code>, afgedwongen door het <code>Periode::saved</code>-event (activeren van één jaar deactiveert de rest). Alle runtime-logica leidt het jaar af uit de <b>periode van de inschrijving</b> of uit <code>now()</code> — nergens staat een studiejaar hardcoded in een berekening. Termijndata (<code>Collegegeldtermijnen</code>) komen uit <code>periode.startdatum</code>; het tarief uit <code>collegegeldtarieven</code> op <code>periode_id</code> (opleiding-specifiek vóór een eventueel <code>opleiding_id = null</code> standaardtarief van dezelfde periode). De jaarovergang naar 2026-2027 op de draaiende DB is gezet met de guarded datamigratie <code>activeer_studiejaar_2026_2027</code> (raw update — een migratie vuurt geen Eloquent-event; daarom expliciet alle jaren op inactief en daarna 2026-2027 op actief). Op een verse migratie draait die vóór de seeders (lege <code>perioden</code>) en doet niets, zodat de <code>ReferentieSeeder</code>-basislijn (2025-2026 actief) en de tests ongewijzigd blijven. Beheer stuurt verdere overgangen via Opzoektabellen → Studiejaren (<code>ReferentieController</code>, checkbox <code>actief</code>). Let op: <code>RapportController::actieveStudentenExport</code> filtert op <code>status = actief</code> over ALLE perioden, niet op de actieve periode — bewust, zodat na de overgang zowel herinschreven als nog-niet-herinschreven actieve studenten meekomen.</div>
  <div class="let"><b>Let op de betekenis van de velden</b> in <code>Collegegeldstatus::voor()</code>: <code>verschuldigd</code> is het totaal van de niet-vervallen termijnen (bij een lopende inschrijving dus het volle jaarbedrag), <code>openstaand</code> is verschuldigd − betaald (inclusief termijnen die nog moeten vervallen), en <code>achterstallig</code> is het direct opeisbare bedrag. Alleen <code>achterstallig</code> bepaalt <code>achterstand</code>.</div>
  <p>De kolom <code>inschrijvingen.betaalwijze</code> is <b>vervallen</b> (zij mengde regeling en betaalwijze) en blijft alleen voor de historie bestaan. De betaalwijze hoort bij een betaling, niet bij de inschrijving.</p>
  <p>Bij een beëindigde inschrijving wordt het totaal herrekend naar het pro rata bedrag; termijnen met een vervaldatum ná het einde worden <code>vervallen</code> en de laatste geldende termijn vangt het verschil op. De CSV-import herkent kolommen op <b>naam</b> uit de kopregel, met terugval op de klassieke volgorde (<code>studentnummer;bedrag;datum;betaalwijze;opmerking</code>) voor oudere bestanden.</p>

  <h3>Afstuderen &amp; alumni</h3>
  <p>Afstuderen is een <b>terminale eindstatus</b> per inschrijving (<code>InschrijvingStatus::Afgestudeerd</code>), gezet via <b>Acties &rarr; Afgestudeerd markeren</b> (Studentenzaken); de <code>afstudeerdatum</code> wordt vastgelegd. <b>Alumnus</b> is afgeleid (geen kolom): <code>Student::isAlumnus()</code> = heeft minstens één afgestudeerde inschrijving. Een afgestudeerde inschrijving is <b>bevroren</b>: korting, betaalregeling, aanwezigheidsregeling en vaktoewijzing worden server-side geweigerd (<code>Inschrijving::isAfgestudeerd()</code>), en herinschrijven voor <b>dezelfde</b> opleiding wordt geblokkeerd. Het studentnummer blijft behouden; een andere opleiding kan als nieuwe inschrijving. Afstuderen kan alleen in het <b>laatste leerjaar</b> (<code>leerjaar === opleidingen.nominale_jaren</code>). <b>Vervroegd afstuderen</b> is een uitzondering die de <b>examencommissie</b> per inschrijving vrijgeeft (<code>inschrijvingen.vervroegd_afstuderen</code>, route <code>inschrijving.vervroegd-afstuderen</code>, alleen <code>rol:examencommissie,beheerder</code>); dan geldt <code>magAfstuderen() = isLopend() &amp;&amp; (isLaatsteLeerjaar() || vervroegd_afstuderen)</code>. Alle mutaties (afstuderen, vrijgeven/intrekken) worden gelogd.</p>
  <p><b>Afstudeerproces</b> (examencommissie-gedreven): tabellen <code>afstudeerprocessen</code> (één per inschrijving) + <code>afstudeerprocesstappen</code> (5 stappen uit enum <code>Afstudeerstap</code>). De examencommissie start het proces voor een afstudeerbare inschrijving; elke stap wordt STRIKT door de verantwoordelijke rol afgevinkt (<code>Afstudeerstap::magAfvinkenDoor()</code> — examencommissie stap 1-3, Studentenzaken stap 4-5) en SEQUENTIEEL. Het afvinken van de laatste stap (diploma uitgereikt) zet de inschrijving op <code>afgestudeerd</code> en het proces op <code>afgerond</code>. Routes onder <code>afstuderen.*</code> (kandidaten <code>rol:examencommissie,studentenzaken,directie,beheerder</code>; starten/afbreken <code>rol:examencommissie,beheerder</code>; stap afvinken <code>rol:examencommissie,studentenzaken,beheerder</code>). Alles gelogd.</p>

  <h2>9. Curriculum (vakken)</h2>
  <table class="kv">
    <tr><td class="k">Bron</td><td><code>database/data/curriculum.csv</code> (uit 'vakkenlijst update.xlsx', 2026-07-10), geladen door <code>CurriculumSeeder</code>. Referentiedata, geen persoonsgegevens: hoort in Git.</td></tr>
    <tr><td class="k">Herladen</td><td><code>php artisan db:seed --class=CurriculumSeeder</code> — idempotent: matcht op (opleiding, code) en werkt bij. Vakken die niet in de CSV staan blijven ongemoeid.</td></tr>
    <tr><td class="k">EC</td><td><code>vakken.ec</code> is <code>decimal(4,1)</code>: halve studiepunten (2,5) komen voor. Nooit naar <code>int</code> casten. Gebruik <code>App\Support\Ec::toon()</code> voor weergave (Nederlandse komma).</td></tr>
    <tr><td class="k">Vakcode</td><td>Uniek per opleiding: <code>unique(opleiding_id, code)</code>. Elf codes bestaan in zowel ISLTH als PMGV.</td></tr>
    <tr><td class="k">Blok</td><td><code>null</code> = het vak loopt het hele studiejaar (stage, scriptie). Views die over blok 1..4 itereren moeten blok <code>null</code> apart tonen.</td></tr>
    <tr><td class="k">Keuzevak</td><td><code>vakken.keuzevak</code>. <code>Vaktoewijzer</code> slaat keuzevakken over; <code>Overgangsbeoordeling</code> telt alleen de keuzevakken mee die aan de inschrijving zijn toegewezen.</td></tr>
  </table>
  <div class="let"><b>Synthetische vakken horen niet naast het echte curriculum.</b> De voorbeeldvakken met code <code>ISLTH-*</code> zijn verplaatst naar <code>SynthetischVakSeeder</code>, die alleen door de testsuite wordt gebruikt en bewust NIET in <code>DatabaseSeeder</code> staat. Stonden zij actief naast het echte curriculum, dan telden zij mee in de EC-totalen per leerjaar (jaar 1 werd 94 i.p.v. 60 EC) en werden zij automatisch aan elke ISLTH-student toegewezen.</div>
  <p>De <b>toetsopbouw</b> (toetsonderdelen + weging) van de <b>ISLTH</b>-vakken staat in <code>database/data/toetsonderdelen.csv</code> (bron: studiegids 2025-2026, hoofdstuk 5, per module de regel &ldquo;Toetsing&rdquo;) en wordt geladen door <code>ToetsonderdeelSeeder</code> (idempotent, matcht op opleiding+vakcode; vervangt de standaard &lsquo;Tentamen 100%&rsquo; van <code>CurriculumSeeder</code>). Genestte weging is afgevlakt naar losse onderdelen die optellen tot 100% (bv. &ldquo;Schriftelijk 80% = grammatica 40% + vertalen 40%&rdquo; + mondeling 20% &rarr; grammatica&nbsp;0,40 / vertalen&nbsp;0,40 / mondeling&nbsp;0,20). Dataveilig: een vak waarvan de huidige onderdelen al resultaten hebben wordt overgeslagen (vervangen zou cijfers wissen). De guarded migratie <code>toetsopbouw_uit_studiegids</code> past dit toe op de draaiende DB (no-op op een verse migratie). Ook <b>MGV</b> (Master IGV) is geladen uit de studiegids MIGV 2024-2025 (19 vakken, o.a. modules met werkstuk/voordracht/rollenspel/moreel beraad). <b>PMGV</b> (Pre-Master) deelt vakcodes met ISLTH en volgt per code <b>dezelfde toetslogica</b> als het gelijknamige ISLTH-vak (12 vakken; de gecombineerde code <code>B-FQ02-B-FQ03</code> volgt B-FQ02). <b>PABO</b> volgt met de eigen studiegids; die vakken houden voorlopig de standaard &lsquo;Tentamen 100%&rsquo;. De <b>docenten</b> zijn per vak gekoppeld uit de studiegidsen (regel &ldquo;Docent&rdquo;): <code>database/data/vakdocenten.csv</code> + <code>VakDocentSeeder</code> (match op genormaliseerde achternaam, zodat &ldquo;Bi&ccedil;er-Uslu&rdquo; &harr; &ldquo;Bicer-Uslu&rdquo; koppelt); guarded migratie <code>koppel_docenten_aan_vakken</code> (no-op op verse migratie). Gekoppeld: ISLTH 48/60 en MGV 18/19; <b>stage-/scriptie</b>coördinatie-vakken en de <b>keuzevakken</b> krijgen bewust geen individuele docent, en <b>PMGV/PABO</b> nog niet (geen bron). Ontbrekende docent Bouyazdouzen is aan <code>DocentSeeder</code> toegevoegd. De toetsopbouw en de docent zijn per vak verder aan te passen via <b>Vakstructuur</b>. <b>Let op:</b> een docent ziet zijn vakken pas in &lsquo;Mijn vakken&rsquo; als er een <b>gebruikersaccount</b> met rol Docent aan het docentprofiel is gekoppeld (<code>users.docent_id</code>). Er is een <b>demo-docentlogin</b> voor <b>Galal Ali</b> (<code>amer@iuasr.nl</code>), die diverse Fiqh-vakken onderwijst. De <b>e-mailconventie</b> is <code>{achternaam}@iuasr.nl</code> (dus <code>abba@iuasr.nl</code>), met enkele uitzonderingen in <code>DocentSeeder::EMAIL_UITZONDERINGEN</code> (Galal Ali → <code>amer@iuasr.nl</code>). De eerdere dummy-docenten Yusuf Aydın en Salima Boujat zijn verwijderd.</p>

  <h2>10. Takenlijst (Studentenzaken)</h2>
  <p>Tabel <code>taken</code>, model naar Outlook Taken / Microsoft Graph <code>todoTask</code>: <code>titel</code>, <code>omschrijving</code>, <code>startdatum</code>, <code>vervaldatum</code>, <code>status</code> (open | bezig | afgerond), <code>prioriteit</code> (laag | normaal | hoog), <code>afgerond_op</code>, <code>afgerond_door_id</code>. Optionele koppelingen: <code>student_id</code>, <code>toegewezen_aan_id</code>, <code>aangemaakt_door_id</code>, <code>afgerond_door_id</code> — alle vier <code>nullOnDelete</code>, zodat een taak blijft bestaan als een student of medewerker verdwijnt.</p>
  <p><code>afgerond_op</code> en <code>afgerond_door_id</code> volgen altijd de status: bij afronden worden beide gezet, bij heropenen beide op <code>null</code>. Dat gebeurt zowel via de afvinkknop als via het bewerkformulier. De afvinker is bewust een eigen veld en niet <code>toegewezen_aan_id</code>: een niet-toegewezen taak mag door iedereen worden opgepakt, en een collega mag andermans taak afronden. Bij taken die vóór deze kolom werden afgerond blijft het veld leeg; dat wordt niet met terugwerkende kracht ingevuld.</p>
  <div class="let"><b>'Te laat' is geen kolom.</b> De status wordt afgeleid uit <code>vervaldatum &lt; vandaag</code> én <code>status != afgerond</code> (<code>Taak::isTeLaat()</code>). Sla dit nooit op: anders kan een afgeronde taak in de database als 'te laat' blijven staan.</div>
  <p>Toegang uitsluitend voor Studentenzaken en Beheer (<code>Rol::magTakenBeheren()</code>, routegroep <code>rol:studentenzaken,beheerder</code>). Er is bewust <b>geen audit-logging</b>: een taak is werkverdeling, geen gevoelig persoonsgegeven. Wel blijft zichtbaar wie de taak aanmaakte en aan wie zij is toegewezen.</p>

  <h2>11. Balie / Receptie (module)</h2>
  <p>Eén tabel <code>balie_registraties</code> voor alle vijf de stromen, met twee discriminatoren: <code>soort</code> (<code>telefoon</code> | <code>bezoek</code> | <code>post</code>, enum <code>BalieSoort</code>) en <code>richting</code> (<code>inkomend</code> | <code>uitgaand</code>, enum <code>BalieRichting</code>). Bewust géén vijf aparte tabellen: de stromen delen vrijwel dezelfde velden, en het logboek moet in één keer doorzoekbaar, filterbaar en exporteerbaar zijn. Velden die niet voor elk soort gelden zijn <code>nullable</code>.</p>
  <p>Koppelingen zijn echte foreign keys op surrogaatsleutels: <code>medewerker_id</code> (bestemd voor / afspraak met, <code>nullOnDelete</code>) met <code>afdeling</code> als vrije terugval wanneer iets niet voor één persoon bestemd is, en <code>geregistreerd_door_user_id</code> (welke baliemedewerker het vastlegde, <code>nullOnDelete</code>). Indexen op <code>datum_tijd</code>, <code>(soort, richting)</code> en <code>medewerker_id</code>.</p>
  <div class="let"><b>Drie invarianten worden server-side afgedwongen</b> in <code>BalieRegistratieController::valideer()</code>, niet alleen in de UI: een <b>bezoek</b> is altijd <code>inkomend</code> (een meegestuurde <code>uitgaand</code> wordt overschreven); <b>alleen een bezoek</b> houdt een <code>vertrokken_op</code> over (bij telefoon/post wordt het op <code>null</code> gezet); en bij <b>post</b> wordt geen <code>onderwerp</code> vastgelegd, terwijl het bij telefoon en bezoek verplicht is.</div>
  <p><b>Aanwezigheid.</b> "Wie is er nu in het pand" is <b>geen kolom</b> maar een afleiding: <code>soort = bezoek</code> én <code>vertrokken_op IS NULL</code> (scope <code>nogAanwezig()</code>, helper <code>isNogAanwezig()</code>). Sla dit nooit als vlag op — dan raakt het uit de pas met het vertrekmoment.</p>
  <p><b>Autorisatie.</b> <code>Rol::magBalieBeheren()</code> (Balie, Beheerder) en <code>Rol::magBalieInzien()</code> (daarnaast uitsluitend Bestuur, alleen-lezen), met Gates <code>balie-beheren</code> en <code>balie-inzien</code>. Routegroepen: <code>rol:balie,beheerder</code> voor muteren, <code>rol:balie,beheerder,bestuur</code> voor inzage en export. De <b>Directie heeft géén toegang</b> (keuze opdrachtgever 2026-07-13): het logboek is een werkregister van de balie, geen opleidingsinformatie. De rol <code>balie</code> is bewust smal: geen studentdossiers, geen cijfers, geen personeelsdossiers — alleen de namenlijst van medewerkers (niet uit dienst) om aan te koppelen.</p>
  <p><b>Verwijderen bestaat niet.</b> Er is geen destroy-route: het logboek is een chronologisch verantwoordingsdocument. Een fout wordt gecorrigeerd met een wijziging. Aanmaak, wijziging, afmelden en export worden gelogd via <code>AuditLogger</code> (<code>veld</code>: <code>balie_registratie</code>, <code>balie_vertrek</code>, <code>balie_export</code>).</p>
  <p><b>Module &amp; account.</b> De migratie <code>2026_07_13_100100_balie_module_en_account</code> voegt de modulerij (<code>modules.sleutel = balie</code>) én het rolaccount <code>balie@iuasr.nl</code> toe, allebei idempotent (bestaat het al, dan gebeurt er niets). Zo krijgt een bestaande database de module met alleen <code>php artisan migrate</code>, zonder seeders. Synthetische voorbeelddata staat in <code>BalieSeeder</code> (draait na de HR-seeders; doet niets als er al registraties zijn).</p>

  <h2>12. Bibliotheek (module)</h2>
  <p><b>Titel en exemplaar zijn gescheiden</b> (model van Koha e.a.): <code>bibliotheek_publicaties</code> is het bibliografische record (ISBN, titel, jaar, druk, vakgebied, reeks+deelnummer), <code>bibliotheek_exemplaren</code> is het fysieke boek (uniek <code>serienummer</code>, kast, <code>status</code>). Uitlenen gebeurt op EXEMPLAARNIVEAU. Auteurs en talen zijn n-op-n (<code>bibliotheek_publicatie_auteur</code>, <code>bibliotheek_publicatie_taal</code>) — een publicatie kan meerdere talen hebben. Een <b>boekreeks</b> (<code>bibliotheek_reeksen</code>) is een eigen record; de delen zijn gewone publicaties met <code>reeks_id</code> + <code>deelnummer</code>, dus los vindbaar en uitleenbaar. Een <b>tijdschrift</b> is een publicatie met <code>bibliotheek_uitgaven</code> (afleveringen) en daaronder <code>bibliotheek_artikelen</code> (+ eigen auteurs-pivot).</p>
  <p><b>Meertaligheid.</b> De verbinding staat op <code>utf8mb4</code> / <code>utf8mb4_unicode_ci</code> (config/database.php), dus Arabisch schrift en Turkse diakrieten worden correct opgeslagen, doorzocht en accent-ongevoelig gesorteerd. Er is geen aparte ingreep per tabel nodig. In de formulieren staat <code>dir="auto"</code> op de tekstvelden, zodat rechts-naar-links invoer goed wordt weergegeven.</p>
  <div class="let"><b>Afleidingen, geen kolommen.</b> 'Te laat' (<code>verwachte_retour_op &lt; vandaag</code> én <code>retour_op IS NULL</code>), 'op tijd ingeleverd' (<code>retour_op &lt;= verwachte_retour_op</code>) en 'aantal dagen te laat' worden BEREKEND (<code>Uitlening::isTeLaat()</code>, <code>isOpTijdIngeleverd()</code>, <code>dagenTeLaat()</code>, scopes <code>lopend()</code>/<code>teLaat()</code>/<code>binnenkortRetour()</code>). Sla ze nooit op: dan lopen ze uit de pas met de datums. Hetzelfde geldt voor de status van een exemplaar: de LOPENDE UITLENING is de waarheid (<code>Exemplaar::isUitleenbaar()</code> controleert beide), de status is de weergave daarvan.</div>
  <p><b>Lener.</b> Precies één van <code>student_id</code> / <code>medewerker_id</code> is gevuld (echte FK's, <code>nullOnDelete</code>); dat wordt in <code>UitleningController::store()</code> afgedwongen. Naam, telefoon en e-mail komen uit het dossier — geen tweede administratie.</p>
  <p><b>Termijn &amp; boete.</b> Standaardtermijnen in <code>config/sis.php</code> → <code>sis.bibliotheek.uitleentermijn_student_dagen</code> (21) en <code>..._docent_dagen</code> (60), env-overschrijfbaar (<code>SIS_BIEB_TERMIJN_*</code>). <b>TE BEVESTIGEN</b> door de opdrachtgever — het zijn terugvalwaarden, geen vastgestelde norm. <b>Boete is bewust niet gebouwd</b> (regels niet vastgesteld); de kolom <code>boete_bedrag</code> staat wel klaar zodat een latere fase geen schemawijziging nodig heeft.</p>
  <p><b>E-mail.</b> Vijf sjablonen in <code>bibliotheek_emailsjablonen</code> (enum <code>BibliotheekMailsoort</code>), beheerd door de Beheerder; variabelen <code>&#123;&#123;Naam&#125;&#125;</code>, <code>&#123;&#123;Titel&#125;&#125;</code>, <code>&#123;&#123;Uitleendatum&#125;&#125;</code>, <code>&#123;&#123;Retourdatum&#125;&#125;</code>, <code>&#123;&#123;AantalDagenTeLaat&#125;&#125;</code>. <code>BibliotheekMailer</code> rendert, verstuurt (<code>BibliotheekBericht</code>, CC uit <code>sis.mail.cc.bibliotheek</code>) en logt élke poging in <code>bibliotheek_emaillogs</code> (append-only, ook mislukkingen). <b>Een mislukte mail blokkeert de handeling niet</b> — de uitlening is dan al vastgelegd.</p>
  <p><b>Scheduler.</b> <code>bibliotheek:herinneringen</code> (dagelijks 07:30, <code>routes/console.php</code>): herinnering X dagen vooraf (standaard 3), waarschuwing te laat voor studenten (eenmalig), herhaalherinnering voor docenten (elke 3 dagen, geen boete). <b>Idempotent</b>: het commando leest het e-maillogboek, dus een dubbele run verstuurt niets dubbel.</p>
  <p><b>Autorisatie.</b> <code>Rol::magBibliotheekBeheren()</code> (Bibliotheek, Beheerder) en <code>magBibliotheekInzien()</code> (+ Bestuur, alleen-lezen); <code>magBibliotheekSjablonenBeheren()</code> = alleen Beheerder; <code>magBibliotheekSignaalZien()</code> (Studentenzaken, Bibliotheek, Beheer) stuurt het te-laat-blok op het SZ-dashboard aan. Gates <code>bibliotheek-inzien</code>/<code>-beheren</code>/<code>-signaal</code>. Elke mutatie en elke export wordt gelogd via <code>AuditLogger</code>; bij het bijwerken van een publicatie worden alleen de GEWIJZIGDE velden gelogd, mét oude en nieuwe waarde (opdracht §3).</p>
  <p><b>Nog te bouwen (latere fase):</b> de <b>importwizard</b> voor de bestaande Excel-bestanden (boeken, tijdschriften) en de Word-documenten met tijdschriftartikelen. Het datamodel is daarop voorbereid; het importontwerp met kolommapping volgt zodra de bronbestanden zijn aangeleverd.</p>

  <h2>13. Regulier onderhoud</h2>
  <ul>
    <li><b>Migraties:</b> <code>php artisan migrate</code> na een update (reversible; maak eerst een back-up).</li>
    <li><b>Cache:</b> <code>php artisan optimize:clear</code> bij onverwacht gedrag na wijzigingen.</li>
    <li><b>Logs:</b> <code>storage/logs/</code> (zitten niet in de back-up).</li>
    <li><b>Tests:</b> <code>php artisan test</code> moet groen zijn vóór uitrol.</li>
    <li><b>Scheduler (vereist voor automatische e-mails).</b> Zorg dat er een <b>cron</b> draait die elke minuut <code>php artisan schedule:run</code> aanroept (of <code>php artisan schedule:work</code>). Geplande taken (<code>routes/console.php</code>): <code>nieuws:ophalen</code> (dagelijks 23:00) en <code>hr:notificaties</code> (dagelijks 07:00). Die laatste stuurt de <b>verjaardagsfelicitaties</b> en de meldingen van <b>startend wettelijk verlof</b>; hij is idempotent (log in <code>hr_notificaties</code>), dus meerdere runs op een dag versturen niets dubbel.</li>
    <li><b>E-mail &amp; afdelings-CC.</b> Elke automatische systeem-e-mail krijgt een CC naar de afdelingspostbus (config <code>sis.mail.cc</code>: HR/Studentenzaken/Examencommissie; env <code>SIS_MAIL_CC_*</code>). De self-service-verlofmelding gaat naar <code>sis.hr.notificatie_email</code>. Controleer dat de <b>mailconfiguratie</b> (<code>MAIL_*</code>) klopt; e-mailfouten worden gelogd maar blokkeren de gebruikersactie niet.</li>
  </ul>

  <h2>14. Migratie uit de oude Access-database (tijdelijk)</h2>
  <p>De historische studentgegevens uit het oude Access-systeem (<code>IUTSTD…mdb</code>, sinds ca. 2009) worden in twee stappen overgezet. De bronbestanden blijven <b>buiten de repository</b> (AVG): de per-jaar geëxporteerde CSV's staan lokaal onder <code>Documents\IUASR-migratie-export\</code>.</p>
  <ul>
    <li><b>Export (buiten het systeem):</b> de Access-tabellen zijn met een PowerShell/OLEDB-script (<code>Microsoft.ACE.OLEDB.16.0</code>) geëxporteerd naar semikolon-gescheiden UTF-8-CSV's: referentietabellen plus <code>cijfers-JJJJ-JJJJ.csv</code> per studiejaar (2009-2010 t/m 2025-2026). Grondgetallen: 3.461 studenten, 27.214 cijferregels.</li>
    <li><b>Import in het systeem — tijdelijk scherm <code>Studentenzaken → Migratie (import)</code></b> met drie stappen (volgorde: 1 studenten → 2 vakken → 3 cijfers). Draai per bestand <b>altijd eerst een controle (preview)</b>; die schrijft niets en toont aantallen plus een voorbeeldtabel. Pas daarna <b>Nu importeren</b>. Alle stappen zijn idempotent (bestaande gegevens worden niet overschreven of verdubbeld).</li>
    <li><b>Fase 1 — studenten (<code>_studenten.csv</code>):</b> <code>SDT-NR → studentnummer</code>, naam, geboortedatum/-plaats, nationaliteit (gematcht of aangemaakt), adres, e-mail, <code>Opleiding → vooropleiding</code> (let op: in Access is "Opleiding" de vooropleiding), diploma. <b>BSN en rekeningnummer worden bewust niet meegenomen.</b> Junk-/naamloze rijen worden overgeslagen.</li>
    <li><b>Fase 2a — vakken (<code>_vaklijsten.csv</code>):</b> elk oud vak wordt een (inactief) historisch vak met de EC-punten uit de vaklijst, onder de aparte opleiding <b>“Bachelor Islamitische Theologie (historisch t/m 2025)”</b> (code <code>BA-HIST</code>). Zo blijft de historische data volledig gescheiden van het huidige curriculum.</li>
    <li><b>Fase 2b — cijfers (<code>cijfers-JJJJ-JJJJ.csv</code>, één bestand per studiejaar):</b> per regel één eindcijfer (<code>cl-gemmid</code>, 0–100 → 0–10) voor student+vak+periode, opgeslagen als resultaat op het onderdeel “Eindcijfer (gemigreerd)”. De periode (studiejaar) en de inschrijving per student+jaar worden automatisch aangemaakt/hergebruikt; ontbrekende vakken worden alsnog aangemaakt. Vrijstellingen komen als resultaat zonder cijfer. Regels zonder cijfer, met onbekende student of onleesbare periode worden overgeslagen en geteld. Voldoende-grens 5,5.</li>
    <li><b>Inzage:</b> <code>Cijfers → Historisch dossier</code> (<code>HistorischDossierController</code>, views <code>historisch/index</code>+<code>historisch/show</code>) toont de gemigreerde cijfers alleen-lezen, per studiejaar. Route <code>rol:examencommissie,directie,beheerder</code> — bewust NIET Studentenzaken (rolscheiding cijfers). Inzage door examencommissie/directie wordt gelogd. De knop <b>Printbare PDF</b> (<code>historisch.pdf</code>) rendert een A4 via <code>Documentondertekening::pdfVanHtml()</code> (dompdf, ongewaarmerkt — informatief, want niet opnieuw vastgesteld); afdrukken wordt gelogd als UITGIFTE.</li>
    <li><b>Bulk-export</b> (<code>historisch.bulk</code>, <code>?scope=</code>): per studiejaar een gecombineerd overzicht, of <code>scope=alle</code> voor de hele opleiding. dompdf is geheugen-/tijdintensief, daarom wordt per studiejaar in <b>brokken van 50 studenten</b> gerenderd (±1,6s/&lt;100 MB per stuk); meerdere delen of jaren worden als ZIP aangeboden. De hele opleiding (±2.500 studentregels → ±59 PDF's) duurt ±3–4 min bij ±200 MB piek — daarom <code>memory_limit 768M</code> en <code>set_time_limit(600)</code> in de actie. Wordt dit vaker/zwaarder, verplaats het dan naar een wachtrij-job.</li>
    <li><b>Code:</b> <code>App\Support\MigratieImport</code> (<code>verwerkStudenten</code>/<code>verwerkVakken</code>/<code>verwerkCijfers</code>), <code>MigratieController</code>, view <code>migratie/index</code>; tests in <code>tests/Feature/MigratieTest.php</code> en <code>HistorischDossierTest.php</code>. Het import-scherm en de route (<code>rol:studentenzaken,beheerder</code>) zijn <b>tijdelijk</b> en kunnen na de migratie worden verwijderd (inclusief de historische opleiding als die niet gewenst is).</li>
  </ul>

  <div class="tip">Deze handleiding wordt bijgewerkt zodra er functies of infrastructuur wijzigen. Controleer de datum onderaan op actualiteit.</div>
</body>
</html>
