  <h2 id="h1">1. Waarvoor is dit systeem?</h2>
  <p>Het IUASR Management Systeem is de interne administratie van de hogeschool. U beheert er — afhankelijk van uw rol — studenten, inschrijvingen, cijfers, collegegeld, cursussen, relatiebeheer &amp; stage, personeelszaken (HR), documenten en rapporten. Het systeem draait uitsluitend op het interne netwerk en is gescheiden van het publieke aanmeldportaal.</p>
  <p><b>Weergave.</b> Het systeem opent standaard in <b>donkere modus</b> (energiezuiniger en rustiger voor de ogen). Rechtsboven staat een knop (maan/zon) om te wisselen tussen donker en licht; uw keuze wordt onthouden en geldt ook voor het inlogscherm.</p>
  <div class="let">Alle gegevens in de ontwikkel-/testomgeving zijn <b>synthetisch</b> (verzonnen). Ga zorgvuldig om met echte persoonsgegevens; deze vallen onder de AVG.</div>

  <h2 id="h2">2. Inloggen &amp; een module kiezen</h2>
  <p>U logt in via uw IUASR-account (Microsoft-account, Single Sign-On). Na het inloggen verschijnt het <b>modulekeuzescherm</b>: het systeem groeit uit tot een platform met meerdere onderdelen. Kies met welke module u wilt werken.</p>
  <ul>
    <li><b>Studentenzaken</b> — het huidige systeem (inschrijving, cijfers, collegegeld, documenten).</li>
    <li><b>Cursussen Administratie</b> — cursusbeheer, cursisten en cursusgelden (boekhouding).</li>
    <li><b>Relatiebeheer &amp; Stage</b> — stagescholen en werkveldrelaties, contactpersonen en stageplaatsen (opleidingoverstijgend).</li>
    <li><b>HR / Personeelszaken</b> — medewerkers, dienstverband en FTE, verlof &amp; verzuim, gesprekken en rapportages.</li>
    <li><b>Scriptie</b> — later te ontwikkelen; nu zichtbaar als "Binnenkort".</li>
  </ul>
  <p>Welke modules u kunt openen, hangt af van uw <b>rol</b>. De meeste medewerkers zien alleen Studentenzaken; de Financiële Administratie en de Beheerder zien meerdere modules. Nog niet gebouwde modules staan grijs met de melding <b>Binnenkort</b>. Rechtsboven in elk scherm brengt de knop <b>Modules</b> u terug naar het keuzescherm.</p>
  <p>Werkt u met cursussen, dan staat op het keuzescherm onder <b>Cursussen</b> een <b>aparte knop voor elke cursus</b> die u mag openen. Zo kiest u na het inloggen meteen uw eigen cursus, zonder eerst de hele module te doorzoeken. Een <b>cursusdirecteur</b> ziet alleen de eigen cursus(sen); de Financiële Administratie, de Beheerder en het Schoolbestuur zien alle cursussen. Klikt u op een cursus, dan opent de <b>cursus-startpagina</b> met de kerncijfers (inschrijvingen, betaalgraad, openstaand), de cursisten van die cursus en knoppen naar de cursusgelden en de rapportage. Kiest u per ongeluk een cursus die niet van u is, dan houdt het systeem u tegen.</p>
  <p>Op het keuzescherm staan naast de modules twee <b>snelkoppelingen</b>: het <b>Schoolbestuur</b> vindt er de knop <b>Bestuur — globaal overzicht</b> (zie hieronder), en de <b>Beheerder</b> vindt er een blok <b>Systeembeheer</b> met directe toegang tot Gebruikers &amp; rollen, Opzoektabellen, het Audit-log, Back-up &amp; herstel en de technische handleiding. Zo hoeft de Beheerder voor die taken niet meer eerst de module Studentenzaken te openen.</p>
  <p>Op <b>Gebruikers &amp; rollen</b> maakt de Beheerder nieuwe medewerkersaccounts aan (naam, e-mail, primaire rol en eventueel extra rollen). Er wordt geen wachtwoord ingesteld: inloggen verloopt via Entra ID (SSO). Bij een bestaande gebruiker kan de Beheerder de primaire rol wijzigen en via <b>Extra rollen</b> aanvullende rollen aan- of uitvinken. Alle wijzigingen worden gelogd.</p>

  <div class="tip"><b>Jaarovergang (nieuw studiejaar).</b> Er is altijd precies één <b>huidig studiejaar</b> actief. Het systeem staat sinds de jaarwisseling op <b>Studiejaar 2026 / 2027</b>; de collegegeldtarieven voor dat jaar (Bachelor Islamitische Theologie € 3.500, Pre-Master GV € 3.500, Master GV € 4.000, PABO € 3.500) staan klaar. Het vorige jaar (2025 / 2026) blijft als <b>historie</b> bewaard. Wilt u later naar een volgend jaar overschakelen, dan doet de <b>Beheerder</b> dat via <b>Opzoektabellen &rarr; Studiejaren</b>: vink bij het gewenste jaar <b>Huidig studiejaar</b> aan — het systeem zet het vorige jaar dan automatisch uit. Studenten schuiven per stuk mee via <b>Herinschrijven</b>; nieuwe inschrijvingen komen standaard in het huidige studiejaar.</div>
  <h3>Bestuurspagina (globaal overzicht)</h3>
  <p>Het <b>Schoolbestuur</b> heeft één instellingsbrede <b>Bestuurspagina</b> die de statistieken van <b>alle modules en afdelingen</b> op één scherm bundelt (voorheen twee losse links, Bestuur en Dashboard, nu samengevoegd tot dit ene overzicht). Alles is <b>alleen-lezen</b> en geordend in vijf duidelijke rubrieken met hoofdlijnen: <b>A · Studenten &amp; onderwijs</b> (inschrijvingen, studiesucces, aanwezigheid per opleiding), <b>B · Financiën</b> (collegegeld van de opleidingen én de cursusgelden van de cursussen, met een gecombineerd totaal), <b>C · Cursussen</b> (aanbod en cursisten), <b>D · Relatiebeheer &amp; stage</b> (organisaties, stageplaatsen, lopende en te beoordelen stages) en <b>E · HR / Personeelszaken</b> (medewerkers, FTE en verzuim per afdeling). U opent de pagina via de tegel <b>Globaal overzicht</b> op het keuzescherm of via <b>Bestuursoverzicht</b> in het menu; ook na het inloggen komt u er direct op uit. Voor detailrapporten leiden knoppen door naar het alumni-rapport, de aanwezigheid, het cursusrapport, het HR-rapport, de HR-lijst <b>verzuim &amp; verlof</b> en het relatiebeheer. De Beheerder kan dezelfde pagina bekijken.</p>
  <p><b>Alle rapportages staan in het menu — u blijft in de Bestuur-omgeving.</b> Deze detailrapporten staan ook in de linkerbalk onder <b>Rapportages</b>. Als Schoolbestuur houdt u <b>altijd het eigen Bestuur-menu</b>, ook wanneer u een rapport van een andere module opent. U belandt dus niet meer onbedoeld in een andere module (zoals Personeelszaken) met een menu vol beheerlinks waarvoor u geen rechten hebt — die eerdere foutmeldingen (&ldquo;geen rechten om deze pagina te bekijken&rdquo;) zijn daarmee verholpen. Vanuit elk rapport keert u met één klik terug naar het <b>Bestuursoverzicht</b>.</p>

  <h2 id="h3">3. Rollen: wie mag wat</h2>
  <p>Het systeem kent een strikte rolscheiding. Deze wordt aan de serverkant afgedwongen — u ziet alleen de schermen die bij uw rol horen.</p>
  <table class="rol">
    <tr><th>Rol</th><th>Wat u doet</th></tr>
    <tr><td><b>Studentenzaken</b></td><td>Studenten in-/uitschrijven, gegevens en documenten beheren, collegegeld, verklaringen, vrijstellingen registreren, de 50%-aanwezigheidsregeling vastleggen. <b>Geen</b> cijferinzage.</td></tr>
    <tr><td><b>Docent</b></td><td>Cijfers invoeren voor <b>uw eigen vakken</b> en indienen bij de examencommissie. De <b>aanwezigheid</b> per college registreren (verplicht).</td></tr>
    <tr><td><b>Examencommissie</b></td><td>Cijferlijsten vaststellen, tentamenlijsten en cijferlijsten inzien, studievoortgang en aanwezigheid beoordelen.</td></tr>
    <tr><td><b>Directie</b></td><td>Cijfers, aanwezigheid en rapporten inzien van <b>uitsluitend de eigen opleiding(en)</b>. Een directielid wordt door Beheer aan één of meer opleidingen gekoppeld en ziet alleen die studenten.</td></tr>
    <tr><td><b>Financiële Administratie</b></td><td>Collegegeldbetalingen registreren en achterstanden bewaken.</td></tr>
    <tr><td><b>Schoolbestuur</b></td><td>Kerncijfers, aanwezigheidsstatistiek, het <b>alumni-rapport</b> en alle ondertekende documenten inzien. <b>Geen</b> cijferinzage.</td></tr>
    <tr><td><b>Beheerder</b></td><td>Gebruikers/rollen, referentietabellen, audit-log, back-ups en het volledig verwijderen van foutieve studentrecords.</td></tr>
  </table>
  <p><b>Meerdere rollen.</b> Een medewerker kan naast een <b>primaire rol</b> ook <b>extra rollen</b> hebben (bijvoorbeeld iemand die zowel Studentenzaken als de cursusadministratie doet). De primaire rol bepaalt uw <b>startdashboard</b> en hoe u in beeld staat; de extra rollen tellen daar bovenop, zodat u alles mag wat één van uw rollen toestaat. Overige modules bereikt u via de knop <b>Modules</b> rechtsboven. De Beheerder kent de rollen toe (zie hoofdstuk Beheer).</p>

  <h2 id="h4">4. Uw dashboard</h2>
  <p>Na het inloggen ziet u uw dashboard met kerncijfers en grafieken die bij uw rol passen — bijvoorbeeld aantallen studenten, instroom, slaagpercentages of financiële cijfers. Signaleringen (zoals NT2-deadlines of nog aan te leveren documenten) staan er ook.</p>
  <p>Onderaan het dashboard staat een lijst <b>Studenten met vrijstelling</b>, met per student de vrijgestelde vakken. Deze is zichtbaar voor alle rollen behalve Beheer en de Financiële Administratie.</p>
  <p>Daarnaast toont het dashboard (voor Studentenzaken, Directie en de Financiële Administratie) een lijst <b>Studenten met een dubbele inschrijving</b>: studenten die twee opleidingen tegelijk volgen, met beide opleidingen erbij. Directie ziet hierin alleen studenten van de eigen opleiding(en).</p>
  <p>Op het dashboard staat ook het venster <b>Studenten met 50%-aanwezigheidsregeling</b>, met de opleiding en het studiejaar waarvoor de regeling geldt. Docenten zien daarin alleen de studenten uit hun eigen vakken; Directie alleen die van de eigen opleiding(en); de Financiële Administratie ziet dit venster niet. Voor docenten, directie en schoolbestuur verschijnt daarnaast het venster <b>Aanwezigheidsregistratie nog niet volledig</b>, met de vakken en de weken die nog ontbreken.</p>

  <h2 id="h5">5. Werken met studenten (Studentenzaken)</h2>
  <h3>Student zoeken</h3>
  <p>Ga naar <b>Alle studenten</b> en gebruik de zoekbalk (studentnummer of naam). Klik op een student om het dossier te openen.</p>
  <h3>Nieuwe student inschrijven</h3>
  <p>Kies <b>Student inschrijven</b>, vul de gegevens in en bevestig. Het studentnummer wordt automatisch toegekend en de vakken van het studiejaar worden toegewezen. Voor grote aantallen bestaat <b>Bulk inschrijven</b> (CSV-export van het aanmeldportaal), met een controlestap vóór definitief importeren. In die controlestap <b>kiest u het studiejaar</b> waarin de studenten worden ingeschreven (bijvoorbeeld het komende jaar); bij een toekomstig studiejaar wordt de inschrijfdatum automatisch de startdatum (1 september).</p>
  <h3>Gegevens wijzigen</h3>
  <p>Open het dossier, tabblad <b>Persoonsgegevens</b>, en kies <b>Wijzig gegevens</b>. Onder <b>Acties</b> vindt u herinschrijven, uitschrijven en schorsen.</p>
  <h3>Herinschrijven (met of zonder studiewissel)</h3>
  <p>Bij <b>Herinschrijven</b> maakt u een nieuwe inschrijving terwijl het studentnummer en de persoonsgegevens gelijk blijven. U kiest de <b>opleiding</b>: dezelfde opleiding (vervolg naar een volgend leerjaar of hetzelfde jaar overdoen) óf een <b>andere opleiding</b> (studiewissel — bijvoorbeeld van een cursus naar een bacheloropleiding). Kiest u een andere opleiding, dan wordt het leerjaar automatisch 1 en verschijnen alleen de klassen van die opleiding. De vakken worden op de gekozen opleiding en het gekozen leerjaar toegewezen; eerder behaalde resultaten blijven op de vorige inschrijving bewaard.</p>
  <h3>Twee opleidingen tegelijk (dubbele inschrijving)</h3>
  <p>Een student mag twee opleidingen tegelijk volgen. Kies op het dossier onder <b>Acties</b> de knop <b>Tweede opleiding</b>, selecteer een <b>andere</b> opleiding en (meestal) het huidige studiejaar. Er ontstaat een tweede actieve inschrijving; beide opleidingen staan bovenaan het dossier met de vermelding <b>dubbele inschrijving</b>. Dezelfde opleiding twee keer in hetzelfde studiejaar is niet mogelijk. Het <b>collegegeld wordt per studiejaar één keer</b> berekend, ook bij twee opleidingen.</p>
  <h3>Afstuderen (alumnus)</h3>
  <p>Rondt een student de opleiding af, kies dan op het dossier onder <b>Acties</b> de knop <b>Afgestudeerd markeren</b>. U kiest de opleiding en de <b>afstudeerdatum</b>. De inschrijving krijgt de status <b>Afgestudeerd</b> en wordt daarmee <b>afgerond</b>: korting, betaalregeling, aanwezigheidsregeling en de vaktoewijzing zijn voor die opleiding niet meer wijzigbaar. De student krijgt de markering <b>Alumnus</b>. Het <b>studentnummer blijft behouden</b> en de afgeronde opleiding blijft als historie op het dossier staan. Wil de student later een <b>andere</b> opleiding volgen, dan schrijft u die als nieuwe inschrijving in (<b>Herinschrijven</b>); dezelfde (afgeronde) opleiding opnieuw kan niet.</p>
  <div class="tip"><b>Afstuderen kan alleen in het laatste leerjaar.</b> Studeert een student bij hoge uitzondering een jaar eerder af (wegens vrijstellingen of eerder behaalde EC), dan geeft de <b>examencommissie</b> dit eerst vrij: op het dossier (tabblad <b>Inschrijving &amp; klas</b>, kaart <b>Vervroegd afstuderen</b>) klikt de examencommissie op <b>Vrijgeven</b>. Pas daarna verschijnt de knop <b>Afgestudeerd markeren</b> voor Studentenzaken.</div>
  <h3>Afstudeerproces (examencommissie)</h3>
  <p>Naast het losse <b>Afgestudeerd markeren</b> kent het systeem een volledig <b>afstudeerproces</b> in vijf stappen, gestart door de <b>examencommissie</b>. Onder <b>Afstuderen &rarr; Kandidaten</b> staan de studenten in het laatste leerjaar; de examencommissie klikt op <b>Start proces</b>. Op het studentdossier (kaart <b>Afstudeerproces</b>) worden de stappen afgevinkt — <b>strikt per rol</b>:</p>
  <ol>
    <li><b>Afstudeerverzoek ingediend</b> — examencommissie</li>
    <li><b>Alle vakken gecontroleerd</b> — examencommissie</li>
    <li><b>Stage en scriptie gecontroleerd</b> — examencommissie</li>
    <li><b>Diploma klaarmaken</b> — Studentenzaken</li>
    <li><b>Diploma uitgereikt</b> — Studentenzaken</li>
  </ol>
  <p>De stappen worden <b>op volgorde</b> doorlopen; elke rol vinkt alleen de eigen stap(pen) af (een optionele opmerking legt bevindingen vast). Zodra de laatste stap (<b>Diploma uitgereikt</b>) is afgevinkt, wordt de student automatisch <b>Afgestudeerd</b> (alumnus) en is de inschrijving afgerond. Een lopend proces kan de examencommissie afbreken. Alle stappen worden gelogd met datum en naam.</p>
  <p><b>Studentenzaken</b> ziet elk gestart afstudeerproces op het <b>dashboard</b> (venster <b>Afstudeerprocessen</b>). Zodra het de beurt van Studentenzaken is (diploma klaarmaken of uitreiken) staat er <b>Actie: Studentenzaken</b> — zo wordt geen afstudeeraanvraag gemist of vergeten.</p>
  <h3>Interne notities</h3>
  <p>Op het dossier staat een kaart met <b>interne notities</b> voor de onderlinge communicatie. <b>Studentenzaken</b> en <b>Beheer</b> kunnen notities <b>toevoegen en verwijderen</b>; <b>Directie</b> en <b>Schoolbestuur</b> kunnen ze <b>meelezen</b> (alleen-lezen). Directie ziet uiteraard alleen notities van studenten binnen de eigen opleiding(en).</p>
  <p>De <b>examencommissie</b> heeft daarnaast een <b>eigen</b> notitieblok op het dossier (kaart <b>Notities examencommissie</b>) voor haar werkaantekeningen — bevindingen en overwegingen, bijvoorbeeld rondom het afstuderen. Deze notities zijn <b>uitsluitend voor de examencommissie</b> zichtbaar en worden niet gedeeld met Studentenzaken, Directie of Bestuur. Elke notitie krijgt automatisch datum en auteur.</p>
  <h3>Documenten</h3>
  <p>In het dossier uploadt u documenten (identiteitsbewijs, diploma, cijferlijst, pasfoto, overig). Ontbreekt iets nog, zet dan <b>“levert later aan”</b> aan — de student verschijnt dan als herinnering op het dashboard.</p>
  <h3>Landelijke kennistoetsen (PABO)</h3>
  <p>Studenten van de PABO moeten de landelijke kennistoetsen halen (de RWT reken-/wiskundetoets en de LKT-kennisbasistoetsen taal en rekenen), binnen <b>twee jaar</b> na inschrijving. Zodra een student zich voor de PABO inschrijft, verschijnt op het dossier (kaart <b>Landelijke kennistoetsen</b>) automatisch de status per toets met de deadline. Registreer een behaalde toets door de datum in te vullen en op <b>Opslaan</b> te klikken. Op het dashboard van Studentenzaken staan de studenten met openstaande of verstreken toetsen — vergelijkbaar met de NT2-bewaking. De set kennistoetsen per opleiding wordt beheerd door Beheer via <b>Opzoektabellen &rarr; Landelijke kennistoetsen</b>.</p>

  <h3>50%-aanwezigheidsregeling</h3>
  <p>Normaal wordt van een student <b>75%</b> aanwezigheid verwacht (studiegids §2.3.3). Met de <b>50%-aanwezigheidsregeling</b> hoeft de student minimaal de <b>helft</b> van de lessen, practica en colleges bij te wonen. De regeling wordt <b>toegestaan door de directie</b> en door Studentenzaken vastgelegd.</p>
  <p>Open het dossier, tabblad <b>Inschrijving &amp; klas</b>. Onder <b>Huidige inschrijving</b> staat het vinkje <b>50% Aanwezigheidsregeling</b>. Zet het aan (of uit) en klik op <b>Opslaan</b>. De wijziging wordt gelogd.</p>
  <div class="tip">De regeling hangt aan de <b>inschrijving</b>: zij geldt voor één opleiding in één studiejaar. Bij <b>herinschrijven</b> — of bij een tweede opleiding — moet de regeling dus <b>bewust opnieuw</b> worden toegekend. Zo blijft het een jaarlijks besluit van de directie en loopt zij niet stilzwijgend door.</div>
  <p>De regeling is zichtbaar voor Studentenzaken, Docenten, Examencommissie, Directie, Schoolbestuur en Beheer — op het studentdossier, op het dashboard en (voor de docent) op de aanwezigheidslijst, waar de student het label <b>50%</b> achter de naam krijgt.</p>

  <h3>Taken (takenlijst Studentenzaken)</h3>
  <p>Onder <b>Taken</b> staat de <b>gedeelde takenlijst</b> van de afdeling, opgezet naar het model van Outlook Taken. Alleen Studentenzaken en Beheer hebben er toegang toe.</p>
  <p>Een taak heeft een <b>onderwerp</b> (het enige verplichte veld), een optionele <b>begindatum</b>, een <b>vervaldatum</b> (“moet af op”), een <b>prioriteit</b> (laag, normaal, hoog) en een <b>status</b>: Open, Bezig of Afgerond. Klik op <b>Nieuwe taak</b> om er een toe te voegen.</p>
  <p>De lijst is <b>gedeeld</b>: iedereen ziet alle taken. Een taak kunt u aan uzelf of aan een collega toewijzen, of aan niemand — dan is zij vrij op te pakken. Met het vinkje <b>Alleen mijn taken</b> filtert u de lijst.</p>
  <div class="tip"><b>Te laat</b> is geen status die u zelf zet. Een taak wordt automatisch als te laat gemarkeerd zodra de vervaldatum is verstreken en zij nog niet is afgerond. Een taak <b>zonder</b> vervaldatum staat onderaan de lijst en verschijnt niet in de signalering.</div>
  <p>Vinkt u een taak af met het <b>rondje links</b>, dan wordt zij afgerond en wordt vastgelegd <b>wanneer</b> en door <b>wie</b>. Nogmaals klikken heropent haar; het afrondmoment en de afvinker vervallen dan weer.</p>
  <p>Onderaan de takenlijst staat de sectie <b>Afgerond</b> met de 25 laatst afgeronde taken, inclusief de kolommen <b>Toegewezen aan</b> en <b>Afgevinkt door</b>. Dat hoeft niet dezelfde persoon te zijn: een taak die aan een collega is toegewezen mag u gewoon afvinken, en dan staat úw naam bij <b>Afgevinkt door</b>. Bij taken die al vóór deze functie waren afgerond blijft die kolom leeg.</p>
  <p><b>Koppeling met een student:</b> geef bij een taak een student op, dan verschijnt de taak ook op het dossier van die student (kaart <b>Taken</b>), waar u met één regel een nieuwe taak kunt toevoegen. Wordt een student later verwijderd, dan blijft de taak bestaan zonder koppeling.</p>
  <p><b>Op uw dashboard</b> staat het venster <b>Mijn taken</b>: uw eigen taken en de taken die aan niemand zijn toegewezen, met een vervaldatum binnen zeven dagen of al verstreken, op urgentie gesorteerd. U kunt ze daar direct afvinken.</p>

  <h3>Vakstructuur: het curriculum</h3>
  <p>Onder <b>Vakstructuur</b> legt u per opleiding, per studiejaar en per blok de vakken vast. Het IUASR-curriculum staat er al in: Bachelor Islamitische Theologie, Pre-Master GV en Master GV (PABO volgt later).</p>
  <p>Drie dingen om te weten:</p>
  <ul>
    <li><b>Halve studiepunten</b> zijn toegestaan. Vakken als Standaard Arabisch en Qoranrecitatie tellen 2,5 EC.</li>
    <li>Een vak zonder blok loopt het <b>hele studiejaar</b>. Dat geldt voor de stages, de bachelorscriptie en de masterthesis. In de vakstructuur staan zij onder het kopje <b>Hele studiejaar</b>.</li>
    <li>Vakken uit de <b>keuzeruimte</b> zijn gemarkeerd als <b>keuzevak</b>. Zij worden bij inschrijving <b>niet automatisch</b> toegewezen: de student kiest, en u legt die keuze vast via <b>Vakken aanpassen</b> op het dossier (tabblad Inschrijving &amp; klas). Bachelor jaar 4 bestaat daardoor uit 40 EC verplicht plus 20 EC uit de keuzeruimte.</li>
  </ul>
  <div class="tip">Dezelfde vakcode mag in twee opleidingen voorkomen. Zo wordt <b>B-QR02</b> zowel in de bachelor als in de pre-master aangeboden; het zijn aparte vakken met een eigen cijferlijst, docent en aanwezigheidslijst.</div>

  <h3>Vrijstellingen (workflow examencommissie &rarr; Studentenzaken)</h3>
  <p>Een vrijstelling wordt <b>verleend door de examencommissie</b>. De examencommissie legt het besluit vast en stuurt het intern naar Studentenzaken; het verschijnt dan als taak op uw dashboard onder <b>Vrijstellingsbesluiten van de examencommissie</b>. Klik op <b>Verwerken</b> en de vrijstelling wordt automatisch op het vak van de student vastgelegd — u hoeft niets over te typen. Is het vak nog niet toegewezen, dan krijgt u een melding om het eerst toe te wijzen.</p>
  <p>U kunt een vrijstelling ook <b>handmatig</b> vastleggen onder <b>Inschrijving &amp; klas</b> (bijvoorbeeld bij een papieren besluit), altijd met de <b>referentie van het examencommissie-besluit</b>. Een vrijstelling levert de volledige studiepunten (EC) op zonder cijfer (vermelding “VR”).</p>

  <h2 id="h6">6. Cijfers en aanwezigheid (Docent)</h2>
  <h3>Cijfers invoeren</h3>
  <p>Ga naar <b>Cijferinvoer</b> en kies een van uw vakken. Voer per toetsonderdeel de <b>1e poging</b> en eventueel de <b>herkansing</b> en een <b>2e herkansing</b> in (drie velden per onderdeel); van de ingevulde pogingen telt automatisch de <b>beste</b> mee. Het systeem berekent het gewogen eindcijfer en de EC. Als u klaar bent, klikt u op <b>Opslaan en indienen bij examencommissie</b>: dit slaat de cijfers eerst op en dient de lijst dan in. Daarna is de lijst vergrendeld.</p>
  <div class="tip">De knop <b>Opslaan en indienen</b> bewaart altijd eerst uw ingevoerde cijfers. U hoeft dus niet apart op <b>Cijfers opslaan</b> te klikken voordat u indient.</div>
  <p>De kolom <b>Aanwezigheid</b> toont per student het percentage; wie <b>onder de norm</b> zit krijgt een rode waarschuwing en bovenaan verschijnt een melding. Volgens de studiegids (§2.3.3) mag zo'n student formeel geen toets afleggen — het systeem <b>blokkeert dit niet</b>, maar signaleert het zodat u en de examencommissie het kunnen meewegen. Of de EC worden toegekend hangt af van het <b>EC-model</b> van de opleiding: bij <b>knock-out</b> moet elk meetellend onderdeel voldoende zijn, bij <b>compensatorisch</b> volstaat een voldoende gewogen eindcijfer (Beheer stelt dit per opleiding in). De voetnoot onder de cijfertabel vermeldt welk model geldt.</p>
  <div class="tip">U ziet en wijzigt uitsluitend uw eigen vakken. Bij een vrijstelling vervallen de invoervelden en geldt “VR”.</div>

  <h3>Aanwezigheid registreren (verplicht)</h3>
  <p>Tijdens elk college registreert u de aanwezigheid van uw studenten. <b>Dit is verplicht.</b> Een blok telt <b>acht onderwijsweken</b>. Per student en per week klikt u op een <b>vakje</b> dat wisselt tussen drie standen:</p>
  <table class="rol">
    <tr><th>Vakje</th><th>Betekenis</th></tr>
    <tr><td><b>groen &#10003;</b></td><td>De student was aanwezig.</td></tr>
    <tr><td><b>rood &#10007;</b></td><td>De student was afwezig.</td></tr>
    <tr><td><b>leeg</b></td><td>Nog niet geregistreerd. Dit telt <b>niet</b> als afwezigheid.</td></tr>
  </table>
  <p>Ga naar <b>Mijn vakken</b> en klik bij een vak op <b>Aanwezigheid</b> (of kies <b>Aanwezigheid</b> in het menu voor een overzicht van al uw vakken). U ziet een tabel met uw studenten en de acht weken. <b>Eén klik</b> op een leeg vakje zet de student op <b>aanwezig</b> (groen &#10003;); nog een klik maakt er <b>afwezig</b> (rood &#10007;) van, en een derde klik maakt het weer leeg. Met het knopje <b>alle 1</b> boven een week zet u die hele week in één keer op aanwezig; daarna klikt u alleen de afwezige studenten aan. Klik op <b>Aanwezigheid opslaan</b>. Het percentage per student wordt direct berekend.</p>
  <p>Twee dingen ziet u meteen op de lijst:</p>
  <ul>
    <li>Studenten met een <b>vrijstelling</b> voor uw vak volgen de colleges niet. Bij hen vult u <b>niets</b> in; hun rij toont “Vrijgesteld — geen aanwezigheidsplicht”.</li>
    <li>Studenten met de <b>50%-aanwezigheidsregeling</b> hebben het label <b>50%</b> achter hun naam en worden aan de <b>50%-norm</b> getoetst in plaats van 75%. De kolom <b>Norm</b> toont per student welke norm geldt.</li>
  </ul>
  <p>Op <b>Mijn vakken</b> en op uw dashboard ziet u per vak of de registratie <b>volledig</b> is. Een week telt pas als geregistreerd wanneer <b>álle</b> presentieplichtige studenten een waarde hebben. Ontbrekende weken worden expliciet benoemd. Uw dashboard toont daarnaast de gemiddelde aanwezigheid, het aantal studenten onder de norm, en grafieken per vak.</p>
  <div class="tip">De aanwezigheidslijst is te <b>printen</b> (knop <b>Printen</b>), bijvoorbeeld om hem tijdens het college op papier bij te houden. Verwar deze lijst niet met de <b>presentielijst voor tentamens</b> (met handtekeningvak), die u vindt onder <b>Tentamenlijst</b>.</div>

  <h2 id="h7">7. Cijfers vaststellen &amp; lijsten (Examencommissie/Directie)</h2>
  <p>In <b>Cijferoverzicht</b> ziet u alle vakken met status. Klik bij een ingediende lijst op <b>Beoordelen</b> om de ingevoerde cijfers te zien. Een ingediende lijst kunt u <b>vaststellen</b> (knop <b>Opslaan en vaststellen</b> — eventuele correcties worden daarbij eerst opgeslagen) of met een opmerking <b>terugsturen</b> naar de docent. Per vak downloadt u een <b>presentielijst</b>: een tentamenlijst om <b>tijdens het tentamen</b> te gebruiken, met per student een vak voor de <b>handtekening</b> (aanwezigheidsbevestiging). Deze lijst bevat bewust <b>geen cijfers of studiepunten</b> — die privé-informatie mag niet zichtbaar zijn voor medestudenten. Per student maakt u via <b>Cijferlijst</b> een officieel transcript (mét cijfers). Beide zijn te printen (knop <b>Printen</b>) en als ondertekende PDF te downloaden. Directie ziet hierbij alleen de vakken en studenten van de eigen opleiding(en).</p>
  <p><b>Vrijstelling voorstellen:</b> op het dossier van een student (tabblad <b>Inschrijving &amp; klas</b>) legt u een vrijstellingsbesluit vast en stuurt u het met <b>Naar Studentenzaken sturen</b> door. Studentenzaken verwerkt het; u ziet de status (openstaand/verwerkt) terug op het dossier en kunt een openstaand besluit annuleren.</p>
  <p><b>Aanwezigheid:</b> via het menu-item <b>Aanwezigheid</b> opent u het <b>aanwezigheidsoverzicht</b>: per vak de docent, het aantal deelnemers, of de registratie volledig is, de gemiddelde aanwezigheid en hoeveel studenten onder hun norm zitten. Klik op <b>Aanwezigheidslijst</b> voor de lijst per week. U kijkt alleen mee — registreren doet uitsluitend de docent van het vak. Directie ziet alleen de eigen opleiding(en). Zo is zichtbaar of docenten de verplichte registratie bijhouden en hoe de aanwezigheid zich per opleiding ontwikkelt.</p>
  <p><b>Resultaten mailen (einde blok):</b> in <b>Cijferlijst</b> kiest u onderaan een opleiding om alle studenten te zien. Met <b>Definitieve resultaten mailen</b> komt u op een controlescherm dat toont wie een e-mail krijgt en wie wordt overgeslagen (geen vastgestelde resultaten of geen e-mailadres). Na bevestiging ontvangt <b>elke student individueel</b> zijn/haar eigen officiële cijferlijst als PDF-bijlage. Alleen door de examencommissie vastgestelde resultaten worden verstuurd; de verzending wordt gelogd.</p>

  <h3>Historisch dossier (oude cijfers uit Access)</h3>
  <p>Onder <b>Cijfers &rarr; Historisch dossier</b> vindt u de cijferlijsten van studenten die zijn overgezet uit het oude Access-systeem (tot en met studiejaar 2024&ndash;2025). Zoek op studentnummer of naam en open de <b>cijferlijst</b>: die toont per <b>studiejaar</b> de vakken met eindcijfer, resultaat (voldoende / onvoldoende / vrijstelling) en behaalde EC. Deze schermen zijn <b>alleen-lezen</b>; de oude cijfers stonden op een 0&ndash;100-schaal en zijn omgezet naar 0&ndash;10 (voldoende vanaf 5,5). Het oude systeem kende geen deeltoetsen, dus er is per vak één eindcijfer. Met de knop <b>Printbare PDF</b> downloadt u de cijferlijst als A4-document om te printen of te archiveren; die is duidelijk gemarkeerd als <b>informatief, niet gewaarmerkt</b> (de oude cijfers zijn niet opnieuw door de examencommissie vastgesteld). Toegang: <b>Examencommissie</b>, <b>Directie</b> en <b>Beheer</b> (niet Studentenzaken &mdash; rolscheiding op cijfers). Inzage en het afdrukken worden gelogd.</p>
  <p>Voor een <b>bulk-export</b> staat op het lijstscherm het blok <b>Bulk-export (PDF)</b>. Kies een <b>studiejaar</b> voor één gecombineerd cijferoverzicht van alle studenten van dat jaar (bij veel studenten opgesplitst in delen, samen als ZIP), of <b>Hele opleiding</b> voor een ZIP met per studiejaar een overzicht &mdash; dat laatste kan enkele minuten duren. Ook deze documenten zijn informatief en niet gewaarmerkt.</p>

  <h2 id="h8">8. Collegegeld &amp; betalingen</h2>
  <h3>Termijnen: vijf facturen per jaar</h3>
  <p>Het collegegeld wordt elke twee maanden gefactureerd: in <b>september, november, januari, maart en mei</b>. Elke termijn is het jaarbedrag gedeeld door vijf; een afrondingsverschil van enkele centen komt op de laatste termijn, zodat de som exact het jaarbedrag is.</p>
  <p>De <b>factuur</b> gaat op de <b>14e</b> van de vervalmaand naar de student; die heeft daarna <b>10 dagen</b> om te betalen. De <b>vervaldatum</b> van een termijn valt dus op de <b>24e</b> van de maand. Een onbetaalde termijn telt pas ná die datum als achterstallig.</p>
  <p>Op het studentdossier (kaart <b>Collegegeld</b>) staat een tabel met alle termijnen: vervaldatum, bedrag, betaald, openstaand en de status. Zo ziet u in één oogopslag welke termijn wel en niet is voldaan.</p>
  <table class="rol">
    <tr><th>Status</th><th>Betekenis</th></tr>
    <tr><td><b>Betaald</b></td><td>De termijn is volledig voldaan.</td></tr>
    <tr><td><b>Achterstallig</b></td><td>De vervaldatum is verstreken en de termijn is niet (volledig) betaald. Dit bepaalt de betalingsachterstand.</td></tr>
    <tr><td><b>Deels betaald</b></td><td>Er is een deelbetaling gedaan, maar de vervaldatum is nog niet verstreken.</td></tr>
    <tr><td><b>Nog niet vervallen</b></td><td>De vervaldatum ligt in de toekomst. Dit is <b>geen</b> achterstand.</td></tr>
    <tr><td><b>Vervallen</b></td><td>De student is uitgeschreven vóór deze vervaldatum; er wordt niet meer gefactureerd.</td></tr>
  </table>
  <div class="tip">Een student heeft pas een <b>betalingsachterstand</b> wanneer een <b>vervallen</b> termijn niet is voldaan. Dat een student in oktober nog € 3.200 openstaan heeft voor de rest van het jaar is dus geen achterstand — die termijnen moeten immers nog vervallen. Bij een echte achterstand worden herinschrijven en verklaringen geblokkeerd.</div>

  <h3>Eén factuur voor het hele jaar</h3>
  <p>Wil een student het volledige jaarbedrag in één keer betalen, dan legt <b>Studentenzaken</b> dat vast op het dossier onder <b>Collegegeld &rarr; Betaalregeling</b>: kies <b>Eén factuur (volledig)</b> en klik op <b>Opslaan</b>. Er ontstaat dan één termijn die op 24 september vervalt. De keuze staat ook in het inschrijfformulier. De regeling hangt aan de <b>inschrijving</b> en geldt dus per studiejaar: bij herinschrijving stelt u haar opnieuw vast. Elke wijziging wordt gelogd.</p>

  <h3>Betalingen boeken (Financiële Administratie)</h3>
  <p>Op het financiële scherm van een student staat per studiejaar hetzelfde termijnoverzicht, met achter elke openstaande termijn de knop <b>Boek € …</b>. Eén klik boekt die termijn volledig op de datum van vandaag. Voor een deelbetaling of een afwijkend bedrag gebruikt u het formulier <b>Betaling registreren</b>; daar kiest u de termijn, of laat u <b>automatisch</b> staan — dan gaat de betaling naar de <b>oudste openstaande</b> termijn.</p>
  <p>Bij de <b>bulk-import</b> (CSV) is er een extra, optionele kolom <b>termijn</b> (1 t/m 5). Laat u die leeg, dan wordt de betaling automatisch toegerekend. Bestaande bestanden zonder termijnkolom blijven gewoon werken: de kolommen worden op naam herkend.</p>

  <h3>Twee opleidingen: elk een eigen rekening</h3>
  <p>Collegegeld wordt <b>per opleiding</b> geheven. Volgt een student twee opleidingen, dan heeft <b>elke inschrijving</b> een eigen jaartarief, een eigen termijnschema en eigen facturen. De bedragen tellen op; het totaal ziet u bovenaan het financiële scherm en op het studentdossier.</p>
  <p>Op de tweede opleiding kan <b>Studentenzaken</b> een <b>korting</b> vastleggen. Dat gebeurt op het dossier, in de kaart <b>Collegegeld</b>, onder <b>Korting op &lt;opleiding&gt;</b>: vul het percentage in (0 t/m 100) en een <b>reden</b> — die is verplicht zodra u korting geeft, want er wordt minder gefactureerd dan het tarief. Alle wijzigingen worden gelogd. Het systeem beslist nooit zelf welke opleiding “de tweede” is; wat u invult, is wat er gefactureerd wordt.</p>
  <table class="rol">
    <tr><th>Voorbeeld</th><th>Bedrag</th></tr>
    <tr><td>ISLTH, jaartarief</td><td>&euro; 4.000,00</td></tr>
    <tr><td>PABO, jaartarief &euro; 2.530,00 met 50% korting</td><td>&euro; 1.265,00</td></tr>
    <tr><td><b>Totaal verschuldigd dit studiejaar</b></td><td><b>&euro; 5.265,00</b></td></tr>
  </table>
  <div class="tip">Bij 100% korting ontstaan er geen facturen voor die opleiding. Een <b>achterstand bij één van de twee</b> opleidingen blokkeert herinschrijven en verklaringen: de student heeft dan een schuld aan de instelling. De boekhouding boekt elke betaling op de opleiding waar zij bij hoort; geld wordt nooit tussen opleidingen verschoven.</div>

  <h3>Betalingsafspraak: blokkade tijdelijk opheffen</h3>
  <p>Bij een betalingsachterstand kan Studentenzaken <b>geen verklaring afgeven</b> en de student <b>niet herinschrijven</b>. Maakt de student een afspraak om alsnog te betalen, dan legt de <b>Financiële Administratie</b> die afspraak vast op het financiële scherm van de student, in de kaart <b>Betalingsafspraak</b>: vul in <b>vóór welke datum</b> betaald wordt en <b>wat er is afgesproken</b>. Beide zijn verplicht.</p>
  <p>Zolang de afspraak loopt vervallen <b>beide blokkades</b>: verklaringen en herinschrijven zijn weer mogelijk. De <b>schuld verdwijnt niet</b> — het achterstallige bedrag blijft op het dossier staan, met de melding dat er een afspraak loopt en tot wanneer.</p>
  <table class="rol">
    <tr><th>Situatie</th><th>Verklaring / herinschrijven</th></tr>
    <tr><td>Achterstand, geen afspraak</td><td><b>Geblokkeerd</b></td></tr>
    <tr><td>Achterstand, lopende afspraak</td><td>Toegestaan</td></tr>
    <tr><td>Afspraak verlopen, nog niet betaald</td><td><b>Geblokkeerd</b> (automatisch)</td></tr>
    <tr><td>Afspraak ingetrokken, nog niet betaald</td><td><b>Geblokkeerd</b></td></tr>
    <tr><td>Schuld voldaan</td><td>Toegestaan</td></tr>
  </table>
  <div class="tip">Na de einddatum keert de blokkade <b>vanzelf</b> terug als er niet is betaald; u hoeft niets te doen. Legt u een nieuwe afspraak vast terwijl er al één loopt, dan wordt de oude automatisch ingetrokken — er is altijd hoogstens één geldende afspraak. Op het dashboard van de Financiële Administratie staat het venster <b>Lopende betalingsafspraken</b> met de einddatum en het aantal resterende dagen.</div>
  <div class="let">Alleen de <b>Financiële Administratie</b> (en Beheer) kan een afspraak vastleggen of intrekken. Studentenzaken kan dat bewust niet: anders zou de rol die de verklaring wil afgeven ook de betaalblokkade kunnen wegnemen. Vastleggen en intrekken worden gelogd.</div>

  <h3>Een betaling corrigeren of verwijderen</h3>
  <p>Staat er een betaling verkeerd geboekt, dan herstelt de <b>Financiële Administratie</b> dat zelf. Klik in de lijst <b>Geregistreerde betalingen</b> op <b>Wijzigen</b>: u past opleiding, termijn, bedrag, datum, betaalwijze en opmerking aan. Met <b>Verwijderen</b> haalt u een betaling helemaal weg, na een bevestiging.</p>
  <div class="let">Beide handelingen worden <b>gelogd</b> in de audit-log, met de <b>oude én de nieuwe waarden</b> en de naam van degene die het deed. Zo blijft elke mutatie op een geldbedrag herleidbaar. Alleen de Financiële Administratie en Beheer kunnen dit; Studentenzaken niet.</div>

  <h3>Tussentijdse uitschrijving</h3>
  <p>Schrijft een student zich halverwege uit, dan is hij alleen de verstreken maanden verschuldigd (jaarbedrag ÷ 12 × maanden, t/m het einde van de uitschrijfmaand). De termijnen ná de uitschrijfdatum krijgen de status <b>Vervallen</b> en de laatste nog geldende termijn wordt naar beneden bijgesteld. Is er meer betaald dan verschuldigd, dan verschijnt de student op het Financiën-overzicht onder <b>terugbetalingen</b>.</p>

  <h2 id="h9">9. Verklaringen &amp; ondertekende documenten</h2>
  <p>Bij <b>Verklaring opstellen</b> genereert u bewijzen (bv. bewijs van inschrijving) op officieel briefpapier, digitaal gewaarmerkt met een verificatiecode. In <b>Ondertekende documenten</b> vindt u uw eigen gewaarmerkte documenten terug; u kunt ook zelf een PDF uploaden en laten waarmerken. Echtheid is te controleren op de publieke verificatiepagina.</p>

  <h2 id="h10">10. Rapporten</h2>
  <p>Onder <b>Rapporten</b> maakt u o.a. de klassenlijst, het alumni-rapport, een Excel-export van actieve studenten (met IBAN, zonder BSN), het EC-rapport, het overgangsadvies en de cijfer-/tentamenlijsten. Elke lijst heeft een zoekbalk.</p>
  <p>Het <b>alumni-rapport</b> (afgestudeerde studenten met hun contactgegevens) is toegankelijk voor <b>Studentenzaken</b>, de <b>Examencommissie</b>, de <b>Directie</b> en het <b>Schoolbestuur</b>. Het bevat geen cijfers en geen BSN. Directie ziet alleen de alumni van de eigen opleiding(en); de overige rollen zien ze allemaal. De Examencommissie en het Schoolbestuur vinden de lijst in het menu onder <b>Rapporten &rarr; Alumni</b>.</p>
  <div class="tip"><b>Snelkoppeling Vrijstelling (Examencommissie).</b> In het menu van de Examencommissie staat onder <b>Studenten</b> de knop <b>Vrijstelling</b>. Die brengt u direct naar de studentenlijst met de melding om een student te kiezen; klikt u vervolgens op <b>Openen</b>, dan springt u meteen naar het <b>vrijstellingsformulier</b> op het dossier. Zo legt u sneller een vrijstellingsbesluit vast dan via de gewone studentenlijst.</div>

  <h2 id="h11">11. Cursussen Administratie (aparte module)</h2>
  <p>Naast Studentenzaken is er de module <b>Cursussen Administratie</b> voor de cursussen die buiten Studentenzaken vallen. U opent haar via het <b>modulekeuzescherm</b> (rechtsboven <b>Modules</b>). De toegang is per rol verdeeld: een <b>cursusdirecteur</b> (rol Cursusadministratie) beheert uitsluitend de <b>eigen cursus(sen)</b>; de <b>Financiële Administratie</b> (boekhouding) ziet de cursusgelden van alle cursussen; het <b>Schoolbestuur</b> kijkt mee (dashboard/statistieken en cursisten, alleen-lezen); de <b>Beheerder</b> ziet en doet alles.</p>
  <h3>Cursusdirecteuren (toegang per cursus)</h3>
  <p>Elke cursus heeft een <b>directeur</b>. Die directeur ziet en beheert op het dashboard, in het cursusbeheer en in het cursistenoverzicht <b>alleen zijn eigen cursus(sen)</b> en de cursisten die daarop zijn ingeschreven — niet die van andere cursussen. Op een cursistdossier ziet een directeur alleen de inschrijving(en) op de eigen cursus. Zo blijft de administratie van elke cursus gescheiden (need-to-know).</p>
  <p>Het <b>toewijzen van een directeur</b> aan een cursus, en het <b>aanmaken of verwijderen</b> van een cursus, doet uitsluitend de <b>Beheerder</b> (via het veld <i>Cursusdirecteur</i> op het cursusformulier). Een cursusdirecteur kan zichzelf dus geen extra cursussen geven; hij mag wel de gegevens van de eigen cursus wijzigen. De Financiële Administratie en het Schoolbestuur zijn niet cursusgebonden: zij zien alle cursussen.</p>
  <p><b>Een cursus kopiëren.</b> Wilt u een nieuwe cursus starten die sterk lijkt op een bestaande (bijvoorbeeld volgend jaar een cursus <i>Turkse Taal</i> naar het voorbeeld van <i>Arabische Taal</i>), gebruik dan in het Cursusbeheer de knop <b>Kopiëren</b> achter de broncursus (alleen Beheerder). Het cursusformulier verschijnt dan al ingevuld met het cursusgeld, de omschrijving, de looptijd en de directeur van de broncursus. U geeft alleen een <b>nieuwe, unieke cursuscode</b> en past de naam aan, en klikt op Opslaan — het systeem maakt dan een nieuwe cursus aan. De cursisten van de broncursus worden bewust <b>niet</b> meegekopieerd; de nieuwe cursus begint leeg.</p>
  <h3>Cursussen</h3>
  <p>Onder <b>Cursusbeheer</b> staan de cursussen met hun cursusgeld. De huidige cursussen zijn <b>Arabische Taal</b> (€ 265), <b>Hifz Programma</b> (€ 330) en <b>Certificaatprogramma / Ijaaza</b> (€ 430). Nieuwe cursussen en tarieven voegt u hier gewoon toe; een cursus met inschrijvingen kunt u niet verwijderen (historie) maar wel op inactief zetten.</p>
  <h3>Cursisten</h3>
  <p>Cursisten staan los van de studenten en krijgen een eigen <b>cursistnummer</b> (bijv. C260001). U voegt ze <b>handmatig</b> toe of in <b>bulk</b> via een Excel- of CSV-bestand. Bij de bulk-import mag u een kolom <b>cursuscode</b> meegeven; staat daar een geldige code, dan wordt de cursist meteen op die cursus ingeschreven. Zoals altijd ziet u eerst een controlescherm voordat er iets wordt opgeslagen.</p>
  <h3>Inschrijven</h3>
  <p>Op het dossier van een cursist schrijft u hem in op een cursus. Het <b>cursusgeld</b> wordt als momentopname vastgelegd, zodat een latere tariefwijziging bestaande inschrijvingen niet verandert. De status van een inschrijving (aangemeld, actief, afgerond, geannuleerd) past u daar ook aan.</p>
  <h3>Cursusgelden (boekhouding)</h3>
  <p>De <b>Financiële Administratie</b> opent binnen de module de pagina <b>Cursusgelden</b>. Daar staat per inschrijving het cursusgeld, het reeds betaalde bedrag en het openstaande saldo, met een status <b>Voldaan</b>, <b>Deels betaald</b> of <b>Openstaand</b>. U kunt filteren op cursus, op status en zoeken op cursistnummer of naam.</p>
  <p>Via <b>Beheer</b> bij een inschrijving registreert u een betaling: <b>bedrag</b>, <b>datum</b>, <b>betaalmethode</b> (iDEAL/online, bankoverschrijving of contant) en <b>status</b>. Alleen betalingen met status <b>Betaald</b> tellen mee voor het voldane bedrag; een betaling <i>in afwachting</i>, <i>mislukt</i> of <i>terugbetaald</i> telt niet mee. Bestaande betalingen kunt u <b>wijzigen</b> of <b>verwijderen</b>; elke wijziging en verwijdering wordt gelogd. Een cursist mag het cursusgeld ook in delen betalen — de deelbetalingen worden bij elkaar opgeteld.</p>
  <p>De cursusadministratie ziet de betaalstatus op het cursistdossier alleen ter informatie; het registreren en corrigeren van betalingen is voorbehouden aan de boekhouding.</p>
  <h3>Rapportage</h3>
  <p>Onder <b>Rapportage</b> (op het cursusdashboard of in het menu) staat een overzicht per cursus: het aantal inschrijvingen uitgesplitst naar status (aangemeld, actief, afgerond, geannuleerd) en de cursusgelden — verschuldigd, betaald, openstaand en de betaalgraad — met grafieken (inschrijvingen en openstaand per cursus, en de verdeling naar betaalmethode). Een <b>cursusdirecteur</b> ziet alleen de eigen cursus(sen); de Financiële Administratie, de Beheerder en het Schoolbestuur zien alle cursussen. Met de knop <b>Exporteren (CSV)</b> haalt u een lijst op één regel per cursist op (te openen in Excel). Ook op het <b>dashboard</b> ziet u nu in één oogopslag de betaalgraad en het openstaande cursusgeld. Het Schoolbestuur bereikt dit overzicht ook via de knop <b>Cursusrapport</b> op de Bestuurspagina.</p>
  <div class="tip">De cursusadministratie is een aparte administratie met een lichter regime: geen BSN of DUO-gegevens. Belangrijke acties (cursus/cursist aanmaken, inschrijven, importeren, betaling registreren/wijzigen/verwijderen) worden gelogd.</div>

  <h2 id="h12">12. Relatiebeheer &amp; Stage (aparte module)</h2>
  <p>De module <b>Relatiebeheer &amp; Stage</b> beheert de externe relaties van de hogeschool: <b>stagescholen</b> en <b>werkveldorganisaties</b> (zoals basisscholen en schoolbesturen voor de PABO, zorginstellingen en justitiële inrichtingen voor de Master IGV, en moskeeën en maatschappelijke organisaties voor de Bachelor Islamitische Theologie). U opent haar via het <b>modulekeuzescherm</b> (rechtsboven <b>Modules</b>). De module is <b>opleidingoverstijgend</b>: dezelfde functies gelden voor elke opleiding, maar de organisatietypes zijn per opleiding in te stellen.</p>
  <p>De toegang is per rol verdeeld: de <b>Relatiebeheerder</b> en de <b>Stagecoördinator</b> beheren de organisaties van de <b>eigen opleiding(en)</b>; de <b>Directie</b> (opleidingsmanager) en het <b>Schoolbestuur</b> kijken mee (alleen-lezen); de <b>Beheerder</b> ziet en doet alles. De zichtbaarheid is <b>opleidinggebonden</b>: u ziet uitsluitend de relaties van de opleiding(en) waaraan u bent gekoppeld. Op het <b>Overzicht</b> (het startscherm van de module) staat bovenaan aangegeven welke <b>opleiding(en)</b> aan u zijn gekoppeld.</p>
  <h3>Organisaties</h3>
  <p>Onder <b>Organisaties</b> staat de lijst met alle relaties die u mag zien, met een filterbalk (zoeken op naam/plaats/relatienummer, filteren op type, opleiding en status). Elke organisatie krijgt automatisch een uniek, leesbaar <b>relatienummer</b> (bijvoorbeeld R260001). U legt de naam, het type, KvK- en BRIN-nummer, het adres, de contactgegevens en de opleiding(en) vast. Een organisatie wordt nooit verwijderd (historie); zet haar desgewenst op <b>inactief</b>.</p>
  <h3>Contactpersonen</h3>
  <p>Op de <b>relatiekaart</b> (het detailscherm van een organisatie) staat het paneel <b>Contactpersonen</b>. Elke organisatie kan één of meer contactpersonen hebben; per persoon legt u de naam, functie, afdeling, e-mail, telefoon/mobiel, het voorkeurskanaal (e-mail, telefoon of Teams) en eventueel LinkedIn vast. U voegt een contactpersoon toe met de knop <b>Contactpersoon toevoegen</b> en bewerkt of <b>inactiveert</b> hem via de knoppen achter de regel — verwijderen doet u niet (historie). Wie de organisatie mag beheren, mag ook haar contactpersonen beheren; het aanmaken en wijzigen wordt gelogd.</p>
  <h3>Contactmomenten</h3>
  <p>Onder <b>Contactmomenten</b> op de relatiekaart legt u elke interactie met de relatie vast: een <b>telefoongesprek</b>, <b>e-mail</b>, <b>Teams</b>-overleg, <b>bezoek</b>, <b>stagebezoek</b>, overleg, klacht of evaluatie. Per contactmoment kiest u het type, eventueel de betrokken contactpersoon, de datum en tijd, een onderwerp en een samenvatting, en optioneel een <b>vervolgdatum</b> voor de afgesproken opvolging. Contactmomenten zijn historische records: u kunt ze corrigeren maar niet verwijderen. De soorten contactmoment beheert de Beheerder via Opzoektabellen.</p>
  <h3>Notities</h3>
  <p>Onder <b>Notities</b> plaatst u vrije aantekeningen bij de organisatie, met een optionele categorie en tags. Een notitie kunt u weer verwijderen.</p>
  <h3>Historie / tijdlijn</h3>
  <p>De <b>tijdlijn</b> onderaan de relatiekaart bundelt automatisch alle gebeurtenissen — contactmomenten, notities en de vastgelegde wijzigingen aan de organisatie en haar contactpersonen — chronologisch, met datum en medewerker. Zo ziet u in één oogopslag de volledige geschiedenis van de samenwerking.</p>
  <h3>Stageplaatsen</h3>
  <p>Onder <b>Stageplaatsen</b> op de relatiekaart legt u het <b>aanbod</b> van een organisatie vast: per opleiding (en eventueel leerjaar/studiejaar) het aantal plaatsen, een maximum, de werkdagen, specialisaties en eisen. Bij elke plaats ziet u de actuele <b>bezetting</b> (aantal geplaatste studenten t.o.v. het maximum). Stageplaatsen beheert de <b>Stagecoördinator</b> (voor de eigen opleiding) en de Beheerder.</p>
  <h3>Stages (studenten plaatsen)</h3>
  <p>Met de knop <b>Student plaatsen</b> koppelt u een student aan de organisatie: u <b>zoekt de student op</b> in het veld <b>Student</b> — typ een deel van het <b>studentnummer of de naam</b> en kies uit de lijst die meeloopt (met honderden studenten is doorbladeren geen doen; kent u het nummer uit uw hoofd, dan volstaat dat alleen). U ziet uitsluitend studenten met een actieve inschrijving in een opleiding van deze organisatie waarvoor u bevoegd bent. Verder kiest u de opleiding, de <b>stageperiode</b>, eventueel een specifieke stageplaats, de <b>stagebegeleider</b> vanuit de opleiding en de <b>werkplekbegeleider</b> op de locatie (een contactpersoon), de periode en de status (aangevraagd, lopend, afgerond, afgebroken). Elke stage krijgt een uniek <b>stagenummer</b>. Alle stages samen ziet u ook via het menu <b>Stages</b>, met filters op status en opleiding.</p>
  <p>De <b>stageperiode</b> is de stage binnen het curriculum van de opleiding, met een vaste <b>urennorm</b>. Voor de <b>Bachelor Islamitische Theologie</b> zijn dat er drie: <b>Verkennende stage</b> (jaar 2, 140 uur), <b>Stage 1</b> (jaar 3, 280 uur) en <b>Grote Stage 2</b> (jaar 4, 560 uur). Voor de <b>Master Islamitische Geestelijke Verzorging</b> zijn er twee: <b>Snuffelstage</b> (40 uur) en <b>Grote stage</b> (480 uur). Zodra u de opleiding kiest, verschijnen automatisch de bijbehorende stageperioden; heeft een opleiding perioden, dan is de keuze verplicht. Het veld <b>Gemaakte uren</b> wordt voorgevuld met de urennorm en is aan te passen. De stageperioden (ook voor andere opleidingen zoals PABO) beheert de Beheerder via <b>Opzoektabellen &rarr; Stageperioden</b>.</p>
  <p>Elke stageperiode hoort bij een <b>leerjaar</b> (de Verkennende stage bij jaar 2, Stage 1 bij jaar 3, enzovoort). Kiest u een stageperiode, dan toont de studentenlijst <b>alleen de studenten van dat leerjaar</b>, zodat u niet per ongeluk een student uit een ander jaar plaatst. Legt u tóch bewust een student van een ander leerjaar vast (bijvoorbeeld een vertraagde student die de stage inhaalt), dan mag dat, maar verschijnt een <b>waarschuwing</b> — bij het typen en na het opslaan. Stageperioden zonder leerjaar (de masterstages) kennen deze controle niet.</p>
  <p>Bij het bewerken van een stage legt u de <b>beoordeling</b> vast: <b>voldoende</b> of <b>onvoldoende</b>, met een optionele toelichting. Let op: de beoordeling gaat over de student en wordt gelogd — leg alleen de formeel vastgestelde uitslag vast.</p>
  <h3>Taken</h3>
  <p>Onder <b>Taken</b> op de relatiekaart houdt u de werkverdeling bij: geef een taak een titel, wijs haar toe aan een medewerker (of laat haar vrij op te pakken), stel een prioriteit en een vervaldatum in. Een taak vinkt u met één klik af (of heropent u). Een taak waarvan de vervaldatum verstreken is en die nog niet is afgerond, wordt gemarkeerd als <b>Te laat</b>. Taken zijn werkinformatie en worden niet apart gelogd.</p>
  <h3>Agenda</h3>
  <p>Onder <b>Agenda</b> plant u afspraken bij de organisatie: <b>schoolbezoek</b>, <b>stagebezoek</b>, <b>evaluatie</b>, <b>overleg</b> of <b>open dag</b>, met datum, tijd, locatie en een status (gepland, afgerond, geannuleerd). Een afspraak kunt u aan een specifieke stage koppelen.</p>
  <h3>Agenda &amp; taken (planning)</h3>
  <p>Via het menu <b>Agenda &amp; taken</b> ziet u een overzicht over alle organisaties binnen uw bereik: de <b>aankomende afspraken</b> en de <b>openstaande taken</b> (met vervaldatum en de markering ‘te laat’). Zo hebt u uw werkvoorraad in één scherm.</p>
  <h3>Overeenkomsten</h3>
  <p>Onder <b>Overeenkomsten</b> op de relatiekaart legt u samenwerkingsovereenkomsten, convenanten en stagecontracten vast, met een start- en een <b>verloopdatum</b> en een status (concept, getekend, verlopen, opgezegd). U kunt een <b>getekende PDF</b> uploaden: die krijgt automatisch een SHA-256-echtheidskenmerk en een verificatiecode via de ondertekenmodule en de status wordt dan ‘Getekend’; het gewaarmerkte document is daarna te downloaden. Overeenkomsten waarvan de verloopdatum nadert of verstreken is, verschijnen op de pagina <b>Agenda &amp; taken</b> onder ‘Contracten die verlopen’.</p>
  <h3>Documenten</h3>
  <p>Onder <b>Documenten</b> uploadt u bestanden bij de organisatie (stagecontract, convenant, beoordeling, verslag, correspondentie, foto, certificaat of overig). De bestanden staan op de <b>private schijf</b> (buiten het web) en de inzage wordt gelogd (AVG). Met <b>Nieuwe versie</b> vervangt u een document terwijl de oude versie bewaard blijft (versiebeheer); verwijderen kan ook.</p>
  <h3>Overzicht (dashboard) en Rapportage</h3>
  <p>De module opent op een <b>Overzicht</b> met kerncijfers en signaleringen: aantal organisaties en contactpersonen, stageplaatsen en <b>bezettingsgraad</b>, lopende stages en het percentage <b>voldoende</b>, te beoordelen stages, open taken, aankomende bezoeken, aflopende contracten en nieuwe documenten — met grafieken (stages per status, organisaties per type) en een lijst ‘te beoordelen stages’. Onder <b>Rapportage</b> staat een overzicht per organisatie (contactpersonen, stageplaatsen, lopende stages, open taken) dat u met één klik als <b>CSV</b> exporteert (te openen in Excel). Alle cijfers zijn beperkt tot de opleiding(en) waarvoor u bevoegd bent.</p>
  <h3>Slimme functies</h3>
  <p><b>Zoeken.</b> Via het menu <b>Zoeken</b> doorzoekt u in één keer alle organisaties, contactpersonen en stages binnen uw bereik (op naam, plaats, relatienummer, e-mail, functie, stagenummer of student).</p>
  <p><b>Agenda exporteren.</b> Op de pagina <b>Agenda &amp; taken</b> downloadt u met de knop <b>Exporteren naar agenda (.ics)</b> uw aankomende afspraken als een standaard agendabestand, dat u kunt importeren in Outlook, Google Agenda of Apple Agenda. (Een automatische, doorlopende Outlook-koppeling valt bewust buiten dit interne systeem.)</p>
  <p><b>Contactmoment → taak.</b> Heeft een contactmoment een vervolgdatum, dan maakt u er met de knop <b>→ Taak</b> in één klik een opvolgtaak van, met dezelfde vervaldatum.</p>
  <div class="tip">Belangrijk (AVG): in deze module leggen wij uitsluitend gegevens van de <b>organisatie</b> en haar contactpersonen vast — nooit gegevens van leerlingen of cliënten van de stageplaats. De organisatietypes beheert de Beheerder via Opzoektabellen (per opleiding instelbaar). Het aanmaken en wijzigen van organisaties wordt gelogd.</div>

  <h2 id="h13">13. HR / Personeelszaken (aparte module)</h2>
  <p>De module <b>HR / Personeelszaken</b> is de personeelsadministratie. U opent haar via het <b>modulekeuzescherm</b>. Toegang: de <b>HR-medewerker</b> doet de volledige administratie én is tevens leidinggevende — bij IUASR zijn dit dezelfde persoon, daarom is dit <b>één gecombineerde rol</b> die alle medewerkers ziet en het verlof goedkeurt. Het <b>Schoolbestuur</b> kijkt instellingsbreed mee (alleen-lezen); de <b>Beheerder</b> ziet en doet alles.</p>
  <h3>Zoeken</h3>
  <p>Via het menu <b>Zoeken</b> doorzoekt u in één keer alle <b>medewerkers</b> (op naam, personeelsnummer of e-mail) en <b>afdelingen</b> binnen uw bereik. Vul minimaal twee tekens in; u klikt vanuit de resultaten direct door naar de medewerkerkaart of de organisatiestructuur.</p>
  <h3>Medewerkers</h3>
  <p>Onder <b>Medewerkers</b> staat de personeelslijst met filters (afdeling, functie, status) en zoeken. Elke medewerker krijgt een uniek <b>personeelsnummer</b> (bijv. P260001). Op de <b>medewerkerkaart</b> legt u de persoons- en contactgegevens vast, de functie, afdeling en leidinggevende, en optioneel een koppeling aan een <b>login</b> voor self-service. Het <b>BSN</b> is een beschermd veld: het staat standaard uit en wordt pas na akkoord van de Functionaris Gegevensbescherming ingeschakeld (versleuteld opgeslagen, inzage gelogd).</p>
  <p><b>Foutief of dubbel aangemaakt?</b> Onderaan de medewerkerkaart staat <b>Medewerker volledig verwijderen</b>. Dit verwijdert de medewerker en alle gekoppelde HR-gegevens (dienstverbanden, verlof, verzuim, documenten, notities, gesprekken) <b>onherstelbaar</b>; een eventueel gekoppeld login-account blijft bestaan. Ter beveiliging typt u eerst het <b>personeelsnummer</b> ter bevestiging. De verwijdering wordt gelogd. Bedoeld voor correcties (zoals een per ongeluk dubbel aangemaakte medewerker) — voor een medewerker die uit dienst gaat, gebruikt u de status <b>Uit dienst</b> in plaats van verwijderen.</p>
  <h3>Soort (profiel): personeel, vrijwilliger of ZZP</h3>
  <p>IUASR is een stichting met naast betaald personeel ook veel <b>vrijwilligers</b> en <b>ZZP’ers/freelancers</b>. Op de medewerkerkaart kiest u bij <b>Soort</b> tussen <b>Personeel</b>, <b>Vrijwilliger</b> en <b>ZZP / freelancer</b>. Dit is een <b>profiel en staat los van de functie</b>: een vrijwilliger kan bijvoorbeeld <i>kok</i>, <i>schoonmaker</i> of <i>gastvrouw</i> zijn, een ZZP’er <i>trainer</i> of <i>ICT-consultant</i>. Vrijwilligers en ZZP’ers worden volwaardig geregistreerd (contactgegevens, functie, documenten), maar tellen <b>niet mee in de FTE</b> en de personeelsformatie: hun FTE blijft leeg, ook als er uren zijn vastgelegd. Op het dashboard en in het HR-rapport staan zij <b>apart geteld</b> (‘X vrijwilligers · Y zzp’) en het <b>Totaal FTE</b> is exclusief deze profielen. In de medewerkerslijst filtert u op soort en herkent u het profiel aan het label achter de naam.</p>
  <p>Het <b>contract of de overeenkomst bewaart</b> u bij <b>Documenten</b> op de medewerkerkaart. Kies daar de passende categorie: <b>Arbeidscontract</b> (personeel), <b>Vrijwilligersovereenkomst</b> of <b>ZZP-/opdrachtovereenkomst</b>. De bestanden staan op de private schijf en de inzage wordt gelogd (AVG).</p>
  <h3>Dienstverband &amp; FTE</h3>
  <p>Per medewerker legt u één of meer <b>dienstverbanden</b> vast (vast/tijdelijk, start- en einddatum, uren per week, functie, afdeling). De <b>FTE</b> wordt automatisch berekend: uren per week ÷ {{ (int) config('sis.hr.voltijd_uren', 40) }} (de voltijdsnorm). Het dashboard toont het totaal aantal medewerkers, de totale FTE, de statusverdeling en de contracten die binnen 60 dagen aflopen.</p>
  <h3>Uitdiensttreding (offboarding)</h3>
  <p>Zet u de <b>status</b> van een medewerker op <b>Uit dienst</b>, dan verschijnt op de medewerkerkaart een verplichte <b>Uit-dienstdatum</b> (laatste werkdag) en een optionele <b>reden</b> (bv. eigen verzoek, einde contract, pensioen). Bij het opslaan gebeurt automatisch het volgende: de medewerker wordt op <b>niet-actief</b> gezet, en het <b>lopende dienstverband</b> wordt afgesloten op de uit-dienstdatum. Dat laatste is vooral belangrijk bij een <b>vast contract</b>, want dat heeft geen eigen einddatum &mdash; zonder deze stap zou het als ‘lopend’ blijven staan. Een reeds ingevulde einddatum wordt niet overschreven. Zet u de status later weer terug naar actief, dan worden de uit-dienstgegevens gewist. De uit-dienstdatum is ook zichtbaar op de kaart en in <b>Mijn HR</b>.</p>
  <h3>Documenten</h3>
  <p>Onder <b>Documenten</b> uploadt u HR-documenten bij de medewerker (contract, diploma, identiteitsbewijs, overig). De bestanden staan op de <b>private schijf</b> en de inzage wordt gelogd (AVG).</p>
  <h3>Verlof (met self-service)</h3>
  <p>Elke medewerker met een gekoppeld account vraagt <b>zelf</b> verlof aan via <b>Mijn verlof</b>: type (vakantie, bijzonder, ouderschap, studie), periode en aantal uren. De aanvraag gaat naar de <b>HR-medewerker</b> (tevens leidinggevende), die goedkeurt of afwijst. Op <b>Mijn verlof</b> ziet de medewerker het <b>saldo</b> per type (recht − opgenomen) en de status van de aanvragen; een openstaande aanvraag kan zelf worden ingetrokken. Onder <b>Verlof</b> ziet de HR-medewerker alle aanvragen en beoordeelt ze; het <b>recht</b> per type stelt HR in op de medewerkerkaart.</p>
  <h3>Zwangerschaps-, bevallings- en geboorteverlof (WAZO)</h3>
  <p>Naast vakantie en bijzonder verlof registreert u ook het wettelijk verlof uit de Wet arbeid en zorg. Bij <b>Verlof aanvragen</b> kiest u het type; het formulier toont dan de wettelijke toelichting en een rekenhulp:</p>
  <ul>
    <li><b>Zwangerschaps- en bevallingsverlof</b>: samen minimaal <b>16 weken</b>. Vul de <b>uitgerekende datum</b> in, dan vult het systeem automatisch de periode (6 weken vóór t/m 10 weken ná die datum). De uitkering loopt via het UWV.</li>
    <li><b>Geboorteverlof (partner)</b>: <b>1× het aantal werkuren per week</b>, volledig doorbetaald, binnen 4 weken na de geboorte. Het systeem stelt de uren voor op basis van het dienstverband.</li>
    <li><b>Aanvullend geboorteverlof</b>: daarna <b>maximaal 5× de weekuren</b> binnen 6 maanden (70% via UWV).</li>
    <li><b>Ouderschapsverlof</b>: totaal <b>26× de weekuren</b> per kind, op te nemen tot het kind 8 jaar is. Daarvan zijn <b>9 weken (9× de weekuren) deels betaald</b> (70% via UWV) als ze in het eerste levensjaar worden opgenomen; de overige 17 weken zijn onbetaald. In één keer of gespreid op te nemen. Het formulier toont het totale recht en het betaalde deel op basis van het dienstverband.</li>
  </ul>
  <p>Dit wettelijke verlof loopt via een UWV-uitkering en staat daarom los van het vakantiesaldo; het verschijnt niet in de saldotabel maar wel in het overzicht van aanvragen. HR kan de voorgestelde data altijd aanpassen (bijvoorbeeld bij een vroege of late bevalling, of bij gespreid opnemen).</p>
  <h3>Verzuim</h3>
  <p>Onder <b>Verzuim</b> (of op de medewerkerkaart) registreert de HR-medewerker een <b>ziekmelding</b> (ziek vanaf, percentage) en later de <b>herstelmelding</b>. Zolang een melding openstaat, staat de medewerker op status ‘ziek’; bij herstel keert de status terug naar ‘actief’. Het dashboard toont de openstaande verlofaanvragen en de actuele ziekmeldingen.</p>
  <h3>Signaleringen</h3>
  <p>Onder <b>Signaleringen</b> staan de attentiepunten bij elkaar. <b>Aflopende contracten</b> toont de dienstverbanden waarvan de einddatum binnen {{ (int) config('sis.hr.contract_signaal_dagen', 60) }} dagen valt. <b>Langdurig verzuim</b> volgt per zieke medewerker de wettelijke re-integratiemijlpalen van de <b>Wet Verbetering Poortwachter</b> (probleemanalyse in week 6, plan van aanpak in week 8, ziekmelding bij het UWV in de 42e week, eerstejaarsevaluatie rond week 52 en de WIA-aanvraag in week 93): het systeem leidt de uiterste datum per mijlpaal af uit de eerste ziektedag en toont of die verstreken, binnenkort of nog gepland is. <b>Frequent verzuim</b> signaleert medewerkers met meerdere losse ziekmeldingen in de afgelopen twaalf maanden — een aanleiding voor een verzuimgesprek. De mijlpaaldata zijn een hulpmiddel; de formele re-integratie loopt via de bedrijfsarts/arbodienst.</p>
  <h3>Automatische e-mails &amp; verjaardagen</h3>
  <p>Het systeem stuurt zelf een aantal e-mails, zodat niemand iets hoeft te onthouden:</p>
  <ul>
    <li><b>Self-service-aanvraag</b>: dient een medewerker via <b>Mijn verlof</b> een aanvraag in, dan gaat er direct een e-mail naar <b>{{ config('sis.hr.notificatie_email') }}</b>. Personeelszaken weet zo meteen dat er een verzoek binnen is.</li>
    <li><b>Verjaardagen</b>: op het HR-dashboard staat het venster <b>Verjaardagen</b> met de jarigen van de komende {{ (int) config('sis.hr.verjaardag_venster_dagen', 30) }} dagen. Op de dag zelf stuurt het systeem de medewerker automatisch een <b>felicitatie-e-mail</b>.</li>
    <li><b>Startend wettelijk verlof</b>: op de dag dat een zwangerschaps-/bevallings-, geboorte- of ouderschapsverlof ingaat, krijgt Personeelszaken automatisch een melding, zodat de UWV-uitkering en vervanging op tijd geregeld worden.</li>
  </ul>
  <p>Van <b>elke</b> automatische systeem-e-mail gaat er een kopie (CC) naar de postbus van de betrokken afdeling — <b>Personeelszaken</b> voor HR, <b>Studentenzaken</b> en de <b>Examencommissie</b> voor hun berichten — zodat de afdeling altijd kan zien welke post is verstuurd. Deze e-mails worden verstuurd door een dagelijkse achtergrondtaak; daarvoor moet de <b>scheduler</b> draaien (zie de technische handleiding).</p>
  <h3>Gesprekken &amp; performance</h3>
  <p>Onder <b>Gesprekken</b> (of op de medewerkerkaart) plant de HR-medewerker een <b>beoordelings-</b>, <b>functionerings-</b> of <b>exitgesprek</b>: kies datum, gespreksvoerder en status (gepland, gehouden, afgerond). Op het gespreksscherm legt u de <b>samenvatting</b> en <b>feedback</b> vast en beheert u de <b>doelen/KPI's</b> (met status open/behaald/niet behaald) en de <b>competentiebeoordelingen</b> (onvoldoende t/m uitstekend, met toelichting). De gesprekken blijven als <b>historie</b> bij de medewerker staan; het dashboard toont de aankomende geplande gesprekken.</p>
  <h3>Organisatie &amp; rapportage</h3>
  <p>Onder <b>Organisatie</b> ziet u de <b>afdelingenboom</b>: afdelingen, onderliggende teams (een afdeling met een bovenliggende afdeling), de afdelingsmanager en het aantal medewerkers. Op dezelfde pagina <b>beheert de HR-medewerker de afdelingen én de functies rechtstreeks</b>: onder de boom staan twee beheerblokken. Bij <b>Afdelingen &amp; teams beheren</b> voegt u een afdeling toe of wijzigt u per rij de code, naam, bovenliggende afdeling (= team), leidinggevende en of de afdeling actief is. Bij <b>Functies beheren</b> voegt u een functie toe of wijzigt u code, naam en categorie (docent/staf/management). Verwijderen kan alleen als er niets meer aan hangt (een afdeling zonder medewerkers en onderliggende teams; een functie zonder medewerkers). Alle wijzigingen worden gelogd. Verlof-, contract- en gesprekstypen zijn vaste systeemwaarden en worden niet hier beheerd. Het Schoolbestuur ziet deze pagina <b>alleen-lezen</b>. Onder <b>Rapportage</b> staan de kerncijfers (medewerkers, totaal- en gemiddelde FTE, actueel verzuim en ziektedagen) en een overzicht <b>per afdeling</b> (aantal, FTE, verzuim%), met grafieken en een <b>CSV-export</b> op medewerkerniveau. De HR-medewerker, Beheer en Schoolbestuur zien de cijfers van de hele instelling.</p>
  <h3>Verzuim &amp; verlof per medewerker</h3>
  <p>Om <b>elke medewerker duidelijk te volgen</b> op ziekteverzuim en verlof is er een apart rapport <b>Verzuim &amp; verlof</b> (via het menu of de knop op de rapportagepagina). Het toont <b>één regel per medewerker</b> met links de verzuimcijfers — aantal <b>ziekmeldingen</b>, <b>ziektedagen</b> en het <b>verzuimpercentage</b> (kalenderdag-gebaseerd: ziektedagen ÷ verstreken dagen in het jaar) — en rechts het verlof in uren: <b>recht</b>, <b>opgenomen</b> (alleen goedgekeurd verlof), <b>saldo</b> en het aantal <b>openstaande aanvragen</b>. Bovenaan staan totaaltegels (medewerkers, nu ziek gemeld, gemiddeld verzuim, openstaande verlofaanvragen). U kiest het <b>jaar</b> en filtert op <b>afdeling</b>, exporteert alles naar <b>CSV</b>, en klikt op een naam voor het volledige verzuim- en verlofverloop op de medewerkerkaart.</p>
  <h3>Notities (contactmomenten)</h3>
  <p>Op de medewerkerkaart staat onderaan een <b>Notities</b>-blok, hetzelfde als bij Studentenzaken. Het is een <b>doorlopend logboek</b> per medewerker waarin u alle contactmomenten vastlegt: <b>e-mails</b>, <b>telefoongesprekken</b> en <b>gespreksverslagen</b>. Elke notitie krijgt automatisch de <b>datum</b> en <b>uw naam</b> als auteur; de nieuwste staat bovenaan. De <b>HR-medewerker</b> en de <b>Beheerder</b> voegen notities toe en verwijderen ze; het <b>Schoolbestuur</b> leest mee (alleen-lezen). Het gaat om werkinformatie — leg hier geen BSN of andere bijzondere persoonsgegevens vast.</p>
  <h3>Onboarding &amp; offboarding</h3>
  <p>Op de medewerkerkaart start de HR-medewerker een <b>onboarding-</b> of <b>offboarding-checklist</b>: met één klik worden de standaard <b>sjabloontaken</b> aangemaakt (bijv. contract laten tekenen, account aanvragen, werkplek gereedmaken; of bij uitdiensttreding: exitgesprek, toegang blokkeren, materialen innemen). U vinkt de taken af (met datum en wie ze afvinkte), voegt eigen taken toe en ziet de voortgang (aantal gereed van het totaal).</p>
  <h3>Mijn HR (self-service)</h3>
  <p>Elke medewerker met een gekoppeld account heeft een eigen, <b>alleen-lezen</b> dossier onder <b>Zelfservice → Mijn HR</b>. U ziet er uw <b>gegevens</b> (functie, afdeling, leidinggevende, huidig dienstverband met FTE), uw <b>verlofsaldo</b> per type, uw <b>verlofaanvragen</b>, uw <b>gesprekken</b> (aankomend en historie), uw <b>documenten</b> (met downloadknop — u kunt uitsluitend uw eigen documenten ophalen, inzage wordt gelogd) en uw <b>onboarding/offboarding-checklists</b> met voortgang. Met de knop <b>Agenda (iCal)</b> downloadt u een <code>.ics</code>-bestand met uw geplande gesprekken en uw goedgekeurde verlof; dat importeert of abonneert u in uw eigen agenda. Het is bewust een <b>los bestand</b> — er is geen live koppeling met Outlook of Teams, zodat de gegevens het intranet niet verlaten.</p>
  <p><b>Hoe u er komt.</b> Heeft u een personeelsdossier, dan staat <b>HR / Personeelszaken</b> op uw modulekeuzescherm na het inloggen — ook als u geen HR-rol heeft, bijvoorbeeld als docent. U opent dan meteen <b>Mijn HR</b>; u krijgt niet het HR-dashboard en niet de schermen met andermans personeelsdossiers. Daarnaast blijft <b>Zelfservice → Mijn HR</b> in het menu staan van de module waarin u werkt, zodat u er ook zonder omweg bij kunt.</p>

  <h2 id="h14">14. Balie / Receptie (aparte module)</h2>
  <p>De module <b>Balie / Receptie</b> is het werkregister van de ontvangstbalie. U legt er alles vast wat aan de ingang binnenkomt of naar buiten gaat: <b>telefoongesprekken</b> (inkomend en uitgaand), <b>bezoekers</b>, en <b>post</b> (ontvangen en verzonden). Alles komt in één doorlopend <b>logboek</b> te staan, met de nieuwste registratie bovenaan. De rol <b>Balie / Receptie</b> registreert en wijzigt; het <b>Schoolbestuur</b> kijkt alleen mee. De Directie heeft geen toegang: het logboek is een werkregister van de balie, geen opleidingsinformatie. De baliemedewerker ziet bewust géén studentdossiers, cijfers of personeelsdossiers — alleen de namenlijst van medewerkers, om een gesprek of bezoek aan de juiste persoon te koppelen.</p>

  <h3>Iets registreren</h3>
  <p>Op het <b>Overzicht</b> staan drie knoppen: <b>Telefoongesprek</b>, <b>Bezoeker</b> en <b>Poststuk</b>. Het formulier toont daarna alleen de velden die bij dat soort horen. U kiest de <b>richting</b> (inkomend of uitgaand), de <b>datum en tijd</b> (die staat standaard al op nu), het <b>onderwerp</b>, de <b>naam</b> van degene die belde, op bezoek kwam of de post stuurde, en een <b>korte toelichting</b>. Bij <b>Bestemd voor</b> kiest u de medewerker voor wie het bestemd is; is het niet voor één persoon maar voor een afdeling, vul dan het veld <b>Of afdeling</b> in (bijvoorbeeld "Studentenzaken").</p>
  <p>Twee dingen gaan automatisch, zodat het logboek klopt: een <b>bezoek</b> is altijd inkomend (een uitgaand bezoek bestaat niet), en bij <b>post</b> wordt geen onderwerp vastgelegd — daar gaat het om afzender, datum en toelichting.</p>

  <h3>Wie is er nu in het pand?</h3>
  <p>Op het Overzicht staat de lijst <b>Nu in het pand</b>: iedere bezoeker die is aangemeld maar nog niet is afgemeld. Vertrekt een bezoeker, klik dan op <b>Afmelden</b>; het vertrekmoment wordt dan vastgelegd. Deze lijst is bedoeld als bezoekersoverzicht <b>bij een ontruiming</b> — meld bezoekers daarom consequent af.</p>

  <div class="let">Vergeet u af te melden, dan blijft de bezoeker in de lijst staan en klopt het ontruimingsoverzicht niet. Loop de lijst aan het eind van de dag na.</div>

  <h3>Terugzoeken, filteren en exporteren</h3>
  <p>Onder <b>Logboek</b> staat alles bij elkaar. Het zoekveld doorzoekt het <b>onderwerp</b>, de <b>naam</b>, de <b>organisatie</b>, de <b>afdeling</b> én de <b>toelichting</b> tegelijk — u hoeft dus niet te weten in welk veld iets genoteerd is. Daarnaast filtert u op <b>soort</b>, op <b>richting</b>, op de <b>medewerker</b> voor wie het bestemd was, op een <b>periode</b> (van/tot), of op <b>alleen nog aanwezig</b>. Met <b>Exporteren (CSV)</b> haalt u op wat u op dat moment ziet — de filters gelden dus ook voor de export. Het bestand opent in Excel en is bedoeld voor rapportage en archivering.</p>

  <div class="tip">Registraties worden <b>nooit verwijderd</b>: het logboek is een chronologisch verantwoordingsdocument. Maakt u een fout, corrigeer die dan met <b>Bewerken</b>. Elke aanmaak, wijziging en export wordt gelogd (wie, wat, wanneer).</div>

  <h2 id="h15">15. Bibliotheek (aparte module)</h2>
  <p>De module <b>Bibliotheek</b> beheert de collectie en de uitleen. De rol <b>Bibliotheekmedewerker</b> werkt hierin; het <b>Schoolbestuur</b> kijkt mee (alleen-lezen). De bibliotheekmedewerker ziet géén cijfers en géén personeelsdossiers — wel de namen en contactgegevens van leners, want zonder die kan niet worden uitgeleend. De collectie is meertalig: <b>Arabisch, Turks, Engels en Nederlands</b> worden correct opgeslagen, doorzocht en getoond.</p>

  <h3>Titel en exemplaar: het verschil</h3>
  <p>Dit is de kern van de module. Een <b>titel</b> (het boek als werk) staat één keer in de catalogus, met ISBN, auteurs, talen, vakgebied en uitgavejaar. De <b>exemplaren</b> zijn de fysieke boeken die u in de kast hebt staan: elk met een eigen <b>serienummer</b>, een plek in de kast en een eigen <b>status</b>. Heeft u drie exemplaren van hetzelfde boek, dan voert u de titel één keer in en voegt u drie serienummers toe — u kunt ze dan los uitlenen. Zo werken professionele bibliotheeksystemen, en zo blijft de teller "beschikbaar / totaal" kloppen.</p>

  <h3>Een publicatie registreren</h3>
  <p>Kies bij <b>Publicatie toevoegen</b> eerst het type: <b>Boek</b>, <b>Tijdschrift</b> of <b>Digitaal document</b>. Vul daarna de titel, het ISBN, de auteur(s), de taal of talen (meerdere mogen), het uitgavejaar, het druknummer en het vakgebied in. Een auteur die nog niet bestaat, wordt automatisch aangemaakt. Onderaan geeft u de serienummers van de exemplaren op en kiest u de boekenkast. Een <b>digitaal document</b> heeft geen fysieke exemplaren en wordt niet uitgeleend.</p>

  <h3>Boekreeksen (meerdelige werken)</h3>
  <p>Bestaat een werk uit meerdere delen — bijvoorbeeld <b>Tafsir Ibn Kathir</b> deel 1 tot en met 4 — gebruik dan <b>Boekreeks aanmaken</b>. U voert de gedeelde gegevens (auteurs, talen, vakgebied, jaar, kast) <b>één keer</b> in en zet daaronder in één scherm alle delen neer, elk met een deelnummer en een serienummer. Elk deel wordt een apart, los uitleenbaar boek, maar ze blijven zichtbaar bij elkaar horen. Later een deel bijvoegen kan op de reekspagina; de gedeelde gegevens worden dan overgenomen.</p>

  <h3>Tijdschriften en artikelen</h3>
  <p>Een tijdschrift registreert u als publicatie van het type <b>Tijdschrift</b>. Daaronder voegt u de <b>uitgaven</b> toe (uitgavenummer, publicatiedatum, jaar, locatie), en per uitgave de <b>artikelen</b> met artikeltitel, auteur(s), pagina's, trefwoorden en een korte beschrijving. Onder <b>Artikelen zoeken</b> vindt u een artikel terug op <b>artikeltitel</b>, <b>auteur</b>, <b>trefwoord</b> of <b>tijdschriftnaam</b> — en ziet u meteen in welk tijdschrift en welke uitgave het staat.</p>


  <h3>Soorten, talen, vakgebieden en kasten zelf beheren</h3>
  <p>Onder <b>Beheer &rarr; Soorten &amp; tabellen</b> beheert u de keuzelijsten van de bibliotheek zelf, zonder tussenkomst van een programmeur: de <b>publicatiesoorten</b> (boek, tijdschrift, digitaal document, cd, dvd — en wat u er nog aan toevoegt), de <b>talen</b>, de <b>vakgebieden</b> (met de rekletter) en de <b>kasten</b>.</p>
  <p>Bij een soort staan twee vinkjes die géén etiket zijn maar het gedrag van het systeem bepalen. <b>Fysieke exemplaren</b>: er zijn stuks die u kunt uitlenen (een boek, een cd, een dvd) — een digitaal document niet, dat krijgt dan ook geen exemplaren en geen uitleenknop. <b>Uitgaven met artikelen</b>: het verschijnt in afleveringen waarin artikelen staan (een tijdschrift). Zet u die vinkjes goed, dan gedraagt een nieuwe soort zich meteen zoals het hoort.</p>
  <div class="let">Verwijderen kan alleen als er niets aan hangt: een soort met titels, een taal die aan een boek is gekoppeld of een kast met exemplaren blijft staan. Wilt u zo'n waarde uit de keuzelijsten halen, zet hem dan op <b>inactief</b> — hij verdwijnt uit de formulieren, maar de bestaande titels blijven kloppen.</div>

  <h3>De bestaande Excel-bibliotheek importeren</h3>
  <p>Onder <b>Importeren</b> leest u het bestaande Excel-bestand in. Dat gaat in twee stappen: eerst <b>proefdraaien</b> (het systeem leest het bestand, toont hoeveel titels en exemplaren het vindt en welke regels het overslaat, maar slaat nog niets op), daarna pas <b>importeren</b>. Het bestand moet het werkblad <b>Alle Boeken</b> bevatten met de kolommen rekcode, aantal, vakgebied, taal, titel, schrijver en opmerking.</p>
  <p>Wat het systeem doet met de bron: het <b>vakgebied</b> komt uit de <b>rekletter</b> (A&nbsp;=&nbsp;Tafsir, F&nbsp;=&nbsp;Fiqh, en zo verder), omdat de vakgebiedkolom in het Excel-bestand tientallen schrijfwijzen van hetzelfde begrip bevat. Tikfouten in de taal worden gecorrigeerd; staat er iets wat geen taal is (bijvoorbeeld "woordenboeken"), dan krijgt het boek geen taal en gaat die tekst naar het opmerkingveld. De kolom <b>aantal</b> is het aantal fysieke exemplaren: bij rek "F. 143" met aantal 3 krijgt u één titel met de exemplaren F.143-1, F.143-2 en F.143-3 in kast F. <b>Er gaat niets verloren</b>: de oorspronkelijke vakgebied- en taaltekst blijft bewaard in de opmerking bij het boek.</p>
  <div class="tip">De import is herhaalbaar: regels die al zijn ingelezen worden overgeslagen. U krijgt dus geen dubbele boeken als u het bestand nog een keer inleest. Voor de volledige collectie (ruim 11.000 titels) draait de beheerder het commando op de server; het scherm is bedoeld voor kleinere bestanden en om vooraf te controleren.</div>

  <h3>Zoeken en filteren in de catalogus</h3>
  <p>In de <b>Catalogus</b> filtert u op soort (boek, tijdschrift, digitaal document), vakgebied, taal, status en jaar. <b>Zodra u een keuze maakt, wordt de lijst meteen bijgewerkt</b> — u hoeft niet op Filteren te klikken. Wilt u bijvoorbeeld alleen tijdschriften zien, kies dan bij "Alle soorten" de optie <b>Tijdschrift</b>. In het zoekveld typt u een titel, ISBN, auteur of reeks en drukt u op <b>Enter</b>. Boven de lijst ziet u welke filters actief zijn, met een link om weer alles te tonen.</p>
  <p>De catalogus telt duizenden titels. Om daar makkelijk in te navigeren staat boven de lijst een <b>A–Z-balk</b>: klik op een letter en u ziet alleen de titels die met die letter beginnen (de knop <b>#</b> toont titels die met een cijfer of met Arabisch schrift beginnen). Daarnaast kiest u rechts hoeveel titels u <b>per pagina</b> wilt zien (25, 50, 100 of 200). Onder de lijst kunt u met de paginanummers of het sprongveld <b>direct naar een bepaalde pagina</b> springen — u hoeft niet meer stap voor stap door te klikken. Het snelst vindt u één bepaald boek nog altijd via het <b>zoekveld</b>.</p>

  <h3>Artikelen toevoegen, wijzigen en verwijderen</h3>
  <p>Open een tijdschrift in de catalogus en klap een uitgave open; met <b>Artikelen beheren</b> komt u op de uitgavepagina. Onderaan staat het formulier <b>Artikel toevoegen</b> (titel, auteur(s), pagina's, trefwoorden, korte beschrijving; meerdere auteurs kunnen met de knop <i>Auteur toevoegen</i>). Bij elk bestaand artikel klapt u <b>Artikel bewerken of verwijderen</b> open om het aan te passen of weg te halen. Elke wijziging wordt gelogd.</p>
  <p><b>Een artikel toevoegen kan nu ook rechtstreeks op de tijdschriftpagina.</b> Onderaan staat het formulier <b>Artikel toevoegen</b>: kies bij "In welke uitgave?" een bestaande uitgave, of kies "— nieuwe uitgave —" en vul een uitgavenummer in; die uitgave wordt dan meteen aangemaakt. Zo hoeft u niet eerst de uitgave op te zoeken. Een artikel hoort altijd bij een uitgave, zodat vindbaar blijft in welk nummer het stond.</p>
  <p><b>En bij het aanmaken van een nieuw tijdschrift</b> kunt u meteen een eerste uitgave met een paar artikelen invoeren (titel, auteur, pagina's). Dat is optioneel — laat u het leeg, dan maakt u alleen het tijdschrift aan en voegt u de inhoud later toe.</p>
  <div class="let">Bij <b>geïmporteerde</b> artikelen staat in het veld Beschrijving de oorspronkelijke regel uit het bronbestand. Laat die staan: daardoor blijft het artikel vindbaar op elk woord dat in de bron stond, ook op wat het systeem niet als titel of auteur herkende.</div>

  <h3>De tijdschriftinhoud importeren (artikelen)</h3>
  <p>De inhoud van de tijdschriften — welke artikelen in welke uitgave staan — komt uit twee aparte bestanden: een Excel-bestand met de Engelse tijdschriften en een Word-bestand met de Arabische. De beheerder leest die in met een commando op de server; het systeem herkent daarin de opbouw <b>rek &rarr; tijdschrift &rarr; uitgave &rarr; artikel</b> en legt per artikel de <b>titel</b>, de <b>auteur</b>, de <b>pagina's</b> en (bij het Engelse bestand) de <b>Arabische vertaling van de titel</b> vast.</p>
  <p>Daarna vindt u onder <b>Artikelen zoeken</b> een artikel terug op titel, auteur, trefwoord of tijdschriftnaam — en ziet u meteen in welk tijdschrift en welke uitgave het staat.</p>
  <div class="tip">De volledige oorspronkelijke regel uit het bronbestand blijft bij elk artikel bewaard. Ook als het systeem de titel en de auteur niet netjes uit elkaar kon halen, is het artikel dus vindbaar op elk woord dat er in de bron stond — er gaat niets verloren.</div>
  <div class="let">Regels die niet in de structuur passen (inhoudsopgaven, ondertitels, en in het Arabische bestand de boekhoofdstukken die ertussen staan) worden <b>overgeslagen en gerapporteerd</b>, niet geraden. De beheerder kan die lijst opvragen en met de hand nalopen.</div>

  <h3>ISBN en uitgavejaar automatisch aanvullen (verrijking)</h3>
  <p>De oude Excel-lijst bevat geen ISBN's en geen uitgavejaren, en er staan tikfouten in de titels. Onder <b>Verrijking (ISBN)</b> vult het systeem die aan door de titel op te zoeken bij een openbare bibliografische bron (Open Library). Dat gebeurt alleen voor de <b>Nederlandse, Engelse en Turkse</b> titels: Arabische titels staan in de bron door elkaar in Arabisch schrift en in transliteratie, en worden door zulke bronnen slecht gedekt — daar zou "corrigeren" neerkomen op gokken.</p>
  <p><b>Het systeem raadt niet.</b> Er wordt alleen iets gewijzigd bij een <b>zekere</b> match: de gevonden titel moet voor minstens 92% overeenkomen met de onze, en de auteur moet kloppen. In dat geval worden het <b>ISBN</b> en het <b>uitgavejaar</b> ingevuld en wordt de schrijfwijze van de titel rechtgezet (bijvoorbeeld <i>Kuran Ansiklopedisi</i> → <i>Kur'an ansiklopedisi</i>). Alles daaronder wordt <b>overgeslagen</b> en verschijnt in de lijst <b>Onzeker</b>, waar u zelf beslist: <b>Overnemen</b> of <b>Afwijzen</b>.</p>
  <div class="tip">Een ISBN dat u zelf al had ingevuld, wordt nooit overschreven. De oude titel blijft bewaard en elke wijziging wordt gelogd, dus een correctie is altijd terug te draaien.</div>

  <h3>Uitlenen</h3>
  <p>Bij <b>Uitlenen</b> kiest u een beschikbaar exemplaar en daarna de lener: een <b>student</b> of een <b>docent/medewerker</b>. De lener is altijd iemand die al in het systeem staat, zodat naam, telefoonnummer en e-mailadres uit het dossier komen en er geen tikfouten insluipen. De verwachte retourdatum wordt automatisch berekend uit de standaardtermijn (voor studenten korter dan voor docenten), maar u mag hem aanpassen. Na het uitlenen gaat er automatisch een <b>bevestigingsmail</b> naar de lener, met een kopie naar de bibliotheekpostbus.</p>

  <div class="let">Een exemplaar dat al is uitgeleend, verloren of beschadigd staat niet in de keuzelijst. Wilt u het toch uitlenen, neem het dan eerst in of zet de status terug op Beschikbaar.</div>

  <h3>Innemen</h3>
  <p>Bij de inname legt u de <b>retourdatum</b> vast en de <b>staat van het materiaal</b>: Uitstekend, Goed, Licht beschadigd, Beschadigd of Ernstig beschadigd, met eventueel een opmerking. Kiest u <b>Beschadigd</b> of <b>Ernstig beschadigd</b>, dan volgt er automatisch een schademelding en gaat het exemplaar uit de uitleen (status Beschadigd) tot u het weer vrijgeeft. Of iets te laat was, rekent het systeem zelf uit; u hoeft dat niet aan te vinken.</p>

  <h3>Automatische e-mails</h3>
  <p>De bibliotheek verstuurt vijf soorten berichten, allemaal met een kopie naar de bibliotheekpostbus: de <b>uitleenbevestiging</b>, een <b>herinnering drie dagen vóór de vervaldatum</b>, een <b>waarschuwing als een student te laat is</b> (waarin de <b>boete van € 10,00 per boek</b> wordt genoemd), een <b>herinnering voor docenten</b> die elke drie dagen wordt herhaald (zonder boete), en de <b>retourbevestiging</b>. Op de pagina van de lener ziet u precies welke e-mails zijn verstuurd, wanneer, aan wie, en of het gelukt is. De <b>Beheerder</b> past de teksten aan onder <b>E-mailsjablonen</b>; het boetebedrag komt automatisch in de plaats van de variabele <b>&#123;&#123;Boete&#125;&#125;</b>.</p>

  <div class="tip">Mislukt een e-mail (bijvoorbeeld omdat de lener geen e-mailadres in het dossier heeft), dan gaat de uitlening gewoon door en staat de mislukte poging in het e-maillogboek. Een boek moet uitgeleend kunnen worden, ook als de mailserver hapert.</div>

  <h3>Overzicht en rapportage</h3>
  <p>Het <b>Overzicht</b> toont de kerncijfers (boeken, tijdschriften, digitale documenten, nu uitgeleend, te laat, vandaag uitgeleend en geretourneerd), de <b>waarschuwingen</b> (wat te laat is en wat binnen drie dagen terug moet) en grafieken van de uitleningen per maand, per vakgebied en per taal. Onder <b>Rapportage</b> staan de overzichten per vakgebied, per auteur en per uitgavejaar, plus de <b>meest uitgeleende publicaties</b> met het aantal uitleningen en de laatste uitleendatum. De algemene bibliotheeklijst exporteert u naar <b>CSV</b>.</p>

  <h3>Te late studenten bij Studentenzaken</h3>
  <p>Levert een student materiaal niet op tijd in, dan verschijnt dat automatisch op het <b>dashboard van Studentenzaken</b>: studentnummer, naam, geleend materiaal, aantal dagen te laat en het aantal verstuurde waarschuwingen. Zo kan Studentenzaken de student erop aanspreken zonder in de bibliotheekmodule te hoeven kijken.</p>

  <div class="let">De <b>boete</b> is vastgesteld op <b>€ 10,00 per boek</b> en wordt in de te-laat-mail aan studenten genoemd. Het systeem <b>int of administreert de boete zelf niet</b> — dat regelt de bibliotheek buiten het systeem. Docenten krijgen geen boete. Te laat leidt daarnaast tot het signaal op het dashboard van Studentenzaken.</div>

  <h3>Bibliotheek IUASR — een boek zoeken (voor iedereen)</h3>
  <p>Elke medewerker ziet in het menu de ingang <b>Bibliotheek IUASR</b>, in welke module u ook werkt. Daar zoekt u een boek op titel, auteur, ISBN of <b>rekcode</b>. U ziet meteen de <b>rek / plaats</b> (bijvoorbeeld <b>F. 1070</b>: de letter is de kast, het nummer de plaats in het rek), de taal, het vakgebied en of er een exemplaar <b>beschikbaar</b> is. Met het vinkje <b>Alleen beschikbaar</b> verbergt u wat is uitgeleend.</p>
  <p>Dit scherm is <b>alleen-lezen</b>: u kunt er niets wijzigen en er staan geen gegevens van leners. Wilt u een boek lenen, meld u dan bij de bibliotheek met het serienummer; zij leggen de uitlening vast.</p>

  <h2 id="h16">16. Scriptie Coördinatie (aparte module)</h2>
  <p>De module <b>Scriptie Coördinatie</b> begeleidt het volledige scriptietraject van een student, van de toelating tot de afronding. De rol <b>Scriptiecoördinator</b> regisseert het traject; de <b>docent</b> (scriptiebegeleider), de <b>Directie</b> (opleidingsdirecteur) en de <b>Examencommissie</b> (scriptiecommissie/examinator) werken per stap mee; het <b>Schoolbestuur</b> kijkt mee (alleen-lezen). U opent de module via het <b>modulekeuzescherm</b> (rechtsboven <b>Modules</b>).</p>
  <h3>Scriptie Kandidaten</h3>
  <p>Onder <b>Scriptie Kandidaten</b> ziet de coördinator de studenten die aan de <b>toelatingseisen</b> voldoen: minimaal <b>180 EC</b> behaald én <b>Methoden en Technieken I en II</b> afgerond. Per student staat de behaalde EC en of de twee vakken zijn behaald. Voldoet een student, dan start u met één klik het scriptietraject. (Met het vinkje <b>Ook wie nog niet voldoet</b> toont u alle actieve studenten.)</p>
  <h3>Het traject in elf stappen</h3>
  <p>Een traject is een pagina met <b>elf tabbladen</b>, één per stap. U doorloopt ze op volgorde; elke stap heeft een eigen formulier en/of checklist en een eigen <b>status</b>. De stappen zijn: 1. Toelatingseisen · 2. Scriptievoorstel · 3. Onderwerpbeoordeling · 4. Begeleider · 5. Scriptieovereenkomst · 6. Plan van Aanpak · 7. Definitieve inlevering · 8. Plagiaatcontrole · 9. Beoordeling · 10. Verdediging · 11. Afronding.</p>
  <p>Boven aan elk tabblad zet u de <b>status</b> van de stap en vinkt u de stap <b>af</b> als hij klaar is. Een stap kan pas worden afgevinkt als de vorige stap gereed is. Elke stap wordt afgevinkt door de <b>verantwoordelijke rol</b>: de coördinator voor de organiserende stappen (toelating, voorstel, begeleider, overeenkomst, plagiaat, afronding), de <b>examencommissie</b> voor de beoordelende stappen (onderwerp, beoordeling, verdediging) en de <b>begeleider</b> voor het plan van aanpak en de inlevering. Vinkt u de laatste stap <b>Afronding</b> af, dan is het traject afgerond.</p>
  <h3>Overeenkomst, gesprekken en documenten</h3>
  <p>Bij stap 5 legt u de <b>digitale goedkeuring</b> vast (student, begeleider, coördinator, opleidingsdirecteur) en genereert u de <b>scriptieovereenkomst</b> als ondertekende PDF met verificatiecode. Bij het Plan van Aanpak legt de begeleider <b>begeleidingsgesprekken</b> vast (datum, besproken punten, feedback, actiepunten). Bij verschillende stappen uploadt u <b>documenten</b> (plan van aanpak, eindversie, plagiaatrapport, presentatie); die worden veilig en met versiebeheer bewaard.</p>
  <div class="let">Cijfers en een academisch besluit (onderwerp, beoordeling, verdediging) horen bij de examencommissie: de coördinator kan die stappen niet zelf afvinken. Zo blijft de rolscheiding gewaarborgd.</div>

  <h2 id="h17">17. Stichtingsbestuur (aparte module)</h2>
  <p>De module <b>Stichtingsbestuur</b> houdt het bestuur en het toezicht van de stichting bij. De rol <b>Stichtingsbestuur</b> beheert de module; de Beheerder voor onderhoud. Deze module is bewust <b>afgeschermd</b>: er kijkt geen andere rol mee, want het gaat om governance- en persoonsgegevens. (Let op: dit is iets anders dan het <b>Schoolbestuur</b>, dat de onderwijsstatistieken overziet.)</p>
  <h3>Leden &amp; Raad van Toezicht</h3>
  <p>U legt twee organen vast: het <b>Stichtingsbestuur</b> (met de titels voorzitter, penningmeester, secretaris en lid, plus een omschrijving van de bevoegdheid) en de <b>Raad van Toezicht</b> (de commissarissen). Per persoon houdt u naam, achternaam, geboortedatum, adres, telefoonnummer, e-mail, de datum in functie en de titel bij. Treedt iemand af, zet dan het vinkje <b>Actief</b> uit en vul de datum uit functie in — het lid blijft dan bewaard in de historie.</p>
  <h3>Vergaderingen</h3>
  <p>Onder <b>Vergaderingen</b> legt u per (jaarlijkse) vergadering vast: de datum, het soort (Stichtingsbestuur of Raad van Toezicht), de besproken onderwerpen en de besluiten. In het <b>aanwezigheidsraster</b> zet u per lid of hij <b>fysiek</b> of <b>online</b> aanwezig was, of <b>niet bijgewoond</b> heeft. Laat u een lid leeg, dan is er niets voor hem geregistreerd. Op de detailpagina ziet u de onderwerpen, de besluiten en de aanwezigheid in één overzicht.</p>

  <h2 id="h18">18. Noodtoegang (alleen voor beheerders)</h2>
  <p>Normaal logt u in met uw IUASR-account via Microsoft Entra ID. Valt Entra ID uit, dan kan niemand meer inloggen en ligt het systeem stil. Voor dat geval bestaat de <b>noodtoegang</b>: ten hoogste <b>twee</b> beheerders kunnen dan met een gebruikersnaam en wachtwoord binnen, via de link <b>Noodtoegang</b> onder aan het inlogscherm. Voor alle andere medewerkers verandert er niets — die accounts hebben geen wachtwoord en kunnen deze weg niet gebruiken.</p>
  <p>De noodtoegang werkt <b>uitsluitend vanaf het interne netwerk</b>. Moet u tijdens een storing van buiten werken, ga dan eerst de VPN op.</p>
  <h3>Beheer</h3>
  <p>De Beheerder beheert de noodaccounts via <b>Beheer → Noodaccounts</b>: een beheerder aanwijzen, het wachtwoord wijzigen, of de noodtoegang intrekken. Bij het wijzigen typt u ter bevestiging het e-mailadres exact over — dezelfde extra stap als bij het verwijderen van een student. Intrekken wist alleen het wachtwoord; het gebruikersaccount blijft gewoon bestaan.</p>
  <div class="let">Behandel het noodwachtwoord als de sleutel van het gebouw. Deel het nooit per e-mail of chat en zet het niet in een document op een gedeelde schijf. Bewaar het in de digitale kluis of wachtwoordmanager, en geef de twee wachtwoorden aan <b>twee verschillende personen</b> — dan sluit één vergeten wachtwoord u niet buiten. Kies één lange zin van minimaal 16 tekens; lengte beschermt hier beter dan leestekens. Elke inlogpoging wordt vastgelegd in het audit-logboek, geslaagd én mislukt.</div>

  <h2 id="h19">19. Quote in de zijbalk (99 Schone Namen)</h2>
  <p>Bovenaan het menu staat een <b>Schone Naam van Allah</b> (Asma ul-Husna) met de Arabische tekst en de Nederlandse betekenis, of een eigen spreuk. Hij <b>wisselt elke vijf minuten</b>. Welke er staat volgt uit de klok en niet uit uw eigen bezoek, dus u en uw collega's zien op hetzelfde moment dezelfde Naam — en de reeks loopt door terwijl u werkt. U hoeft niets in te stellen; het is bedoeld als bemoediging, er hangt geen functie aan.</p>
  <h3>Beheren (Beheerder)</h3>
  <p>Via <b>Beheer → Quotes</b> voegt de Beheerder eigen spreuken toe (kop, Arabische tekst, Nederlandse betekenis, bron en een afbeelding), zet hij een quote met één klik aan of uit, en past hij de volgorde aan. Alle 99 Namen staan er al in.</p>
  <h3>Afbeeldingen aanleveren</h3>
  <p>Vierkant, <b>456 × 456 pixels</b>, <b>PNG met een doorzichtige achtergrond</b>. In de zijbalk wordt de afbeelding op 152 pixels getoond — dat is precies <b>4 cm</b>; drie keer zo groot aanleveren houdt hem scherp op een goed beeldscherm. Maak het lijnwerk <b>goud of wit</b>: de tegel heeft in zowel de lichte als de donkere modus dezelfde donkere achtergrond, dus u hoeft maar één versie te maken. Een quote zonder afbeelding toont gewoon de Arabische tekst, dus u kunt de afbeeldingen rustig later toevoegen.</p>
  <h3>Islamitische datum</h3>
  <p>Onder de Naam staat de <b>islamitische (hidjri) datum</b> van vandaag: eerst in Arabisch schrift, daaronder in Nederlandse schrijfwijze (bijvoorbeeld <i>5 Safar 1448 AH</i>) en de gewone datum. De omrekening volgt standaard de kalender van <b>Umm al-Qura</b>, de breedst gebruikte. Houdt IUASR een andere telling aan — een andere variant, of de plaatselijke <b>maansobservatie</b> die er een dag naast kan zitten — dan stelt de Beheerder dat in; zie de technische handleiding. De datum is informatief en heeft geen invloed op inschrijvingen, termijnen of roosters: daarvoor blijft de gewone kalender leidend.</p>
  <h3>Achtergrondpatroon</h3>
  <p>Op het <b>inlogscherm</b> en het <b>modulekeuzescherm</b> loopt een fijn islamitisch patroon door de achtergrond: achthoekige sterren (<i>khatam</i>) met ruiten ertussen, in het goud van de huisstijl op een zeer lage dekking. Het staat bewust alleen op die twee schermen — over lijsten en formulieren heen zou zo'n patroon onrustig worden en het lezen bemoeilijken. Het past zich aan de lichte en donkere modus aan en wordt bij afdrukken weggelaten.</p>

  <h2 id="h19b">19b. Werken op tablet en telefoon</h2>
  <p>Het systeem is gemaakt voor een monitor of laptop, maar werkt ook op een <b>tablet</b> en een <b>telefoon</b>. Op die schermen verandert er een aantal dingen, zodat u niet hoeft te knijpen of zijwaarts te schuiven.</p>
  <h3>Het menu</h3>
  <p>Op een smal scherm staat het menu niet meer vast naast de pagina, maar schuift het als paneel over de inhoud. U opent het met de <b>menuknop</b> (de drie streepjes) linksboven. Sluiten kan door naast het menu te tikken, opnieuw op de knop te drukken, of met <b>Esc</b>. De menugroepen en de Schone Naam blijven gewoon zichtbaar. Draait u de tablet naar liggend, dan komt het menu vanzelf weer vast naast de pagina te staan.</p>
  <h3>Lijsten</h3>
  <p>Op een telefoon zijn tabellen te breed. Elke rij wordt daarom een <b>kaartje</b> waarin de gegevens onder elkaar staan, met de knop rechts. Op een tablet blijft de gewone tabel staan — daar is de ruimte er wel. Brede grafieken (zoals de instroom per studiejaar) schuift u zijwaarts binnen hun eigen kader; de pagina zelf blijft stilstaan.</p>
  <h3>De bovenbalk</h3>
  <p>Past de bovenbalk niet op één regel, dan breekt hij netjes af naar twee regels in plaats van dat er knoppen wegvallen. Op een telefoon worden <b>Modules</b> en <b>Help</b> als icoon getoond en wijkt de weekkalender; uw rol blijft altijd zichtbaar, want die bepaalt wat u mag zien.</p>
  <div class="tip">Werkt u op een tablet, gebruik hem dan liggend voor schermen met veel kolommen (cijferinvoer, aanwezigheidslijsten). Die zijn met een raster van vakken en weken nu eenmaal breed; liggend heeft u de ruimte die daarbij hoort.</div>

  <h2 id="h20">20. Systeemmeldingen (Beheerder)</h2>
  <p>Soms moet iedereen iets weten: <i>"Vandaag is het systeem vanaf 18.00 uur niet beschikbaar wegens onderhoud."</i> De Beheerder plaatst zo'n bericht via <b>Beheer &rarr; Systeemmeldingen</b>. Het verschijnt als een balk <b>bovenaan elke pagina van elke module</b> — u kunt het dus niet missen, waar u ook aan het werk bent.</p>
  <h3>Verschijnt en verdwijnt vanzelf</h3>
  <p>U geeft op <b>vanaf</b> wanneer en <b>tot</b> wanneer de melding zichtbaar is; standaard staat dat op 24 uur. Daarna is hij weg, zonder dat iemand iets hoeft te doen. Wilt u een bericht vooruit klaarzetten — bijvoorbeeld maandagochtend al het onderhoud van vrijdag aankondigen — zet <i>Vanaf</i> dan in de toekomst. Moet de melding er eerder af, gebruik <b>Nu stoppen</b>.</p>
  <h3>Drie soorten</h3>
  <p><b>Mededeling</b> voor gewoon nieuws, <b>Let op</b> voor gepland onderhoud, en <b>Urgent</b> voor een storing. Een urgente melding kan niemand wegklikken — die staat er juist omdat iedereen hem moet zien. Bij de andere twee mag de medewerker hem sluiten; zijn browser onthoudt dat. Past u de tekst daarna aan (<i>"het wordt toch 20.00 uur"</i>), dan verschijnt de melding opnieuw, óók bij wie hem al had weggeklikt.</p>
  <h3>Voor wie</h3>
  <p>Vinkt u niets aan, dan ziet <b>iedereen</b> de melding. U kunt hem ook beperken tot bepaalde rollen, bijvoorbeeld alleen de bibliotheek. Verlopen meldingen blijven in het overzicht staan, zodat terug te zien is wat er is omgeroepen en door wie.</p>

  <h2 id="h21">21. Vragen of problemen?</h2>
  <p>Neem bij vragen contact op met de systeembeheerder of Studentenzaken (szaken@iuasr.nl). Werkt iets niet zoals verwacht, meld dan wat u deed en wat u zag.</p>

  <div class="tip">Deze handleiding wordt bijgewerkt zodra er nieuwe functies bij komen. Kijk bij twijfel of u de meest recente versie hebt (zie de datum onderaan).</div>
